package ops

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

const (
	// WatchdogScriptName is the filename of the generated watchdog script.
	WatchdogScriptName = "watchdog.sh"

	// WatchdogCrontabComment is used to identify AGM watchdog entries in crontab.
	WatchdogCrontabComment = "# agm-watchdog"

	// WatchdogLogFile is the default log file for watchdog output.
	WatchdogLogFile = "watchdog.log"
)

// WatchdogPaths holds resolved filesystem paths for the watchdog.
type WatchdogPaths struct {
	BinDir     string // ~/.agm/bin/
	LogDir     string // ~/.agm/logs/
	ScriptPath string // ~/.agm/bin/watchdog.sh
	LogPath    string // ~/.agm/logs/watchdog.log
}

// ResolveWatchdogPaths computes watchdog paths from a home directory.
func ResolveWatchdogPaths(homeDir string) WatchdogPaths {
	agmDir := filepath.Join(homeDir, ".agm")
	return WatchdogPaths{
		BinDir:     filepath.Join(agmDir, "bin"),
		LogDir:     filepath.Join(agmDir, "logs"),
		ScriptPath: filepath.Join(agmDir, "bin", WatchdogScriptName),
		LogPath:    filepath.Join(agmDir, "logs", WatchdogLogFile),
	}
}

// GenerateWatchdogScript returns the shell script content for the watchdog.
// The script checks tmux server health and session presence, logging results.
func GenerateWatchdogScript(socketPath string, agmBin string) string {
	return fmt.Sprintf(`#!/usr/bin/env bash
# AGM Watchdog — tmux server crash recovery
# Generated by: agm admin install-watchdog
# Do not edit manually; re-run install-watchdog to regenerate.

set -euo pipefail

SOCKET_PATH="%s"
AGM_BIN="%s"
TIMESTAMP=$(date -u '+%%Y-%%m-%%dT%%H:%%M:%%SZ')

log() {
    printf '%%s [watchdog] %%s\n' "$TIMESTAMP" "$1"
}

# --- Check 1: Is tmux server alive? ---
if tmux -S "$SOCKET_PATH" list-sessions >/dev/null 2>&1; then
    TMUX_ALIVE=true
else
    TMUX_ALIVE=false
fi

if [ "$TMUX_ALIVE" = false ]; then
    log "CRASH DETECTED: tmux server not responding on $SOCKET_PATH"

    # Remove stale socket if present
    if [ -e "$SOCKET_PATH" ]; then
        rm -f "$SOCKET_PATH"
        log "Removed stale socket: $SOCKET_PATH"
    fi

    # Restart tmux server (detached, empty session that will be cleaned up)
    tmux -S "$SOCKET_PATH" new-session -d -s _watchdog_recovery 2>/dev/null || true
    if tmux -S "$SOCKET_PATH" list-sessions >/dev/null 2>&1; then
        log "tmux server restarted successfully"
        # Kill the bootstrap session — it was only needed to start the server
        tmux -S "$SOCKET_PATH" kill-session -t _watchdog_recovery 2>/dev/null || true
    else
        log "ERROR: failed to restart tmux server"
        exit 1
    fi

    # Attempt to recover sessions from AGM database
    if command -v "$AGM_BIN" >/dev/null 2>&1; then
        log "Attempting session recovery via $AGM_BIN..."
        ACTIVE_SESSIONS=$("$AGM_BIN" session list --status active --output json 2>/dev/null || true)
        if [ -n "$ACTIVE_SESSIONS" ]; then
            log "Found active sessions in database; manual recovery may be needed"
            log "Run: $AGM_BIN session resume-all"
        fi
    fi
    exit 0
fi

# --- Check 2: Are expected sessions present? ---
LIVE_SESSIONS=$(tmux -S "$SOCKET_PATH" list-sessions -F '##{session_name}' 2>/dev/null || true)

if command -v "$AGM_BIN" >/dev/null 2>&1; then
    EXPECTED=$("$AGM_BIN" session list --status active --output json 2>/dev/null || true)
    if [ -n "$EXPECTED" ]; then
        # Parse session names from JSON (lightweight — no jq dependency)
        EXPECTED_NAMES=$(printf '%%s' "$EXPECTED" | grep -o '"name":"[^"]*"' | cut -d'"' -f4)
        MISSING=""
        while IFS= read -r name; do
            [ -z "$name" ] && continue
            if ! printf '%%s' "$LIVE_SESSIONS" | grep -qF "$name"; then
                MISSING="${MISSING}${name} "
            fi
        done <<< "$EXPECTED_NAMES"

        if [ -n "$MISSING" ]; then
            log "MISSING SESSIONS: $MISSING"
            log "Run: $AGM_BIN session resume-all"
        fi
    fi
fi
`, socketPath, agmBin)
}

// InstallWatchdog writes the watchdog script and installs a crontab entry.
func InstallWatchdog(paths WatchdogPaths, socketPath, agmBin string) error {
	// Create directories
	if err := os.MkdirAll(paths.BinDir, 0755); err != nil {
		return fmt.Errorf("create bin dir: %w", err)
	}
	if err := os.MkdirAll(paths.LogDir, 0755); err != nil {
		return fmt.Errorf("create log dir: %w", err)
	}

	// Write script
	script := GenerateWatchdogScript(socketPath, agmBin)
	if err := os.WriteFile(paths.ScriptPath, []byte(script), 0755); err != nil {
		return fmt.Errorf("write watchdog script: %w", err)
	}

	// Install crontab entry
	if err := installCrontabEntry(paths.ScriptPath, paths.LogPath); err != nil {
		return fmt.Errorf("install crontab: %w", err)
	}

	return nil
}

// UninstallWatchdog removes the crontab entry and the watchdog script.
func UninstallWatchdog(paths WatchdogPaths) error {
	// Remove crontab entry
	if err := removeCrontabEntry(); err != nil {
		return fmt.Errorf("remove crontab: %w", err)
	}

	// Remove script file
	if err := os.Remove(paths.ScriptPath); err != nil && !os.IsNotExist(err) {
		return fmt.Errorf("remove watchdog script: %w", err)
	}

	return nil
}

// IsWatchdogInstalled checks whether the watchdog crontab entry exists.
func IsWatchdogInstalled(paths WatchdogPaths) bool {
	// Check script exists
	if _, err := os.Stat(paths.ScriptPath); err != nil {
		return false
	}

	// Check crontab entry
	existing, err := getCurrentCrontab()
	if err != nil {
		return false
	}

	return strings.Contains(existing, WatchdogCrontabComment)
}

// getCurrentCrontab returns the current user crontab content.
func getCurrentCrontab() (string, error) {
	out, err := exec.Command("crontab", "-l").CombinedOutput()
	if err != nil {
		// "no crontab for user" is not an error for our purposes
		if strings.Contains(string(out), "no crontab") {
			return "", nil
		}
		return "", fmt.Errorf("crontab -l: %w: %s", err, out)
	}
	return string(out), nil
}

// installCrontabEntry adds the watchdog line to the user's crontab.
func installCrontabEntry(scriptPath, logPath string) error {
	existing, err := getCurrentCrontab()
	if err != nil {
		return err
	}

	// Check if already installed
	if strings.Contains(existing, WatchdogCrontabComment) {
		// Replace existing entry
		existing = removeWatchdogLines(existing)
	}

	entry := fmt.Sprintf("%s\n* * * * * %s >> %s 2>&1\n",
		WatchdogCrontabComment, scriptPath, logPath)

	newCrontab := strings.TrimRight(existing, "\n")
	if newCrontab != "" {
		newCrontab += "\n"
	}
	newCrontab += entry

	return setCrontab(newCrontab)
}

// removeCrontabEntry removes the watchdog lines from the user's crontab.
func removeCrontabEntry() error {
	existing, err := getCurrentCrontab()
	if err != nil {
		return err
	}

	if !strings.Contains(existing, WatchdogCrontabComment) {
		return nil // Nothing to remove
	}

	cleaned := removeWatchdogLines(existing)
	cleaned = strings.TrimRight(cleaned, "\n")

	if strings.TrimSpace(cleaned) == "" {
		// Crontab is now empty — remove it entirely
		return exec.Command("crontab", "-r").Run()
	}

	return setCrontab(cleaned + "\n")
}

// removeWatchdogLines strips the watchdog comment and the line following it.
func removeWatchdogLines(crontab string) string {
	lines := strings.Split(crontab, "\n")
	var result []string
	skip := false
	for _, line := range lines {
		if strings.TrimSpace(line) == WatchdogCrontabComment {
			skip = true // skip this line and the next (the actual cron entry)
			continue
		}
		if skip {
			skip = false
			continue
		}
		result = append(result, line)
	}
	return strings.Join(result, "\n")
}

// setCrontab writes a new crontab from the given content.
func setCrontab(content string) error {
	cmd := exec.Command("crontab", "-")
	cmd.Stdin = strings.NewReader(content)
	out, err := cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("crontab -: %w: %s", err, out)
	}
	return nil
}
