C4Context
    title System Context diagram for Internet Banking System

    Person(customer, "Personal Banking Customer", "A customer of the bank")
    System(banking_system, "Internet Banking System", "Allows customers to view information about their bank accounts")

    System_Ext(email_system, "E-mail System", "The internal Microsoft Exchange e-mail system")
    System_Ext(mainframe, "Mainframe Banking System", "Stores all of the core banking information")

    Rel(customer, banking_system, "Uses")
    Rel(banking_system, email_system, "Sends e-mail", "SMTP")
    Rel(banking_system, mainframe, "Uses")
