package monitoring

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"text/template"
)

// GitHookManager manages git hook installation for commit monitoring
type GitHookManager struct {
	agentID   string
	repoPath  string
	eventFile string
}

// NewGitHookManager creates a new git hook manager
func NewGitHookManager(agentID, repoPath, eventFile string) (*GitHookManager, error) {
	return &GitHookManager{
		agentID:   agentID,
		repoPath:  repoPath,
		eventFile: eventFile,
	}, nil
}

// InstallHooks installs post-commit hook for monitoring
func (ghm *GitHookManager) InstallHooks() error {
	// Check if .git directory exists
	gitDir := filepath.Join(ghm.repoPath, ".git")
	if _, err := os.Stat(gitDir); os.IsNotExist(err) {
		return fmt.Errorf("not a git repository: %s", ghm.repoPath)
	}

	hookPath := filepath.Join(gitDir, "hooks", "post-commit")

	// Backup existing hook if present
	if _, err := os.Stat(hookPath); err == nil {
		backupPath := hookPath + ".backup"
		if err := os.Rename(hookPath, backupPath); err != nil {
			return fmt.Errorf("failed to backup existing hook: %w", err)
		}
	}

	// Generate hook from template
	hookContent, err := ghm.generateHook()
	if err != nil {
		return fmt.Errorf("failed to generate hook: %w", err)
	}

	// Write hook file
	if err := os.WriteFile(hookPath, []byte(hookContent), 0o700); err != nil { //#nosec G306 -- executable hook
		return fmt.Errorf("failed to write hook: %w", err)
	}

	return nil
}

// UninstallHooks removes monitoring hook and restores backup
func (ghm *GitHookManager) UninstallHooks() error {
	gitDir := filepath.Join(ghm.repoPath, ".git")
	hookPath := filepath.Join(gitDir, "hooks", "post-commit")
	backupPath := hookPath + ".backup"

	// Remove our hook
	if err := os.Remove(hookPath); err != nil && !os.IsNotExist(err) {
		return fmt.Errorf("failed to remove hook: %w", err)
	}

	// Restore backup if exists
	if _, err := os.Stat(backupPath); err == nil {
		if err := os.Rename(backupPath, hookPath); err != nil {
			return fmt.Errorf("failed to restore backup: %w", err)
		}
	}

	return nil
}

// IsHookInstalled checks if monitoring hook is installed
func (ghm *GitHookManager) IsHookInstalled() bool {
	hookPath := filepath.Join(ghm.repoPath, ".git/hooks/post-commit")
	content, err := os.ReadFile(hookPath)
	if err != nil {
		return false
	}
	// Check for our marker comment
	return bytes.Contains(content, []byte("Auto-generated by engram monitoring"))
}

// generateHook creates hook script from template
func (ghm *GitHookManager) generateHook() (string, error) {
	tmpl := `#!/bin/bash
# Auto-generated by engram monitoring - DO NOT EDIT
AGENT_ID="{{.AgentID}}"
EVENT_FILE="{{.EventFile}}"

COMMIT=$(git rev-parse HEAD 2>/dev/null || echo "unknown")
MESSAGE=$(git log -1 --pretty=%B 2>/dev/null | head -1 | sed 's/"/\\"/g')
AUTHOR=$(git log -1 --pretty=%an 2>/dev/null | sed 's/"/\\"/g')
EMAIL=$(git log -1 --pretty=%ae 2>/dev/null)
TIMESTAMP=$(date -Iseconds 2>/dev/null || date)
FILES_CHANGED=$(git diff-tree --no-commit-id --name-only -r HEAD 2>/dev/null | wc -l)

# Extract insertions/deletions from git diff
STATS=$(git diff HEAD~ HEAD --shortstat 2>/dev/null)
INSERTIONS=$(echo "$STATS" | grep -oE '[0-9]+ insertion' | grep -oE '[0-9]+' || echo 0)
DELETIONS=$(echo "$STATS" | grep -oE '[0-9]+ deletion' | grep -oE '[0-9]+' || echo 0)

# Append event to JSONL file
cat >> "$EVENT_FILE" <<EOF
{"event_type":"sub_agent.git.commit","agent_id":"$AGENT_ID","timestamp":"$TIMESTAMP","data":{"commit":"$COMMIT","message":"$MESSAGE","author":"$AUTHOR","email":"$EMAIL","files_changed":$FILES_CHANGED,"insertions":$INSERTIONS,"deletions":$DELETIONS}}
EOF
`

	t, err := template.New("hook").Parse(tmpl)
	if err != nil {
		return "", err
	}

	var buf bytes.Buffer
	err = t.Execute(&buf, struct {
		AgentID   string
		EventFile string
	}{
		AgentID:   ghm.agentID,
		EventFile: ghm.eventFile,
	})
	if err != nil {
		return "", err
	}

	return buf.String(), nil
}
