package selfimprove

import (
	"bytes"
	"context"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"strings"
	"time"
)

// PRApplier implements Applier by creating a git branch, writing the
// hypothesis document, committing, pushing, and opening a draft GitHub PR.
//
// It is safe for sequential use within a single session; it is NOT safe for
// concurrent Apply calls against the same RepoRoot (git branches are
// process-global state).
type PRApplier struct {
	// RepoRoot is the absolute path to the working tree where changes are made.
	RepoRoot string
	// Remote is the git remote to push to; defaults to "origin".
	Remote string
	// ProposeOnly opens a draft PR instead of merging when true.
	ProposeOnly bool
}

// sanitizeBranchName turns an arbitrary hypothesis ID into a safe git branch
// name suffix:
//   - non-alphanumeric characters become "-"
//   - leading/trailing "-" are stripped
//   - result is truncated to 40 characters
func sanitizeBranchName(id string) string {
	re := regexp.MustCompile(`[^a-zA-Z0-9]+`)
	s := re.ReplaceAllString(id, "-")
	s = strings.Trim(s, "-")
	if len(s) > 40 {
		s = s[:40]
		s = strings.TrimRight(s, "-")
	}
	return s
}

// remote returns the configured remote, falling back to "origin".
func (r PRApplier) remote() string {
	if r.Remote != "" {
		return r.Remote
	}
	return "origin"
}

// gitC runs a git subcommand in RepoRoot with the given extra env vars.
func (r PRApplier) gitC(ctx context.Context, extraEnv []string, args ...string) error {
	allArgs := append([]string{"-C", r.RepoRoot}, args...)
	cmd := exec.CommandContext(ctx, "git", allArgs...)
	if len(extraEnv) > 0 {
		cmd.Env = append(os.Environ(), extraEnv...)
	}
	var errOut bytes.Buffer
	cmd.Stderr = &errOut
	if err := cmd.Run(); err != nil {
		return fmt.Errorf("git %v: %w\nstderr: %s", args, err, errOut.String())
	}
	return nil
}

// Apply creates a branch, writes the hypothesis doc, commits, pushes, and
// opens a draft PR.  Returns a Patch whose Diff field holds the PR URL.
func (r PRApplier) Apply(ctx context.Context, h Hypothesis) (Patch, error) {
	branch := "selfimprove/" + sanitizeBranchName(h.ID)

	// 1. Create and switch to the new branch.
	if err := r.gitC(ctx, nil, "checkout", "-b", branch); err != nil {
		return Patch{}, fmt.Errorf("pr_applier: checkout: %w", err)
	}

	// 2. Write the hypothesis document.
	timestamp := time.Now().UTC().Format("20060102T150405Z")
	docPath := filepath.Join(r.RepoRoot, "docs", "hypotheses",
		fmt.Sprintf("%s-%s.md", timestamp, sanitizeBranchName(h.ID)))
	if err := os.MkdirAll(filepath.Dir(docPath), 0o755); err != nil {
		return Patch{}, fmt.Errorf("pr_applier: mkdir hypotheses: %w", err)
	}
	content := fmt.Sprintf(
		"# Hypothesis: %s\n\n**ID:** %s\n**Source:** %s\n**Confidence:** %.2f\n\n## Rationale\n\n%s\n",
		h.Description, h.ID, h.Source, h.Confidence, h.Rationale,
	)
	if err := os.WriteFile(docPath, []byte(content), 0o600); err != nil {
		return Patch{}, fmt.Errorf("pr_applier: write doc: %w", err)
	}

	// 3. Stage and commit.
	if err := r.gitC(ctx, nil, "add", "docs/hypotheses/"); err != nil {
		return Patch{}, fmt.Errorf("pr_applier: git add: %w", err)
	}
	commitMsg := "selfimprove: propose " + h.ID
	if err := r.gitC(ctx, nil, "commit", "-m", commitMsg); err != nil {
		return Patch{}, fmt.Errorf("pr_applier: git commit: %w", err)
	}

	// 4. Push with a 30-second timeout and no terminal prompt.
	pushCtx, cancel := context.WithTimeout(ctx, 30*time.Second)
	defer cancel()
	if err := r.gitC(pushCtx,
		[]string{"GIT_TERMINAL_PROMPT=0"},
		"push", r.remote(), branch,
	); err != nil {
		return Patch{}, fmt.Errorf("pr_applier: git push: %w", err)
	}

	// 5. Open a draft PR.
	body := fmt.Sprintf(
		"## selfimprove proposal\n\n**ID:** %s\n**Source:** %s\n**Confidence:** %.2f\n\n### Rationale\n\n%s\n\n---\n*Generated by PRApplier*\n",
		h.ID, h.Source, h.Confidence, h.Rationale,
	)
	prArgs := []string{
		"pr", "create",
		"--title", "selfimprove: " + h.Description,
		"--body", body,
		"--draft",
	}
	ghCmd := exec.CommandContext(ctx, "gh")
	ghCmd.Args = append([]string{"gh"}, prArgs...)
	ghCmd.Dir = r.RepoRoot
	var prOut bytes.Buffer
	var prErr bytes.Buffer
	ghCmd.Stdout = &prOut
	ghCmd.Stderr = &prErr
	if err := ghCmd.Run(); err != nil {
		return Patch{}, fmt.Errorf("pr_applier: gh pr create: %w\nstderr: %s", err, prErr.String())
	}
	prURL := strings.TrimSpace(prOut.String())

	return Patch{
		Hypothesis: h,
		Diff:       prURL,
		AppliedAt:  time.Now().UTC(),
	}, nil
}

// Revert deletes the branch that Apply created.  It is best-effort and never
// returns an error — a failed cleanup is logged nowhere but also cannot break
// the caller.
func (r PRApplier) Revert(ctx context.Context, p Patch) error {
	branch := "selfimprove/" + sanitizeBranchName(p.Hypothesis.ID)
	// Switch back to main first so we can delete the branch.
	_ = r.gitC(ctx, nil, "checkout", "main")
	_ = r.gitC(ctx, nil, "branch", "-D", branch)
	return nil
}
