package codegen

import (
	"path/filepath"
)

const mcpTemplate = `// Code generated by codegen. DO NOT EDIT.
// Format version: 1

package {{.Package}}

import (
	"context"

	"github.com/modelcontextprotocol/go-sdk/mcp"
)

{{range .Ops}}
// {{.VarName}}MCPInput is the MCP input schema for {{.Op.Name}}.
type {{.VarName}}MCPInput struct {
	{{range $.MCPFields .}}
	{{.GoName}} {{.GoType}} ` + "`" + `json:"{{.JSONName}}{{if not .Required}},omitempty{{end}}" jsonschema:"description={{.Description}}{{if .Required}},required{{end}}{{if .Enum}},enum={{.EnumCSV}}{{end}}"` + "`" + `
	{{- end}}
}

// Add{{.VarName}}Tool registers the {{.Op.MCP.ToolName}} MCP tool.
func Add{{.VarName}}Tool(server *mcp.Server, newOpCtx func() (*OpContext, func(), error)) {
	{{- if $.Stub .}}
	// WARNING: {{.Op.Name}} is a stub. The handler does not perform the actual operation.
	{{- end}}
	mcp.AddTool(server, &mcp.Tool{
		Name:        "{{.Op.MCP.ToolName}}",
		Description: "{{if $.Stub .}}[STUB] {{end}}{{.MCPDescription}}",
	}, func(_ context.Context, _ *mcp.CallToolRequest, input {{.VarName}}MCPInput) (*mcp.CallToolResult, any, error) {
		opCtx, cleanup, err := newOpCtx()
		if err != nil {
			return mcpError(err), nil, nil
		}
		defer cleanup()

		req := &{{.RequestType}}{
			{{range $.MCPFields .}}
			{{.GoName}}: input.{{.GoName}},
			{{- end}}
		}

		result, opErr := {{.HandlerFunc}}(opCtx, req)
		if opErr != nil {
			return mcpError(opErr), nil, nil
		}

		return mcpSuccess(result), result, nil
	})
}
{{end}}
`

// GenerateMCP produces a Go source file with MCP tool registrations for all ops with MCP surfaces.
func GenerateMCP(ops []OpIR, outDir, pkg string, buildIgnore bool) error {
	mcpOps := filterOps(ops, func(o OpIR) bool { return o.Op.MCP != nil })
	if len(mcpOps) == 0 {
		return nil
	}

	data := mcpTemplateData{
		Package: pkg,
		Ops:     mcpOps,
	}

	return renderGoTemplate("mcp", mcpTemplate, data, filepath.Join(outDir, "codegen_mcp.go"), buildIgnore)
}

type mcpTemplateData struct {
	Package string
	Ops     []OpIR
}

func (d mcpTemplateData) MCPFields(o OpIR) []FieldIR { return o.MCPFields() }
func (d mcpTemplateData) Stub(o OpIR) bool           { return o.Op.Stub }
