package codegen

import (
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"strings"
	"text/template"
)

const cliTemplate = `// Code generated by codegen. DO NOT EDIT.
// Format version: 1

package {{.Package}}

import (
	"fmt"

	"github.com/spf13/cobra"
)

// OpCtxFunc creates an OpContext from a Cobra command.
type OpCtxFunc func(cmd *cobra.Command) (*OpContext, func(), error)

{{range .Ops}}
// New{{.VarName}}Cmd creates the Cobra command for {{.Op.Name}}.
func New{{.VarName}}Cmd(newOpCtx OpCtxFunc) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "{{.Op.CLI.Use}}",
		{{- if $.Deprecated .}}
		Short: "[DEPRECATED] {{.Op.Description}}",
		Deprecated: "{{.Op.DeprecatedMsg}}",
		{{- else}}
		Short: "{{.Op.Description}}",
		{{- end}}
		{{- if .Op.CLI.Aliases}}
		Aliases: []string{ {{range .Op.CLI.Aliases}}"{{.}}", {{end}} },
		{{- end}}
		{{- if .Op.CLI.Hidden}}
		Hidden: true,
		{{- end}}
		RunE: func(cmd *cobra.Command, args []string) error {
			{{- if $.Stub .}}
			// WARNING: {{.Op.Name}} is a stub. The handler does not perform the actual operation.
			fmt.Fprintln(cmd.ErrOrStderr(), "WARNING: {{.Op.Name}} is a stub operation")
			{{- end}}

			opCtx, cleanup, err := newOpCtx(cmd)
			if err != nil {
				return fmt.Errorf("failed to create context: %w", err)
			}
			defer cleanup()

			req := &{{.RequestType}}{}
			{{range $.CLIFields .}}
			{{- if .IsPositional}}
			if len(args) > {{.Pos}} {
				req.{{.GoName}} = args[{{.Pos}}]
			}
			{{- else}}
			req.{{.GoName}}, _ = cmd.Flags().Get{{.FlagType}}("{{.FlagName}}")
			{{- end}}
			{{- end}}

			{{range $.CLIFields .}}
			{{- if .Enum}}
			// Validate enum for {{.FlagName}}
			switch req.{{.GoName}} {
			case {{range $i, $v := .Enum}}{{if $i}}, {{end}}"{{$v}}"{{end}}:
				// valid
			default:
				return fmt.Errorf("invalid value for --{{.FlagName}}: %q (allowed: {{.EnumCSV}})", req.{{.GoName}})
			}
			{{- end}}
			{{- end}}

			result, opErr := {{.HandlerFunc}}(opCtx, req)
			if opErr != nil {
				return opErr
			}

			_ = result
			fmt.Println("OK")
			return nil
		},
	}

	{{range $.CLIFields .}}
	{{- if not .IsPositional}}
	cmd.Flags().{{.FlagRegistration}}
	{{- if .Required}}
	_ = cmd.MarkFlagRequired("{{.FlagName}}")
	{{- end}}
	{{- if .Hidden}}
	_ = cmd.Flags().MarkHidden("{{.FlagName}}")
	{{- end}}
	{{- end}}
	{{- end}}

	return cmd
}
{{end}}
`

// GenerateCLI produces a Go source file with Cobra commands for all ops with CLI surfaces.
func GenerateCLI(ops []OpIR, outDir, pkg string, buildIgnore bool) error {
	cliOps := filterOps(ops, func(o OpIR) bool { return o.Op.CLI != nil })
	if len(cliOps) == 0 {
		return nil
	}

	data := cliTemplateData{
		Package: pkg,
		Ops:     cliOps,
	}

	return renderGoTemplate("cli", cliTemplate, data, filepath.Join(outDir, "codegen_cli.go"), buildIgnore)
}

type cliTemplateData struct {
	Package string
	Ops     []OpIR
}

// Template helper methods on cliTemplateData to avoid method calls on OpIR in templates.
func (d cliTemplateData) CLIFields(o OpIR) []FieldIR { return o.CLIFields() }
func (d cliTemplateData) Deprecated(o OpIR) bool     { return o.Op.Deprecated }
func (d cliTemplateData) Stub(o OpIR) bool           { return o.Op.Stub }

func filterOps(ops []OpIR, pred func(OpIR) bool) []OpIR {
	var out []OpIR
	for _, o := range ops {
		if pred(o) {
			out = append(out, o)
		}
	}
	return out
}

func renderGoTemplate(name, tmplStr string, data any, outPath string, buildIgnore bool) error {
	tmpl, err := template.New(name).Parse(tmplStr)
	if err != nil {
		return fmt.Errorf("parsing %s template: %w", name, err)
	}

	var buf strings.Builder
	if buildIgnore {
		buf.WriteString("//go:build ignore\n\n")
	}
	if err := tmpl.Execute(&buf, data); err != nil {
		return fmt.Errorf("executing %s template: %w", name, err)
	}

	formatted, err := format.Source([]byte(buf.String()))
	if err != nil {
		return fmt.Errorf("formatting %s output: %w\n---\n%s", name, err, buf.String())
	}

	if err := os.WriteFile(outPath, formatted, 0o644); err != nil {
		return fmt.Errorf("writing %s: %w", outPath, err)
	}

	return nil
}

