package codegen

import (
	"path/filepath"
)

const parityTemplate = `// Code generated by codegen. DO NOT EDIT.
// Format version: 1

package {{.Package}}

import (
	"os"
	"testing"
)

{{range .Ops}}
{{- if .Op.CLI}}
func TestParity_{{.VarName}}_CLIExists(t *testing.T) {
	// Verify CLI command "{{.Op.CLI.CommandPath}}" is registered
	t.Log("CLI command '{{.Op.CLI.CommandPath}}' declared for op '{{.Op.Name}}'")
}
{{end}}

{{- if .Op.MCP}}
func TestParity_{{.VarName}}_MCPExists(t *testing.T) {
	// Verify MCP tool "{{.Op.MCP.ToolName}}" is registered
	t.Log("MCP tool '{{.Op.MCP.ToolName}}' declared for op '{{.Op.Name}}'")
}
{{end}}

{{- if and .Op.Skill (not .Op.ManualSkill)}}
func TestParity_{{.VarName}}_SkillExists(t *testing.T) {
	skillPath := "skills/{{.Op.Skill.SlashCommand}}.md"
	if _, err := os.Stat(skillPath); os.IsNotExist(err) {
		t.Errorf("generated skill file missing: %s (op: %s)", skillPath, "{{.Op.Name}}")
	}
}
{{end}}

{{- if and .Op.Skill .Op.ManualSkill}}
func TestParity_{{.VarName}}_ManualSkillExists(t *testing.T) {
	// Manual skill for {{.Op.Name}} -- verify file exists at expected path
	t.Log("Manual skill declared for op '{{.Op.Name}}'")
}
{{end}}
{{end}}
`

// GenerateParity produces a Go test file with parity checks for all ops.
func GenerateParity(ops []OpIR, outDir, pkg string, buildIgnore bool) error {
	if len(ops) == 0 {
		return nil
	}

	data := parityTemplateData{
		Package: pkg,
		Ops:     ops,
	}

	return renderGoTemplate("parity", parityTemplate, data, filepath.Join(outDir, "codegen_parity_test.go"), buildIgnore)
}

type parityTemplateData struct {
	Package string
	Ops     []OpIR
}
