// Code generated by sync-spec-governance; DO NOT EDIT.

package earslint

import (
	"testing"
)

func TestDefaultConfig_Compiles(t *testing.T) {
	if _, err := New(DefaultConfig()); err != nil {
		t.Fatalf("default config should compile: %v", err)
	}
	if len(DefaultConfig().Patterns) < 5 {
		t.Fatalf("expected at least the 5 EARS patterns, got %d", len(DefaultConfig().Patterns))
	}
}
