package checks

import (
	"context"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/vbonnet/dear-agent/pkg/audit"
)

// parseFunc returns the first FuncDecl in src. The fixture is parsed
// at test time rather than baked as a fixture file because the test
// inputs are tiny and inlining keeps the assertion next to the code
// shape it asserts on.
func parseFunc(t *testing.T, src string) *ast.FuncDecl {
	t.Helper()
	fset := token.NewFileSet()
	file, err := parser.ParseFile(fset, "x.go", src, parser.SkipObjectResolution)
	if err != nil {
		t.Fatalf("parse fixture: %v", err)
	}
	for _, decl := range file.Decls {
		if fn, ok := decl.(*ast.FuncDecl); ok {
			return fn
		}
	}
	t.Fatalf("no FuncDecl in fixture")
	return nil
}

func TestCyclomaticComplexityLinear(t *testing.T) {
	fn := parseFunc(t, `package x
func Add(a, b int) int { return a + b }`)
	if got := cyclomaticComplexity(fn); got != 1 {
		t.Errorf("complexity = %d, want 1", got)
	}
}

func TestCyclomaticComplexityIfElse(t *testing.T) {
	fn := parseFunc(t, `package x
func Sign(n int) int {
	if n > 0 { return 1 }
	if n < 0 { return -1 }
	return 0
}`)
	// Two ifs → base 1 + 2 = 3. else does not add (it shares the
	// decision point with its if).
	if got := cyclomaticComplexity(fn); got != 3 {
		t.Errorf("complexity = %d, want 3", got)
	}
}

func TestCyclomaticComplexityShortCircuit(t *testing.T) {
	fn := parseFunc(t, `package x
func InRange(n int) bool {
	return n > 0 && n < 10 || n == 42
}`)
	// base 1 + && + || = 3.
	if got := cyclomaticComplexity(fn); got != 3 {
		t.Errorf("complexity = %d, want 3", got)
	}
}

func TestCyclomaticComplexitySwitchAndDefault(t *testing.T) {
	fn := parseFunc(t, `package x
func Kind(s string) string {
	switch s {
	case "a": return "alpha"
	case "b", "c": return "betagamma"
	default: return "other"
	}
}`)
	// base 1 + 2 case clauses = 3. default does not count (one case
	// list, not a new decision).
	if got := cyclomaticComplexity(fn); got != 3 {
		t.Errorf("complexity = %d, want 3", got)
	}
}

func TestCyclomaticComplexityForRangeSelect(t *testing.T) {
	fn := parseFunc(t, `package x
func Drain(ch chan int, xs []int) {
	for i := 0; i < 10; i++ { _ = i }
	for _, x := range xs { _ = x }
	select {
	case <-ch:
	case v := <-ch:
		_ = v
	default:
	}
}`)
	// base 1 + for + range + 2 select cases (default has no Comm) = 5.
	if got := cyclomaticComplexity(fn); got != 5 {
		t.Errorf("complexity = %d, want 5", got)
	}
}

func TestFuncDisplayName(t *testing.T) {
	cases := []struct {
		src  string
		want string
	}{
		{"package x\nfunc Plain() {}", "Plain"},
		{"package x\nfunc (s S) Method() {}", "S.Method"},
		{"package x\nfunc (s *S) PtrMethod() {}", "S.PtrMethod"},
		{"package x\nfunc (g G[T]) Generic() {}", "G.Generic"},
	}
	for _, tc := range cases {
		fn := parseFunc(t, tc.src)
		if got := funcDisplayName(fn); got != tc.want {
			t.Errorf("funcDisplayName(%q) = %q, want %q", tc.src, got, tc.want)
		}
	}
}

func TestIsGenerated(t *testing.T) {
	gen := `// Code generated by stringer -type Pill; DO NOT EDIT.

package x
func F() {}
`
	fset := token.NewFileSet()
	file, err := parser.ParseFile(fset, "x.go", gen, parser.ParseComments|parser.SkipObjectResolution)
	if err != nil {
		t.Fatalf("parse: %v", err)
	}
	if !isGenerated(file) {
		t.Error("expected generated marker to be detected")
	}

	hand := `package x
// just a regular comment, not a marker
func F() {}
`
	file, err = parser.ParseFile(fset, "y.go", hand, parser.ParseComments|parser.SkipObjectResolution)
	if err != nil {
		t.Fatalf("parse hand: %v", err)
	}
	if isGenerated(file) {
		t.Error("expected non-generated file to not match")
	}
}

// TestComplexityCheckRun is the integration-shaped test: build a
// tiny repo on disk, run the check, assert the findings list.
func TestComplexityCheckRun(t *testing.T) {
	dir := t.TempDir()
	writeGo(t, dir, "simple.go", `package x
func Add(a, b int) int { return a + b }`)
	writeGo(t, dir, "branchy.go", `package x
func Branchy(n int) int {
	if n > 0 { n++ }
	if n > 1 { n++ }
	if n > 2 { n++ }
	if n > 3 { n++ }
	if n > 4 { n++ }
	if n > 5 { n++ }
	if n > 6 { n++ }
	if n > 7 { n++ }
	if n > 8 { n++ }
	if n > 9 { n++ }
	if n > 10 { n++ }
	if n > 11 { n++ }
	if n > 12 { n++ }
	if n > 13 { n++ }
	if n > 14 { n++ }
	return n
}`)
	// Test files are skipped by default.
	writeGo(t, dir, "skipped_test.go", `package x
func TestThing(t *testing.T) {
	for i := 0; i < 100; i++ {
		if i%2 == 0 { _ = i }
	}
}`)

	check := ComplexityCheck{}
	res, err := check.Run(context.Background(), audit.Env{
		RepoRoot:   dir,
		WorkingDir: dir,
		Config:     map[string]any{"max_complexity": 10},
	})
	if err != nil {
		t.Fatalf("Run: %v", err)
	}
	if res.Status != audit.StatusOK {
		t.Errorf("Status = %q, want ok", res.Status)
	}
	if len(res.Findings) != 1 {
		t.Fatalf("findings = %d, want 1; got %+v", len(res.Findings), res.Findings)
	}
	f := res.Findings[0]
	if f.Severity != audit.SeverityP2 {
		t.Errorf("severity = %q, want P2", f.Severity)
	}
	if !strings.Contains(f.Title, "Branchy") {
		t.Errorf("title %q does not name the function", f.Title)
	}
	if got, _ := f.Evidence["function"].(string); got != "Branchy" {
		t.Errorf("evidence.function = %q, want Branchy", got)
	}
	if got, _ := f.Evidence["complexity"].(int); got <= 10 {
		t.Errorf("evidence.complexity = %d, want > 10", got)
	}
	// Path should be relative to the working dir; the function lives
	// in branchy.go.
	if !strings.HasSuffix(f.Path, "branchy.go") {
		t.Errorf("path = %q, want suffix branchy.go", f.Path)
	}
}

func TestComplexityCheckSkipsVendorAndGenerated(t *testing.T) {
	dir := t.TempDir()
	// Generated file: even though it is over the threshold, the
	// generated marker should suppress findings.
	writeGo(t, dir, "gen.go", `// Code generated by stringer; DO NOT EDIT.

package x
func Big(n int) int {
	if n > 0 { n++ }
	if n > 1 { n++ }
	if n > 2 { n++ }
	if n > 3 { n++ }
	if n > 4 { n++ }
	return n
}`)
	// vendor/ tree should be skipped wholesale.
	if err := os.MkdirAll(filepath.Join(dir, "vendor", "x"), 0o755); err != nil {
		t.Fatalf("mkdir vendor: %v", err)
	}
	writeGo(t, filepath.Join(dir, "vendor", "x"), "v.go", `package x
func V(n int) int {
	if n > 0 { n++ }
	if n > 1 { n++ }
	if n > 2 { n++ }
	if n > 3 { n++ }
	return n
}`)

	check := ComplexityCheck{}
	res, err := check.Run(context.Background(), audit.Env{
		RepoRoot:   dir,
		WorkingDir: dir,
		Config:     map[string]any{"max_complexity": 1},
	})
	if err != nil {
		t.Fatalf("Run: %v", err)
	}
	if len(res.Findings) != 0 {
		t.Errorf("expected 0 findings (generated + vendor skipped); got %+v", res.Findings)
	}
}

func TestComplexityCheckIncludeTestsKnob(t *testing.T) {
	dir := t.TempDir()
	writeGo(t, dir, "x_test.go", `package x
func Loud(n int) int {
	if n > 0 { n++ }
	if n > 1 { n++ }
	return n
}`)

	check := ComplexityCheck{}
	res, err := check.Run(context.Background(), audit.Env{
		RepoRoot:   dir,
		WorkingDir: dir,
		Config: map[string]any{
			"max_complexity": 1,
			"include_tests":  true,
		},
	})
	if err != nil {
		t.Fatalf("Run: %v", err)
	}
	if len(res.Findings) != 1 {
		t.Fatalf("expected 1 finding when include_tests=true; got %d", len(res.Findings))
	}
}

func TestComplexityCheckMetaIsValid(t *testing.T) {
	if err := (ComplexityCheck{}).Meta().Validate(); err != nil {
		t.Errorf("Meta.Validate: %v", err)
	}
}

func TestComplexityCheckRegisteredInDefault(t *testing.T) {
	if _, ok := audit.Default.Lookup("complexity"); !ok {
		t.Error("complexity not registered in audit.Default")
	}
}

// writeGo writes src to dir/name. It is a tiny helper: tests in this
// package usually inline file content but we have a few callers here.
func writeGo(t *testing.T, dir, name, src string) {
	t.Helper()
	if err := os.WriteFile(filepath.Join(dir, name), []byte(src), 0o644); err != nil {
		t.Fatalf("write %s: %v", name, err)
	}
}
