package trigger

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/vbonnet/dear-agent/pkg/engram"
)

func TestInjectWritesFile(t *testing.T) {
	tmpDir := t.TempDir()

	injector := NewFileInjector()
	engrams := []*engram.Engram{
		{
			Path: "/test/engrams/error-handling.ai.md",
			Frontmatter: engram.Frontmatter{
				Title: "Error Handling in Go",
			},
			Content: "Always check error returns.\n",
		},
		{
			Path: "/test/engrams/testing.ai.md",
			Frontmatter: engram.Frontmatter{
				Title: "Testing Patterns",
			},
			Content: "Use table-driven tests.\n",
		},
	}

	err := injector.Inject(tmpDir, "phase.started", engrams)
	if err != nil {
		t.Fatalf("Inject failed: %v", err)
	}

	outputPath := filepath.Join(tmpDir, ".engram", "triggered-context.md")
	data, err := os.ReadFile(outputPath)
	if err != nil {
		t.Fatalf("Failed to read output file: %v", err)
	}

	content := string(data)

	// Check header
	if !strings.Contains(content, "<!-- Auto-generated by engram trigger engine. Do not edit. -->") {
		t.Error("Missing auto-generated header")
	}
	if !strings.Contains(content, "<!-- Triggered at:") {
		t.Error("Missing triggered-at timestamp")
	}

	// Check first engram
	if !strings.Contains(content, "<!-- Event: phase.started -->") {
		t.Error("Missing event comment")
	}
	if !strings.Contains(content, "## Error Handling in Go") {
		t.Error("Missing first engram title")
	}
	if !strings.Contains(content, "Always check error returns.") {
		t.Error("Missing first engram content")
	}

	// Check second engram
	if !strings.Contains(content, "## Testing Patterns") {
		t.Error("Missing second engram title")
	}
	if !strings.Contains(content, "Use table-driven tests.") {
		t.Error("Missing second engram content")
	}

	// Check separator
	if !strings.Contains(content, "---") {
		t.Error("Missing separator between engrams")
	}
}

func TestInjectCreatesDirectory(t *testing.T) {
	tmpDir := t.TempDir()
	// Ensure .engram/ does not exist
	engramDir := filepath.Join(tmpDir, ".engram")
	if _, err := os.Stat(engramDir); err == nil {
		t.Fatal(".engram directory should not exist before injection")
	}

	injector := NewFileInjector()
	engrams := []*engram.Engram{
		{
			Path: "/test/engrams/test.ai.md",
			Frontmatter: engram.Frontmatter{
				Title: "Test Engram",
			},
			Content: "Test content.\n",
		},
	}

	err := injector.Inject(tmpDir, "task.started", engrams)
	if err != nil {
		t.Fatalf("Inject failed: %v", err)
	}

	// Verify directory was created
	if _, err := os.Stat(engramDir); os.IsNotExist(err) {
		t.Error(".engram directory was not created")
	}

	// Verify file exists
	outputPath := filepath.Join(engramDir, "triggered-context.md")
	if _, err := os.Stat(outputPath); os.IsNotExist(err) {
		t.Error("triggered-context.md was not created")
	}
}

func TestInjectOverwrites(t *testing.T) {
	tmpDir := t.TempDir()
	injector := NewFileInjector()

	// First injection
	firstEngrams := []*engram.Engram{
		{
			Path: "/test/engrams/first.ai.md",
			Frontmatter: engram.Frontmatter{
				Title: "First Engram",
			},
			Content: "First content.\n",
		},
	}

	err := injector.Inject(tmpDir, "phase.started", firstEngrams)
	if err != nil {
		t.Fatalf("First inject failed: %v", err)
	}

	// Second injection (should overwrite)
	secondEngrams := []*engram.Engram{
		{
			Path: "/test/engrams/second.ai.md",
			Frontmatter: engram.Frontmatter{
				Title: "Second Engram",
			},
			Content: "Second content.\n",
		},
	}

	err = injector.Inject(tmpDir, "task.assigned", secondEngrams)
	if err != nil {
		t.Fatalf("Second inject failed: %v", err)
	}

	outputPath := filepath.Join(tmpDir, ".engram", "triggered-context.md")
	data, err := os.ReadFile(outputPath)
	if err != nil {
		t.Fatalf("Failed to read output file: %v", err)
	}

	content := string(data)

	// Should NOT contain first injection content
	if strings.Contains(content, "First Engram") {
		t.Error("First injection content should have been overwritten")
	}

	// Should contain second injection content
	if !strings.Contains(content, "Second Engram") {
		t.Error("Missing second injection content")
	}
	if !strings.Contains(content, "<!-- Event: task.assigned -->") {
		t.Error("Missing second event type")
	}
}

func TestInjectEmpty(t *testing.T) {
	tmpDir := t.TempDir()
	injector := NewFileInjector()

	// Inject with empty engram list
	err := injector.Inject(tmpDir, "phase.started", nil)
	if err != nil {
		t.Fatalf("Inject with empty list failed: %v", err)
	}

	outputPath := filepath.Join(tmpDir, ".engram", "triggered-context.md")
	data, err := os.ReadFile(outputPath)
	if err != nil {
		t.Fatalf("Failed to read output file: %v", err)
	}

	content := string(data)

	// Should have header
	if !strings.Contains(content, "<!-- Auto-generated by engram trigger engine. Do not edit. -->") {
		t.Error("Missing auto-generated header")
	}

	// Should NOT have any event comments or engram content
	if strings.Contains(content, "<!-- Event:") {
		t.Error("Should not have event comments for empty engram list")
	}
}
