package trigger

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/vbonnet/dear-agent/pkg/engram"
)

// FileInjector writes triggered engrams to a project's .engram/triggered-context.md file.
type FileInjector struct{}

// NewFileInjector creates a new FileInjector.
func NewFileInjector() *FileInjector {
	return &FileInjector{}
}

// Inject writes the given engrams to {projectRoot}/.engram/triggered-context.md.
// Creates the .engram/ directory when needed. Overwrites (not appends) on each call.
// Each engram is prefixed with an HTML comment showing the event source.
func (fi *FileInjector) Inject(projectRoot string, eventType string, engrams []*engram.Engram) error {
	engramDir := filepath.Join(projectRoot, ".engram")
	if err := os.MkdirAll(engramDir, 0755); err != nil {
		return fmt.Errorf("failed to create .engram directory: %w", err)
	}

	var sb strings.Builder

	// Write header
	sb.WriteString("<!-- Auto-generated by engram trigger engine. Do not edit. -->\n")
	fmt.Fprintf(&sb, "<!-- Triggered at: %s -->\n", time.Now().UTC().Format(time.RFC3339))

	// Write each engram
	for _, eg := range engrams {
		fmt.Fprintf(&sb, "\n<!-- Event: %s -->\n", eventType)
		fmt.Fprintf(&sb, "## %s\n", eg.Frontmatter.Title)
		sb.WriteString(eg.Content)
		sb.WriteString("\n---\n")
	}

	outputPath := filepath.Join(engramDir, "triggered-context.md")
	if err := os.WriteFile(outputPath, []byte(sb.String()), 0644); err != nil {
		return fmt.Errorf("failed to write triggered-context.md: %w", err)
	}

	return nil
}
