// Code generated by generate-patterns; DO NOT EDIT.
// Source: patterns/bash-anti-patterns.yaml

package validator

import "regexp"

// Forbidden patterns compiled at package init (zero per-request overhead)
// IMPORTANT: Pattern order matters - first match wins!
// More specific patterns should come before more general ones.
var forbiddenPatterns = []*regexp.Regexp{
	// 0. subshell with cd (cd in subshell)
	regexp.MustCompile(`\(\s*cd\s+`),
	// 1. cd command
	regexp.MustCompile(`(^|\s)cd\s+`),
	// 2. while loop
	regexp.MustCompile(`(^|\s)while\s+`),
	// 3. python one-liner (python3 -c / python -c)
	regexp.MustCompile(`(^|\s)(python3?)\s+-c\b`),
	// 4. python heredoc (python3 << / python <<)
	regexp.MustCompile(`(^|\s)(python3?)\s+<<`),
	// 5. command separator (;)
	regexp.MustCompile(`;`),
	// 6. bash test ([/[[/test)
	regexp.MustCompile(`(^test\s+|\[\[?\s*)`),
	// 7. redirection to system path
	regexp.MustCompile(`([^2&]|^)>\s*/(etc|sys|proc|boot|dev|usr|var|sbin)/`),
	// 8. recursive rm (rm -r / rm -rf)
	regexp.MustCompile(`(^|\s)rm\s+(-[a-zA-Z]*r[a-zA-Z]*)\b`),
	// 9. sed in-place edit (sed -i)
	regexp.MustCompile(`(^|\s)sed\s+(-[a-zA-Z]*i|--in-place)\b`),
	// 10. find command
	regexp.MustCompile(`(^|\s)find\s+`),
	// 11. git checkout main/master (worktree safety)
	regexp.MustCompile(`\bgit\s+(-C\s+\S+\s+)?checkout\s+(main|master)\b`),
	// 12. git switch (branch-level operation)
	regexp.MustCompile(`\bgit\s+(-C\s+\S+\s+)?switch\b`),
	// 13. git stash (contaminates shared state)
	regexp.MustCompile(`\bgit\s+(-C\s+\S+\s+)?stash\b`),
	// 14. git add (broad staging: . -A --all -u --update)
	regexp.MustCompile(`\bgit\s+(-C\s+\S+\s+)?add\s+(\.|--all|--update|-A|-u)(\s|$)`),
	// 15. git --no-verify flag (hook bypass)
	regexp.MustCompile(`\bgit\s+[^|&;]*?(--no-verify\b|-n(\s+[^0-9]|\s*$))`),
	// 16. stat (causes shell expansion permission prompt)
	regexp.MustCompile(`(^|\s)stat(\s|$)`),
	// 17. checksum (sha256sum/sha1sum/md5sum/cksum)
	regexp.MustCompile(`\b(sha256sum|sha1sum|sha512sum|md5sum|cksum)\b`),
	// 18. AGM_SKIP_TEST_GATE (test gate bypass)
	regexp.MustCompile(`AGM_SKIP_TEST_GATE`),
	// 19. sensitive dotdir access (~/.ssh, ~/.aws, ~/.gnupg)
	regexp.MustCompile(`(~|/home/\w+)/\.(ssh|aws|gnupg|gpg)/`),
	// 20. ls (standalone)
	regexp.MustCompile(`(^|\s)ls\b`),
	// 21. grep/rg (standalone)
	regexp.MustCompile(`(^|\s)(grep|rg)\b`),
	// 22. cat (standalone)
	regexp.MustCompile(`(^|\s)cat\b`),
	// 23. head/tail (standalone)
	regexp.MustCompile(`(^|\s)(head|tail)\b`),
	// 24. sed (standalone)
	regexp.MustCompile(`(^|\s)sed\b`),
	// 25. awk (standalone)
	regexp.MustCompile(`(^|\s)awk\b`),
	// 26. echo/printf (standalone)
	regexp.MustCompile(`(^|\s)(echo|printf)\b`),
	// 27. command substitution $()
	regexp.MustCompile(`\$\(`),
}

var patternNames = []string{
	"subshell with cd (cd in subshell)",
	"cd command",
	"while loop",
	"python one-liner (python3 -c / python -c)",
	"python heredoc (python3 << / python <<)",
	"command separator (;)",
	"bash test ([/[[/test)",
	"redirection to system path",
	"recursive rm (rm -r / rm -rf)",
	"sed in-place edit (sed -i)",
	"find command",
	"git checkout main/master (worktree safety)",
	"git switch (branch-level operation)",
	"git stash (contaminates shared state)",
	"git add (broad staging: . -A --all -u --update)",
	"git --no-verify flag (hook bypass)",
	"stat (causes shell expansion permission prompt)",
	"checksum (sha256sum/sha1sum/md5sum/cksum)",
	"AGM_SKIP_TEST_GATE (test gate bypass)",
	"sensitive dotdir access (~/.ssh, ~/.aws, ~/.gnupg)",
	"ls (standalone)",
	"grep/rg (standalone)",
	"cat (standalone)",
	"head/tail (standalone)",
	"sed (standalone)",
	"awk (standalone)",
	"echo/printf (standalone)",
	"command substitution $()",
}

// remediations provides actionable fix instructions for each forbidden pattern.
// Index matches forbiddenPatterns/patternNames arrays.
var remediations = []string{
	"Avoid cd entirely; use absolute paths or tool -C flags: e.g., 'git -C /path' not '(cd /path && git...)'",
	"Use absolute paths instead: e.g., 'go -C /path test' not 'cd /path && go test'",
	"Use dedicated tools or separate Bash calls instead of while loops",
	"Use the Write tool to create a .py file, then run it with Bash",
	"Use the Write tool to create a .py file, then run it with Bash",
	"Run as separate Bash calls instead of chaining with ';'",
	"Use the Grep tool for searching, not bash test/[/[[ expressions",
	"Do not redirect output to system directories. Write to project paths or /tmp/ instead.",
	"Use git rm for tracked files, or ask the user to confirm directory deletion.",
	"Use the Edit tool for in-place file modifications instead of sed -i",
	"Use the Glob tool instead of find",
	"Do not checkout main in worktrees. Use git -C for read-only operations on main.",
	"Do not checkout main in worktrees. Use git -C for read-only operations on main.",
	"Avoid git stash in shared trees; use a worktree instead",
	"Use 'git add file1.go file2.go' with specific files instead of broad staging (. -A --all)",
	"Do not skip verification. If the findings are real, fix them. If the verification has a bug, fix and redeploy it. If verification is blocking legitimate work, use AskUserQuestion to surface the issue and propose a fix for the verification — not --no-verify.",
	"Use Read tool to check file existence/contents, or TaskGet/TaskOutput for background task polling",
	"Use Read tool to read file contents for verification; for wayfinder phase checks use the wayfinder CLI",
	"Do not bypass the test gate. Fix failing tests instead. Use AskUserQuestion to escalate if blocked.",
	"Do not access sensitive credential directories. Ask the user to perform credential operations manually.",
	"Use Glob tool (for ls/find), Read tool (for head/tail/cat)",
	"Use Grep tool (for grep), Glob tool (for find)",
	"Use Read tool",
	"Use Read tool",
	"Use Read tool with offset/limit parameters, or Edit tool for modifications",
	"Use Edit tool",
	"Use Write tool to create files",
	"Use --prompt-file flag instead of command substitution in arguments",
}
