#!/usr/bin/env python3
"""create-spec skill - Generate SPEC.md from requirements and codebase analysis.

This skill provides LLM-powered SPEC.md generation with:
- Codebase analysis to understand project context
- Interactive question generation for requirements gathering
- Template-based SPEC rendering
- Quality validation loop
"""

import os
import sys
import argparse
from pathlib import Path
from typing import Optional

# Add lib directory to path
sys.path.insert(0, str(Path(__file__).parent / "lib"))

from lib.codebase_analyzer import CodebaseAnalyzer
from lib.question_generator import QuestionGenerator
from lib.spec_renderer import SPECRenderer
from lib.spec_validator import SpecValidator


def generate_skeleton_diagram(analysis, answers):
    """Generate a skeleton C4 Context diagram in D2 format.

    Args:
        analysis: CodebaseAnalysis result
        answers: QuestionAnswers with requirements

    Returns:
        D2 diagram content as string
    """
    # Extract project name from answers or analysis
    project_name = getattr(answers, 'project_name', 'System')
    if hasattr(answers, 'vision_answers') and answers.vision_answers:
        project_name = answers.vision_answers.get('name', project_name)

    # Build skeleton D2 diagram
    diagram = f"""# C4 Context Diagram - {project_name}
# Generated by create-spec skill
# Edit this file to match your actual architecture

direction: right

# External Actors
user: {{
  shape: person
  label: "User"
}}

# System Boundary
{project_name.lower().replace(' ', '_')}: {{
  label: "{project_name}"
  style: {{
    fill: "#1168bd"
    stroke: "#0b4884"
  }}
}}

# External Systems (add your integrations here)
# external_system: {{
#   label: "External System"
#   style: {{
#     fill: "#999999"
#   }}
# }}

# Relationships
user -> {project_name.lower().replace(' ', '_')}: "Uses" {{
  label: "HTTPS"
}}

# Add more relationships as needed
# {project_name.lower().replace(' ', '_')} -> external_system: "Integrates with"

"""
    return diagram


def create_spec(
    project_path: str,
    output_path: Optional[str] = None,
    interactive: bool = True,
    validate: bool = True,
    template_path: Optional[str] = None,
    generate_diagrams: bool = False,
) -> int:
    """Create SPEC.md for a project.

    Args:
        project_path: Path to project root
        output_path: Path to write SPEC.md (defaults to project_path/docs/SPEC.md)
        interactive: Enable interactive mode for questions
        validate: Validate generated SPEC
        template_path: Path to custom template
        generate_diagrams: Generate skeleton C4 Context diagram

    Returns:
        Exit code (0 for success)
    """
    # Resolve paths
    project_path = os.path.abspath(project_path)
    if not os.path.exists(project_path):
        print(f"Error: Project path does not exist: {project_path}")
        return 1

    if output_path is None:
        # Default to docs/SPEC.md
        docs_dir = os.path.join(project_path, "docs")
        os.makedirs(docs_dir, exist_ok=True)
        output_path = os.path.join(docs_dir, "SPEC.md")
    else:
        output_path = os.path.abspath(output_path)
        # Create parent directory if needed
        os.makedirs(os.path.dirname(output_path), exist_ok=True)

    print("="*60)
    print("CREATE-SPEC: LLM-Powered SPEC.md Generation")
    print("="*60)
    print()

    # Step 1: Analyze codebase
    print("Step 1/4: Analyzing codebase...")
    analyzer = CodebaseAnalyzer()
    try:
        analysis = analyzer.analyze(project_path)
        print(f"  ✓ Analyzed {analysis.file_count} files")
        print(f"  ✓ Primary language: {analysis.primary_language}")
        print(f"  ✓ Technologies: {', '.join(analysis.technologies) if analysis.technologies else 'None detected'}")
    except Exception as e:
        print(f"  ✗ Error analyzing codebase: {e}")
        return 1

    print()

    # Step 2: Generate questions
    print("Step 2/4: Generating clarifying questions...")
    generator = QuestionGenerator(interactive=interactive)
    try:
        questions = generator.generate_questions(analysis)
        total_questions = (
            len(questions.vision_questions) +
            len(questions.persona_questions) +
            len(questions.cuj_questions) +
            len(questions.metrics_questions) +
            len(questions.scope_questions) +
            len(questions.constraints_questions)
        )
        print(f"  ✓ Generated {total_questions} questions")
    except Exception as e:
        print(f"  ✗ Error generating questions: {e}")
        return 1

    print()

    # Step 3: Get answers
    print("Step 3/4: Gathering requirements...")
    try:
        if interactive:
            print("  (Please answer the following questions)\n")
            answers = generator.get_answers(questions)
        else:
            print("  ✓ Using default answers (non-interactive mode)")
            answers = generator.get_default_answers(questions, analysis)
    except Exception as e:
        print(f"  ✗ Error gathering requirements: {e}")
        return 1

    print()

    # Step 4: Render SPEC
    print("Step 4/4: Rendering SPEC.md...")
    renderer = SPECRenderer(template_path=template_path)
    try:
        spec_content = renderer.render(answers, analysis, output_path)
        print(f"  ✓ Generated SPEC.md ({len(spec_content)} bytes)")
        print(f"  ✓ Written to: {output_path}")
    except Exception as e:
        print(f"  ✗ Error rendering SPEC: {e}")
        return 1

    print()

    # Optional: Generate skeleton diagram
    if generate_diagrams:
        print("Optional: Generating skeleton C4 Context diagram...")
        try:
            diagram_content = generate_skeleton_diagram(analysis, answers)
            diagram_dir = os.path.join(project_path, "diagrams")
            os.makedirs(diagram_dir, exist_ok=True)
            diagram_path = os.path.join(diagram_dir, "c4-context.d2")

            with open(diagram_path, 'w', encoding='utf-8') as f:
                f.write(diagram_content)

            print(f"  ✓ Created skeleton diagram at: {diagram_path}")
            print(f"  ✓ Edit the diagram to match your architecture")
            print(f"  ✓ Render with: d2 {diagram_path} {diagram_path.replace('.d2', '.svg')}")
        except Exception as e:
            print(f"  ⚠ Could not generate diagram: {e}")

        print()

    # Validation loop
    if validate:
        print("Validation: Checking SPEC quality...")
        validator = SpecValidator()
        try:
            result = validator.validate(spec_content)
            print(f"  Score: {result.score:.1f}/10.0")

            if result.errors:
                print(f"  ✗ Errors: {len(result.errors)}")
                for error in result.errors:
                    print(f"    - {error}")

            if result.warnings:
                print(f"  ⚠ Warnings: {len(result.warnings)}")
                for warning in result.warnings[:3]:  # Show first 3
                    print(f"    - {warning}")

            if result.suggestions:
                print(f"  💡 Suggestions: {len(result.suggestions)}")
                for suggestion in result.suggestions[:3]:  # Show first 3
                    print(f"    - {suggestion}")

            if result.is_valid:
                print(f"\n  ✓ SPEC validation PASSED")
            else:
                print(f"\n  ✗ SPEC validation FAILED")
                print(f"  Consider improving the SPEC based on feedback above.")

        except Exception as e:
            print(f"  ⚠ Validation error: {e}")

    print()
    print("="*60)
    print("SUCCESS: SPEC.md created!")
    print("="*60)
    print(f"\nNext steps:")
    print(f"  1. Review generated SPEC at: {output_path}")
    print(f"  2. Fill in any placeholder (TBD) content")
    print(f"  3. Run /review-spec to validate quality")
    print(f"  4. Share with stakeholders for feedback")
    print()

    return 0


def main():
    """Main entry point for CLI."""
    parser = argparse.ArgumentParser(
        description="Generate SPEC.md from project requirements and codebase analysis",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Interactive mode (default)
  python create_spec.py /path/to/project

  # Non-interactive with defaults
  python create_spec.py /path/to/project --no-interactive

  # Generate with skeleton diagram
  python create_spec.py /path/to/project --generate-diagrams

  # Custom output path
  python create_spec.py /path/to/project -o /path/to/SPEC.md

  # Skip validation
  python create_spec.py /path/to/project --no-validate

  # Custom template
  python create_spec.py /path/to/project --template my-template.md
        """
    )

    parser.add_argument(
        "project_path",
        help="Path to project root directory"
    )
    parser.add_argument(
        "-o", "--output",
        dest="output_path",
        help="Output path for SPEC.md (default: <project>/docs/SPEC.md)"
    )
    parser.add_argument(
        "-i", "--interactive",
        action="store_true",
        default=True,
        help="Enable interactive mode (default)"
    )
    parser.add_argument(
        "--no-interactive",
        action="store_false",
        dest="interactive",
        help="Disable interactive mode (use defaults)"
    )
    parser.add_argument(
        "-v", "--validate",
        action="store_true",
        default=True,
        help="Validate generated SPEC (default)"
    )
    parser.add_argument(
        "--no-validate",
        action="store_false",
        dest="validate",
        help="Skip SPEC validation"
    )
    parser.add_argument(
        "-t", "--template",
        dest="template_path",
        help="Path to custom SPEC template"
    )
    parser.add_argument(
        "-d", "--generate-diagrams",
        action="store_true",
        dest="generate_diagrams",
        help="Generate skeleton C4 Context diagram in D2 format"
    )

    args = parser.parse_args()

    # Execute
    exit_code = create_spec(
        project_path=args.project_path,
        output_path=args.output_path,
        interactive=args.interactive,
        validate=args.validate,
        template_path=args.template_path,
        generate_diagrams=args.generate_diagrams,
    )

    sys.exit(exit_code)


if __name__ == "__main__":
    main()
