#!/bin/sh
set -eu
test "$#" = 8 && test "$0" = dear-agent-override-ledger-installer || exit 2
IFS= read -r mode; case "$mode" in PROBE|INSTALL) ;; *) exit 2;; esac; test "$mode" != PROBE || exit 42; test "$(/usr/bin/id -u)" = 0 || exit 2
root_gid=$1; operator_user=$2; case "$operator_user" in *[!A-Za-z0-9._-]*|"") exit 2;; esac; case "$root_gid" in *[!0-9]*|"") exit 2;; esac
helper_artifact=$3; expected_hash=$4; caller_identity=$5; companion_identity=$6; agm_artifact=$7; companion_artifact=$8
helper=/usr/local/libexec/dear-agent-override-ledger-append; identity=/usr/local/libexec/dear-agent-override-ledger-agm.identity; companion_policy=/usr/local/libexec/dear-agent-override-ledger-agm-mcp-server.identity; sudoers=/etc/sudoers.d/dear-agent-override-ledger
activation_started=0; activation_complete=0; txdir=; helper_stage=; identity_stage=; companion_stage=; sudoers_stage=
restore() { live=$1; backup=$2; existed=$3; if test "$existed" = 1; then /bin/cp -p "$backup" "$live"; else /bin/rm -f "$live"; fi; }
cleanup() { status=$?; trap - EXIT HUP INT TERM; set +e; if test "$activation_started" = 1 && test "$activation_complete" != 1; then restore "$helper" "$txdir/helper.backup" "$helper_existed"; restore "$identity" "$txdir/identity.backup" "$identity_existed"; restore "$companion_policy" "$txdir/companion.backup" "$companion_existed"; restore "$sudoers" "$txdir/sudoers.backup" "$sudoers_existed"; fi; /bin/rm -f "$helper_stage" "$identity_stage" "$companion_stage" "$sudoers_stage"; test -z "$txdir" || /bin/rm -rf "$txdir"; exit "$status"; }; trap 'cleanup' EXIT HUP INT TERM
platform=$(/usr/bin/uname -s); case "$platform" in Darwin) trusted_parent=/private/var/root; trusted_chain="/private /private/var $trusted_parent";; Linux) trusted_parent=/root; trusted_chain="/ $trusted_parent";; *) exit 2;; esac
trusted() { expected_uid=$2; test -d "$1" && test ! -L "$1" || return 1; case "$platform" in Darwin) uid=$(/usr/bin/stat -f '%u' "$1"); mode_bits=$(/usr/bin/stat -f '%Lp' "$1");; Linux) uid=$(/usr/bin/stat -c '%u' "$1"); mode_bits=$(/usr/bin/stat -c '%a' "$1");; esac; test "$uid" = "$expected_uid" && test "$((0$mode_bits & 0022))" -eq 0; }
for dir in $trusted_chain / /usr /usr/local /etc /etc/sudoers.d; do trusted "$dir" 0 || exit 2; done; if test -e /usr/local/libexec || test -L /usr/local/libexec; then trusted /usr/local/libexec 0 || exit 2; else /usr/bin/install -d -o root -g "$root_gid" -m 0755 /usr/local/libexec; trusted /usr/local/libexec 0 || exit 2; fi
trusted_dir=$trusted_parent/.dear-agent-override-ledger; /usr/bin/install -d -o root -g "$root_gid" -m 0700 "$trusted_dir"; txdir=$(/usr/bin/mktemp -d "$trusted_dir/.install.XXXXXX")
/usr/bin/install -o root -g "$root_gid" -m 0755 "$helper_artifact" "$txdir/helper"; /usr/bin/install -o root -g "$root_gid" -m 0755 "$agm_artifact" "$txdir/agm"; /usr/bin/install -o root -g "$root_gid" -m 0755 "$companion_artifact" "$txdir/agm-mcp-server"; staged_hash=$(/usr/bin/openssl dgst -sha256 -r "$txdir/helper"); staged_hash=${staged_hash%% *}; test "$staged_hash" = "$expected_hash"
case "$platform" in Darwin) agm_digest=$(/usr/bin/codesign -dvvv "$txdir/agm" 2>&1 | /usr/bin/sed -n 's/^CDHash=//p' | /usr/bin/tr '[:upper:]' '[:lower:]'); companion_digest=$(/usr/bin/codesign -dvvv "$txdir/agm-mcp-server" 2>&1 | /usr/bin/sed -n 's/^CDHash=//p' | /usr/bin/tr '[:upper:]' '[:lower:]'); test "darwin-cdhash:$agm_digest" = "$caller_identity"; test "darwin-cdhash:$companion_digest" = "$companion_identity";; Linux) agm_digest=$(/usr/bin/sha256sum "$txdir/agm"); agm_digest=${agm_digest%% *}; companion_digest=$(/usr/bin/sha256sum "$txdir/agm-mcp-server"); companion_digest=${companion_digest%% *}; test "linux-sha256:$agm_digest" = "$caller_identity"; test "linux-sha256:$companion_digest" = "$companion_identity";; esac
printf '%s\n' "$caller_identity" >"$txdir/identity"; printf '%s\n' "$companion_identity" >"$txdir/companion"; printf '%s ALL=(root) NOPASSWD: sha256:%s %s\n' "$operator_user" "$expected_hash" "$helper" >"$txdir/sudoers"; /bin/chmod 0444 "$txdir/identity" "$txdir/companion"; /bin/chmod 0440 "$txdir/sudoers"; /usr/sbin/visudo -cf "$txdir/sudoers"
helper_existed=0; identity_existed=0; companion_existed=0; sudoers_existed=0; for spec in "$helper:$txdir/helper.backup:helper_existed" "$identity:$txdir/identity.backup:identity_existed" "$companion_policy:$txdir/companion.backup:companion_existed" "$sudoers:$txdir/sudoers.backup:sudoers_existed"; do live=${spec%%:*}; rest=${spec#*:}; backup=${rest%%:*}; flag=${rest##*:}; test ! -L "$live" || exit 2; if test -e "$live"; then /bin/cp -p "$live" "$backup"; eval "$flag=1"; fi; done
helper_stage=$(/usr/bin/mktemp /usr/local/libexec/.dear-agent-override-ledger-append.XXXXXX); identity_stage=$(/usr/bin/mktemp /usr/local/libexec/.dear-agent-override-ledger-agm.identity.XXXXXX); companion_stage=$(/usr/bin/mktemp /usr/local/libexec/.dear-agent-override-ledger-agm-mcp-server.identity.XXXXXX); sudoers_stage=$(/usr/bin/mktemp /etc/sudoers.d/.dear-agent-override-ledger.XXXXXX)
/usr/bin/install -o root -g "$root_gid" -m 0755 "$txdir/helper" "$helper_stage"; /usr/bin/install -o root -g "$root_gid" -m 0444 "$txdir/identity" "$identity_stage"; /usr/bin/install -o root -g "$root_gid" -m 0444 "$txdir/companion" "$companion_stage"; /usr/bin/install -o root -g "$root_gid" -m 0440 "$txdir/sudoers" "$sudoers_stage"
activation_started=1; /bin/mv -f "$sudoers_stage" "$sudoers"; /bin/mv -f "$identity_stage" "$identity"; /bin/mv -f "$companion_stage" "$companion_policy"; /bin/mv -f "$helper_stage" "$helper"; activation_complete=1; trap - EXIT HUP INT TERM; /bin/rm -rf "$txdir"
