// Command sync-skill-projections writes the AGENTS-compatible entrypoints for
// the canonical SPEC governance skills.
package main

import (
	"bytes"
	"crypto/rand"
	"encoding/hex"
	"encoding/json"
	"errors"
	"flag"
	"fmt"
	"io"
	"io/fs"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strconv"
	"strings"
	"syscall"

	"gopkg.in/yaml.v3"
)

const generatedMarker = "<!-- Code generated by sync-skill-projections; DO NOT EDIT. -->"

var (
	skillNamePattern       = regexp.MustCompile(`^[a-z0-9]+(?:-[a-z0-9]+)*$`)
	semanticVersionPattern = regexp.MustCompile(`^(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)(?:[-+][0-9A-Za-z.-]+)?$`)
)

type skillMetadata struct {
	name        string
	description string
}

type pluginManifest struct {
	Name        string `json:"name"`
	Version     string `json:"version"`
	Description string `json:"description"`
	Author      struct {
		Name string `json:"name"`
	} `json:"author"`
	Skills []string `json:"skills"`
}

type openAIMetadata struct {
	Interface struct {
		DisplayName      string `yaml:"display_name"`
		ShortDescription string `yaml:"short_description"`
		DefaultPrompt    string `yaml:"default_prompt"`
	} `yaml:"interface"`
}

type projectionPlan struct {
	path    string
	want    []byte
	current []byte
	exists  bool
	stale   bool
}

func main() {
	os.Exit(run(os.Args[1:], os.Stderr))
}

func run(args []string, stderr io.Writer) int {
	flags := flag.NewFlagSet("sync-skill-projections", flag.ContinueOnError)
	flags.SetOutput(stderr)
	var root string
	var check bool
	flags.StringVar(&root, "root", ".", "repository root (check mode only)")
	flags.BoolVar(&check, "check", false, "fail when generated projections are stale")
	if err := flags.Parse(args); err != nil {
		return 2
	}
	if flags.NArg() != 0 {
		fmt.Fprintln(stderr, "sync-skill-projections: no positional arguments are accepted")
		return 2
	}
	rootWasSet := false
	flags.Visit(func(current *flag.Flag) {
		if current.Name == "root" {
			rootWasSet = true
		}
	})
	if !check {
		if rootWasSet {
			fmt.Fprintln(stderr, "sync-skill-projections: -root is accepted only with -check")
			return 2
		}
		if err := requireLinkedWorktreeRoot(root); err != nil {
			fmt.Fprintln(stderr, "sync-skill-projections:", err)
			return 1
		}
	}
	if err := sync(root, check); err != nil {
		fmt.Fprintln(stderr, "sync-skill-projections:", err)
		return 1
	}
	return 0
}

func requireLinkedWorktreeRoot(root string) error {
	gitFile := filepath.Join(root, ".git")
	info, err := os.Lstat(gitFile)
	if err != nil {
		return fmt.Errorf("write mode requires a linked Git worktree root: %w", err)
	}
	if !info.Mode().IsRegular() {
		return errors.New("write mode requires a linked Git worktree root with a regular .git file")
	}
	data, err := os.ReadFile(gitFile)
	if err != nil {
		return fmt.Errorf("read linked-worktree metadata: %w", err)
	}
	gitDirectory := strings.TrimSpace(strings.TrimPrefix(strings.TrimSpace(string(data)), "gitdir:"))
	if !strings.HasPrefix(strings.TrimSpace(string(data)), "gitdir:") || gitDirectory == "" {
		return errors.New("write mode requires valid linked-worktree .git metadata")
	}
	if !filepath.IsAbs(gitDirectory) {
		gitDirectory = filepath.Join(root, gitDirectory)
	}
	gitInfo, err := os.Stat(gitDirectory)
	if err != nil || !gitInfo.IsDir() {
		if err != nil {
			return fmt.Errorf("resolve linked-worktree Git directory: %w", err)
		}
		return errors.New("linked-worktree Git directory is not a directory")
	}
	return nil
}

func sync(root string, check bool) error {
	repository, err := os.OpenRoot(root)
	if err != nil {
		return fmt.Errorf("open repository root: %w", err)
	}
	defer repository.Close()

	skillNames, err := canonicalSkillNames(repository)
	if err != nil {
		return err
	}
	if err := validatePluginManifest(repository); err != nil {
		return err
	}
	plans := make([]projectionPlan, 0, len(skillNames))
	canonical := map[string]bool{}
	for _, skillName := range skillNames {
		canonical[skillName] = true
		canonicalPath := filepath.Join("spec-governance", "skills", skillName, "SKILL.md")
		metadata, err := readMetadata(repository, canonicalPath)
		if err != nil {
			return fmt.Errorf("%s: %w", filepath.ToSlash(canonicalPath), err)
		}
		if metadata.name != skillName {
			return fmt.Errorf("%s: frontmatter name %q, want %q", filepath.ToSlash(canonicalPath), metadata.name, skillName)
		}
		if err := validateOpenAIMetadata(repository, skillName); err != nil {
			return err
		}

		targetPath := filepath.Join(".agents", "skills", skillName, "SKILL.md")
		reference, err := filepath.Rel(filepath.Dir(targetPath), canonicalPath)
		if err != nil {
			return fmt.Errorf("resolve canonical reference for %s: %w", skillName, err)
		}
		want := projection(metadata, filepath.ToSlash(reference))
		plan, err := planProjection(repository, targetPath, want)
		if err != nil {
			return fmt.Errorf("%s: %w", filepath.ToSlash(targetPath), err)
		}
		plans = append(plans, plan)
	}
	obsolete, err := obsoleteGeneratedProjections(repository, canonical)
	if err != nil {
		return err
	}
	if check {
		for _, plan := range plans {
			if plan.stale {
				return fmt.Errorf("%s: generated projection is missing or stale; run make sync-spec-skill-projections", filepath.ToSlash(plan.path))
			}
		}
		if len(obsolete) > 0 {
			return fmt.Errorf("%s: obsolete generated projection; run make sync-spec-skill-projections", filepath.ToSlash(obsolete[0].path))
		}
		return nil
	}
	for _, plan := range plans {
		if plan.stale {
			if err := writeProjectionAtomic(repository, plan); err != nil {
				return fmt.Errorf("%s: %w", filepath.ToSlash(plan.path), err)
			}
		}
	}
	for _, plan := range obsolete {
		if err := removeObsoleteProjection(repository, plan); err != nil {
			return fmt.Errorf("%s: %w", filepath.ToSlash(plan.path), err)
		}
	}
	return nil
}

func validatePluginManifest(repository *os.Root) error {
	const path = "spec-governance/.claude-plugin/plugin.json"
	data, err := repository.ReadFile(path)
	if err != nil {
		return fmt.Errorf("%s: %w", path, err)
	}
	var manifest pluginManifest
	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	if err := decoder.Decode(&manifest); err != nil {
		return fmt.Errorf("%s: parse strict JSON: %w", path, err)
	}
	if err := requireDecoderEOF(decoder); err != nil {
		return fmt.Errorf("%s: %w", path, err)
	}
	if manifest.Name != "spec-governance" || !semanticVersionPattern.MatchString(manifest.Version) || strings.TrimSpace(manifest.Description) == "" || strings.TrimSpace(manifest.Author.Name) == "" {
		return fmt.Errorf("%s: manifest identity, version, description, and author are required", path)
	}
	if len(manifest.Skills) != 1 || manifest.Skills[0] != "./skills/" {
		return fmt.Errorf("%s: skills must be exactly [\"./skills/\"]", path)
	}
	return nil
}

func requireDecoderEOF(decoder *json.Decoder) error {
	var extra any
	if err := decoder.Decode(&extra); !errors.Is(err, io.EOF) {
		if err == nil {
			return errors.New("contains multiple JSON values")
		}
		return fmt.Errorf("parse trailing JSON: %w", err)
	}
	return nil
}

func validateOpenAIMetadata(repository *os.Root, skillName string) error {
	path := filepath.Join("spec-governance", "skills", skillName, "agents", "openai.yaml")
	data, err := repository.ReadFile(path)
	if err != nil {
		return fmt.Errorf("%s: %w", filepath.ToSlash(path), err)
	}
	var metadata openAIMetadata
	decoder := yaml.NewDecoder(bytes.NewReader(data))
	decoder.KnownFields(true)
	if err := decoder.Decode(&metadata); err != nil {
		return fmt.Errorf("%s: parse strict YAML: %w", filepath.ToSlash(path), err)
	}
	var extra any
	if err := decoder.Decode(&extra); !errors.Is(err, io.EOF) {
		if err == nil {
			return fmt.Errorf("%s: contains multiple YAML documents", filepath.ToSlash(path))
		}
		return fmt.Errorf("%s: parse trailing YAML: %w", filepath.ToSlash(path), err)
	}
	if strings.TrimSpace(metadata.Interface.DisplayName) == "" || strings.TrimSpace(metadata.Interface.ShortDescription) == "" || strings.TrimSpace(metadata.Interface.DefaultPrompt) == "" {
		return fmt.Errorf("%s: display_name, short_description, and default_prompt are required", filepath.ToSlash(path))
	}
	if !containsExactSkillInvocation(metadata.Interface.DefaultPrompt, skillName) {
		return fmt.Errorf("%s: default_prompt must delegate through $%s", filepath.ToSlash(path), skillName)
	}
	return nil
}

func containsExactSkillInvocation(prompt, skillName string) bool {
	pattern := `(^|[^A-Za-z0-9_$-])\$` + regexp.QuoteMeta(skillName) + `($|[^A-Za-z0-9_$-])`
	return regexp.MustCompile(pattern).MatchString(prompt)
}

func canonicalSkillNames(repository *os.Root) ([]string, error) {
	directory := filepath.Join("spec-governance", "skills")
	entries, err := fs.ReadDir(repository.FS(), directory)
	if err != nil {
		return nil, fmt.Errorf("read canonical skills: %w", err)
	}
	names := make([]string, 0)
	for _, entry := range entries {
		if !entry.IsDir() || strings.HasPrefix(entry.Name(), ".") {
			continue
		}
		if !skillNamePattern.MatchString(entry.Name()) {
			return nil, fmt.Errorf("canonical skill directory %q has an invalid name", entry.Name())
		}
		if info, statErr := repository.Stat(filepath.Join(directory, entry.Name(), "SKILL.md")); statErr != nil || !info.Mode().IsRegular() {
			if statErr != nil {
				return nil, fmt.Errorf("canonical skill %q: %w", entry.Name(), statErr)
			}
			return nil, fmt.Errorf("canonical skill %q has no regular SKILL.md", entry.Name())
		}
		names = append(names, entry.Name())
	}
	if len(names) == 0 {
		return nil, errors.New("no canonical SPEC governance skills found")
	}
	sort.Strings(names)
	return names, nil
}

func readMetadata(repository *os.Root, path string) (skillMetadata, error) {
	data, err := repository.ReadFile(path)
	if err != nil {
		return skillMetadata{}, err
	}
	return parseMetadata(data)
}

func parseMetadata(data []byte) (skillMetadata, error) {
	lines := strings.Split(strings.ReplaceAll(string(data), "\r\n", "\n"), "\n")
	if len(lines) == 0 || strings.TrimSuffix(lines[0], "\r") != "---" {
		return skillMetadata{}, errors.New("missing opening YAML frontmatter delimiter")
	}
	closing := -1
	for index, line := range lines[1:] {
		if line == "---" {
			closing = index + 1
			break
		}
	}
	if closing < 0 {
		return skillMetadata{}, errors.New("missing closing YAML frontmatter delimiter")
	}
	var raw struct {
		Name        string `yaml:"name"`
		Description string `yaml:"description"`
	}
	if err := yaml.Unmarshal([]byte(strings.Join(lines[1:closing], "\n")), &raw); err != nil {
		return skillMetadata{}, fmt.Errorf("parse YAML frontmatter: %w", err)
	}
	metadata := skillMetadata{name: strings.TrimSpace(raw.Name), description: strings.TrimSpace(raw.Description)}
	if metadata.name == "" {
		return skillMetadata{}, errors.New("frontmatter is missing name")
	}
	if metadata.description == "" {
		return skillMetadata{}, errors.New("frontmatter is missing description")
	}
	return metadata, nil
}

func projection(metadata skillMetadata, canonicalReference string) []byte {
	return []byte(fmt.Sprintf(`---
name: %s
description: %s
---

<!-- Code generated by sync-skill-projections; DO NOT EDIT. -->

# %s

This generated discovery entrypoint delegates to the canonical repository-owned
skill. It does not define a second workflow.

## Workflow

1. Resolve and read [%s](%s) completely before taking action.
2. Resolve and read the canonical skill's linked relative references when they
   are needed for the requested work.
3. Follow the canonical workflow, stop conditions, and evidence requirements
   without substituting this projection for them.

## Verify

Use the canonical skill's verification and completion criteria. Do not report
completion until its required evidence is satisfied.
`, metadata.name, yamlQuote(metadata.description), displayName(metadata.name), "the canonical skill", canonicalReference))
}

func yamlQuote(value string) string {
	return strconv.Quote(value)
}

func displayName(name string) string {
	words := strings.Split(name, "-")
	for i, word := range words {
		if word == "spec" {
			words[i] = "SPEC"
			continue
		}
		words[i] = strings.ToUpper(word[:1]) + word[1:]
	}
	return strings.Join(words, " ")
}

func planProjection(repository *os.Root, path string, want []byte) (projectionPlan, error) {
	plan := projectionPlan{path: path, want: want, stale: true}
	info, err := repository.Lstat(path)
	if err == nil && info.Mode()&os.ModeSymlink != 0 {
		return projectionPlan{}, errors.New("refusing to overwrite symlinked projection")
	}
	if err != nil && !errors.Is(err, os.ErrNotExist) {
		return projectionPlan{}, err
	}
	if err == nil && !info.Mode().IsRegular() {
		return projectionPlan{}, errors.New("projection target is not a regular file")
	}
	if errors.Is(err, os.ErrNotExist) {
		return plan, nil
	}
	current, err := repository.ReadFile(path)
	if err != nil {
		return projectionPlan{}, err
	}
	plan.current = current
	plan.exists = true
	if bytes.Equal(current, want) {
		plan.stale = false
		return plan, nil
	}
	if !bytes.Contains(current, []byte(generatedMarker)) {
		return projectionPlan{}, errors.New("refusing to overwrite a regular file without the generated marker")
	}
	return plan, nil
}

func obsoleteGeneratedProjections(repository *os.Root, canonical map[string]bool) ([]projectionPlan, error) {
	directory := filepath.Join(".agents", "skills")
	entries, err := fs.ReadDir(repository.FS(), directory)
	if errors.Is(err, os.ErrNotExist) {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	obsolete := make([]projectionPlan, 0)
	for _, entry := range entries {
		if !entry.IsDir() || canonical[entry.Name()] {
			continue
		}
		path := filepath.Join(directory, entry.Name(), "SKILL.md")
		info, statErr := repository.Lstat(path)
		if errors.Is(statErr, os.ErrNotExist) {
			continue
		}
		if statErr != nil {
			return nil, statErr
		}
		if info.Mode()&os.ModeSymlink != 0 || !info.Mode().IsRegular() {
			continue
		}
		current, readErr := repository.ReadFile(path)
		if readErr != nil {
			return nil, readErr
		}
		if isExactGeneratedProjection(entry.Name(), path, current) {
			obsolete = append(obsolete, projectionPlan{path: path, current: current, exists: true, stale: true})
		}
	}
	sort.Slice(obsolete, func(i, j int) bool { return obsolete[i].path < obsolete[j].path })
	return obsolete, nil
}

func isExactGeneratedProjection(skillName, targetPath string, current []byte) bool {
	metadata, err := parseMetadata(current)
	if err != nil || metadata.name != skillName {
		return false
	}
	canonicalPath := filepath.Join("spec-governance", "skills", skillName, "SKILL.md")
	reference, err := filepath.Rel(filepath.Dir(targetPath), canonicalPath)
	if err != nil {
		return false
	}
	return bytes.Equal(current, projection(metadata, filepath.ToSlash(reference)))
}

func writeProjectionAtomic(repository *os.Root, plan projectionPlan) (returnErr error) {
	if err := verifyUnchanged(repository, plan); err != nil {
		return err
	}
	directory := filepath.Dir(plan.path)
	if err := repository.MkdirAll(directory, 0o755); err != nil {
		return err
	}
	temporary, temporaryPath, err := createTemporaryProjection(repository, directory)
	if err != nil {
		return err
	}
	closed := false
	defer func() {
		if !closed {
			if closeErr := temporary.Close(); returnErr == nil && closeErr != nil {
				returnErr = closeErr
			}
		}
		if removeErr := repository.Remove(temporaryPath); returnErr == nil && removeErr != nil && !errors.Is(removeErr, os.ErrNotExist) {
			returnErr = removeErr
		}
	}()
	if err = temporary.Chmod(0o644); err != nil {
		return err
	}
	if _, err = temporary.Write(plan.want); err != nil {
		return err
	}
	if err = temporary.Sync(); err != nil {
		return err
	}
	if err = temporary.Close(); err != nil {
		return err
	}
	closed = true
	if err = repository.Rename(temporaryPath, plan.path); err != nil {
		return err
	}
	return nil
}

func createTemporaryProjection(repository *os.Root, directory string) (*os.File, string, error) {
	for range 32 {
		var entropy [12]byte
		if _, err := rand.Read(entropy[:]); err != nil {
			return nil, "", fmt.Errorf("generate temporary name: %w", err)
		}
		path := filepath.Join(directory, ".SKILL.md.tmp-"+hex.EncodeToString(entropy[:]))
		file, err := repository.OpenFile(path, os.O_RDWR|os.O_CREATE|os.O_EXCL, 0o600)
		if err == nil {
			return file, path, nil
		}
		if !errors.Is(err, os.ErrExist) {
			return nil, "", err
		}
	}
	return nil, "", errors.New("could not allocate a unique temporary projection")
}

func verifyUnchanged(repository *os.Root, plan projectionPlan) error {
	info, err := repository.Lstat(plan.path)
	if !plan.exists {
		if errors.Is(err, os.ErrNotExist) {
			return nil
		}
		if err != nil {
			return err
		}
		return errors.New("projection target appeared after validation")
	}
	if err != nil {
		return errors.New("projection target changed after validation")
	}
	if info.Mode()&os.ModeSymlink != 0 || !info.Mode().IsRegular() {
		return errors.New("projection target changed type after validation")
	}
	current, err := repository.ReadFile(plan.path)
	if err != nil {
		return err
	}
	if !bytes.Equal(current, plan.current) {
		return errors.New("projection target changed after validation")
	}
	return nil
}

func removeObsoleteProjection(repository *os.Root, plan projectionPlan) error {
	if err := verifyUnchanged(repository, plan); err != nil {
		return err
	}
	skillName := filepath.Base(filepath.Dir(plan.path))
	if !isExactGeneratedProjection(skillName, plan.path, plan.current) {
		return errors.New("refusing to remove a projection that is not exact generated output")
	}
	if err := repository.Remove(plan.path); err != nil {
		return err
	}
	if err := repository.Remove(filepath.Dir(plan.path)); err != nil && !errors.Is(err, os.ErrNotExist) {
		if !errors.Is(err, syscall.ENOTEMPTY) && !errors.Is(err, syscall.EEXIST) {
			return err
		}
	}
	return nil
}
