// Command sync-skill-projections writes the AGENTS-compatible entrypoints for
// the canonical SPEC governance skills.
package main

import (
	"bytes"
	"encoding/json"
	"errors"
	"flag"
	"fmt"
	"io"
	"io/fs"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"sort"
	"strconv"
	"strings"
	"syscall"

	"gopkg.in/yaml.v3"
)

const generatedMarker = "<!-- Code generated by sync-skill-projections; DO NOT EDIT. -->"

const maxGitMetadataBytes = 1024 * 1024
const maxProjectionBytes = 256 * 1024

var (
	skillNamePattern       = regexp.MustCompile(`^[a-z0-9]+(?:-[a-z0-9]+)*$`)
	semanticVersionPattern = regexp.MustCompile(`^(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)(?:[-+][0-9A-Za-z.-]+)?$`)
)

type skillMetadata struct {
	name        string
	description string
}

type pluginManifest struct {
	Name        string `json:"name"`
	Version     string `json:"version"`
	Description string `json:"description"`
	Author      struct {
		Name string `json:"name"`
	} `json:"author"`
	Skills []string `json:"skills"`
}

type openAIMetadata struct {
	Interface struct {
		DisplayName      string `yaml:"display_name"`
		ShortDescription string `yaml:"short_description"`
		DefaultPrompt    string `yaml:"default_prompt"`
	} `yaml:"interface"`
}

type projectionPlan struct {
	path    string
	want    []byte
	current []byte
	info    fs.FileInfo
	exists  bool
	stale   bool
}

type projectionMutation string

const (
	projectionInstallCreate projectionMutation = "install-create"
	projectionInstallVerify projectionMutation = "install-verify"
	projectionReplacement   projectionMutation = "replacement"
	projectionDeletion      projectionMutation = "deletion"
)

type projectionMutationHook func(projectionMutation, string) error

func main() {
	os.Exit(run(os.Args[1:], os.Stderr))
}

func run(args []string, stderr io.Writer) int {
	flags := flag.NewFlagSet("sync-skill-projections", flag.ContinueOnError)
	flags.SetOutput(stderr)
	var root string
	var check bool
	flags.StringVar(&root, "root", ".", "repository root (check mode only)")
	flags.BoolVar(&check, "check", false, "fail when generated projections are stale")
	if err := flags.Parse(args); err != nil {
		return 2
	}
	if flags.NArg() != 0 {
		fmt.Fprintln(stderr, "sync-skill-projections: no positional arguments are accepted")
		return 2
	}
	rootWasSet := false
	flags.Visit(func(current *flag.Flag) {
		if current.Name == "root" {
			rootWasSet = true
		}
	})
	if !check {
		if rootWasSet {
			fmt.Fprintln(stderr, "sync-skill-projections: -root is accepted only with -check")
			return 2
		}
		if err := requireLinkedWorktreeRoot(root); err != nil {
			fmt.Fprintln(stderr, "sync-skill-projections:", err)
			return 1
		}
	}
	if err := sync(root, check); err != nil {
		fmt.Fprintln(stderr, "sync-skill-projections:", err)
		return 1
	}
	return 0
}

func requireLinkedWorktreeRoot(root string) error {
	rootPath, err := canonicalFilesystemPath(root)
	if err != nil {
		return fmt.Errorf("resolve linked Git worktree root: %w", err)
	}
	gitDirectory, err := linkedWorktreeGitDirectory(rootPath)
	if err != nil {
		return err
	}
	if err := authenticateLinkedWorktree(rootPath, gitDirectory); err != nil {
		return err
	}
	return nil
}

func linkedWorktreeGitDirectory(rootPath string) (string, error) {
	gitFile := filepath.Join(rootPath, ".git")
	info, err := os.Lstat(gitFile)
	if err != nil {
		return "", fmt.Errorf("write mode requires a linked Git worktree root: %w", err)
	}
	if !info.Mode().IsRegular() {
		return "", errors.New("write mode requires a linked Git worktree root with a regular .git file")
	}
	data, err := os.ReadFile(gitFile)
	if err != nil {
		return "", fmt.Errorf("read linked-worktree metadata: %w", err)
	}
	gitDirectory, ok := strings.CutPrefix(strings.TrimSpace(string(data)), "gitdir:")
	gitDirectory = strings.TrimSpace(gitDirectory)
	if !ok || gitDirectory == "" {
		return "", errors.New("write mode requires valid linked-worktree .git metadata")
	}
	if !filepath.IsAbs(gitDirectory) {
		gitDirectory = filepath.Join(rootPath, gitDirectory)
	}
	gitDirectory, err = canonicalFilesystemPath(gitDirectory)
	if err != nil {
		return "", fmt.Errorf("resolve linked-worktree Git directory: %w", err)
	}
	gitInfo, err := os.Stat(gitDirectory) //nolint:gosec // G703: canonical Git metadata path; read-only existence check.
	if err != nil || !gitInfo.IsDir() {
		if err != nil {
			return "", fmt.Errorf("resolve linked-worktree Git directory: %w", err)
		}
		return "", errors.New("linked-worktree Git directory is not a directory")
	}
	if err := authenticateGitDirectoryBackpointer(gitDirectory, gitFile); err != nil {
		return "", err
	}
	return gitDirectory, nil
}

func authenticateGitDirectoryBackpointer(gitDirectory, gitFile string) error {
	backpointerPath := filepath.Join(gitDirectory, "gitdir")
	backpointerData, err := os.ReadFile(backpointerPath) //nolint:gosec // G703: authenticated canonical Git admin path; read-only metadata.
	if err != nil {
		return fmt.Errorf("read linked-worktree Git directory backpointer: %w", err)
	}
	backpointer := strings.TrimSpace(string(backpointerData))
	if backpointer == "" {
		return errors.New("linked-worktree Git directory has an empty backpointer")
	}
	if !filepath.IsAbs(backpointer) {
		backpointer = filepath.Join(gitDirectory, backpointer)
	}
	authenticatedGitFile, err := canonicalFilesystemPath(backpointer)
	if err != nil || authenticatedGitFile != gitFile {
		return errors.New("linked-worktree Git directory does not point back to this worktree's .git file")
	}
	return nil
}

func authenticateLinkedWorktree(rootPath, gitDirectory string) error {
	topLevel, err := projectionGit(rootPath, "rev-parse", "--show-toplevel")
	if err != nil {
		return fmt.Errorf("authenticate linked-worktree top level: %w", err)
	}
	authenticatedRoot, err := canonicalFilesystemPath(strings.TrimSpace(topLevel))
	if err != nil || authenticatedRoot != rootPath {
		return errors.New("write mode requires the current linked-worktree top level")
	}
	authenticatedGitDirectory, err := projectionGit(rootPath, "rev-parse", "--absolute-git-dir")
	if err != nil {
		return fmt.Errorf("authenticate linked-worktree Git directory: %w", err)
	}
	authenticatedGitDirectoryPath, err := canonicalFilesystemPath(strings.TrimSpace(authenticatedGitDirectory))
	if err != nil || authenticatedGitDirectoryPath != gitDirectory {
		return errors.New("linked-worktree .git file does not name this worktree's Git directory")
	}
	commonDirectory, err := projectionGit(rootPath, "rev-parse", "--path-format=absolute", "--git-common-dir")
	if err != nil {
		return fmt.Errorf("resolve linked-worktree common Git directory: %w", err)
	}
	commonDirectoryPath, err := canonicalFilesystemPath(strings.TrimSpace(commonDirectory))
	if err != nil || commonDirectoryPath == gitDirectory {
		return errors.New("write mode requires a linked worktree, not a primary checkout or submodule")
	}
	worktreeMetadataRoot := filepath.Join(commonDirectoryPath, "worktrees")
	relativeMetadata, err := filepath.Rel(worktreeMetadataRoot, gitDirectory)
	if err != nil || relativeMetadata == "." || relativeMetadata == ".." || strings.Contains(relativeMetadata, string(filepath.Separator)) {
		return errors.New("linked-worktree Git directory is outside the common worktree registry")
	}
	return requireRegisteredWorktree(rootPath)
}

func requireRegisteredWorktree(rootPath string) error {
	worktreeList, err := projectionGit(rootPath, "worktree", "list", "--porcelain", "-z")
	if err != nil {
		return fmt.Errorf("read linked-worktree registry: %w", err)
	}
	for field := range strings.SplitSeq(worktreeList, "\x00") {
		registered, ok := strings.CutPrefix(field, "worktree ")
		if !ok {
			continue
		}
		registeredPath, pathErr := canonicalFilesystemPath(registered)
		if pathErr == nil && registeredPath == rootPath {
			return nil
		}
	}
	return errors.New("current root is not registered as a linked Git worktree")
}

func canonicalFilesystemPath(value string) (string, error) {
	absolute, err := filepath.Abs(value)
	if err != nil {
		return "", err
	}
	return filepath.EvalSymlinks(absolute)
}

func projectionGit(root string, args ...string) (string, error) {
	full := append([]string{"--no-replace-objects", "-C", root, "-c", "core.hooksPath=" + os.DevNull}, args...)
	command := exec.Command("git", full...)
	command.Env = cleanProjectionGitEnvironment()
	stdout, err := command.StdoutPipe()
	if err != nil {
		return "", err
	}
	command.Stderr = io.Discard
	if err := command.Start(); err != nil {
		return "", err
	}
	output, readErr := io.ReadAll(io.LimitReader(stdout, maxGitMetadataBytes+1))
	if readErr != nil {
		_ = command.Process.Kill()
		_ = command.Wait()
		return "", readErr
	}
	if len(output) > maxGitMetadataBytes {
		_ = command.Process.Kill()
		_ = command.Wait()
		return "", errors.New("git metadata output exceeds the safety limit")
	}
	waitErr := command.Wait()
	if waitErr != nil {
		return "", waitErr
	}
	return string(output), nil
}

func cleanProjectionGitEnvironment() []string {
	environment := make([]string, 0, len(os.Environ())+5)
	for _, entry := range os.Environ() {
		if !strings.HasPrefix(entry, "GIT_") {
			environment = append(environment, entry)
		}
	}
	return append(environment,
		"GIT_CONFIG_GLOBAL="+os.DevNull,
		"GIT_CONFIG_SYSTEM="+os.DevNull,
		"GIT_CONFIG_NOSYSTEM=1",
		"GIT_NO_REPLACE_OBJECTS=1",
		"GIT_TERMINAL_PROMPT=0",
	)
}

func sync(root string, check bool) error {
	return syncWithMutationHook(root, check, nil)
}

func syncWithMutationHook(root string, check bool, hook projectionMutationHook) error {
	repository, err := os.OpenRoot(root)
	if err != nil {
		return fmt.Errorf("open repository root: %w", err)
	}
	defer repository.Close()

	plans, obsolete, err := planProjectionSync(repository)
	if err != nil {
		return err
	}
	if check {
		return checkProjectionSync(plans, obsolete)
	}
	return applyProjectionSync(repository, plans, obsolete, hook)
}

func planProjectionSync(repository *os.Root) ([]projectionPlan, []projectionPlan, error) {
	skillNames, err := canonicalSkillNames(repository)
	if err != nil {
		return nil, nil, err
	}
	if err := validatePluginManifest(repository); err != nil {
		return nil, nil, err
	}
	plans := make([]projectionPlan, 0, len(skillNames))
	canonical := map[string]bool{}
	for _, skillName := range skillNames {
		canonical[skillName] = true
		plan, err := planCanonicalProjection(repository, skillName)
		if err != nil {
			return nil, nil, err
		}
		plans = append(plans, plan)
	}
	obsolete, err := obsoleteGeneratedProjections(repository, canonical)
	if err != nil {
		return nil, nil, err
	}
	return plans, obsolete, nil
}

func planCanonicalProjection(repository *os.Root, skillName string) (projectionPlan, error) {
	canonicalPath := filepath.Join("spec-governance", "skills", skillName, "SKILL.md")
	metadata, err := readMetadata(repository, canonicalPath)
	if err != nil {
		return projectionPlan{}, fmt.Errorf("%s: %w", filepath.ToSlash(canonicalPath), err)
	}
	if metadata.name != skillName {
		return projectionPlan{}, fmt.Errorf("%s: frontmatter name %q, want %q", filepath.ToSlash(canonicalPath), metadata.name, skillName)
	}
	if err := validateOpenAIMetadata(repository, skillName); err != nil {
		return projectionPlan{}, err
	}

	targetPath := filepath.Join(".agents", "skills", skillName, "SKILL.md")
	reference, err := filepath.Rel(filepath.Dir(targetPath), canonicalPath)
	if err != nil {
		return projectionPlan{}, fmt.Errorf("resolve canonical reference for %s: %w", skillName, err)
	}
	want := projection(metadata, filepath.ToSlash(reference))
	if len(want) > maxProjectionBytes {
		return projectionPlan{}, fmt.Errorf("%s: deterministic projection exceeds %d bytes", filepath.ToSlash(targetPath), maxProjectionBytes)
	}
	plan, err := planProjection(repository, skillName, targetPath, want)
	if err != nil {
		return projectionPlan{}, fmt.Errorf("%s: %w", filepath.ToSlash(targetPath), err)
	}
	return plan, nil
}

func checkProjectionSync(plans, obsolete []projectionPlan) error {
	for _, plan := range plans {
		if plan.stale {
			if plan.exists {
				return fmt.Errorf("%s: generated projection is stale; inspect its path and bytes, then remove it explicitly before rerunning make sync-spec-skill-projections", filepath.ToSlash(plan.path))
			}
			return fmt.Errorf("%s: generated projection is missing or stale; run make sync-spec-skill-projections", filepath.ToSlash(plan.path))
		}
	}
	if len(obsolete) > 0 {
		return fmt.Errorf("%s: obsolete generated projection; inspect its path and bytes, then remove it explicitly before rerunning make sync-spec-skill-projections", filepath.ToSlash(obsolete[0].path))
	}
	return nil
}

func applyProjectionSync(repository *os.Root, plans, obsolete []projectionPlan, hook projectionMutationHook) error {
	// Reject every operation that would require replacing or deleting an
	// existing directory entry before publishing any missing projections. There
	// is no portable macOS/Linux compare-and-swap rename or unlink by inode.
	for _, plan := range plans {
		if plan.stale && plan.exists {
			if err := writeProjectionNoClobber(repository, plan, hook); err != nil {
				return fmt.Errorf("%s: %w", filepath.ToSlash(plan.path), err)
			}
		}
	}
	for _, plan := range obsolete {
		if err := refuseObsoleteProjectionRemoval(repository, plan, hook); err != nil {
			return fmt.Errorf("%s: %w", filepath.ToSlash(plan.path), err)
		}
	}
	for _, plan := range plans {
		if plan.stale && !plan.exists {
			if err := writeProjectionNoClobber(repository, plan, hook); err != nil {
				return fmt.Errorf("%s: %w", filepath.ToSlash(plan.path), err)
			}
		}
	}
	return nil
}

func validatePluginManifest(repository *os.Root) error {
	const path = "spec-governance/.claude-plugin/plugin.json"
	data, err := repository.ReadFile(path)
	if err != nil {
		return fmt.Errorf("%s: %w", path, err)
	}
	var manifest pluginManifest
	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	if err := decoder.Decode(&manifest); err != nil {
		return fmt.Errorf("%s: parse strict JSON: %w", path, err)
	}
	if err := requireDecoderEOF(decoder); err != nil {
		return fmt.Errorf("%s: %w", path, err)
	}
	if manifest.Name != "spec-governance" || !semanticVersionPattern.MatchString(manifest.Version) || strings.TrimSpace(manifest.Description) == "" || strings.TrimSpace(manifest.Author.Name) == "" {
		return fmt.Errorf("%s: manifest identity, version, description, and author are required", path)
	}
	if len(manifest.Skills) != 1 || manifest.Skills[0] != "./skills/" {
		return fmt.Errorf("%s: skills must be exactly [\"./skills/\"]", path)
	}
	return nil
}

func requireDecoderEOF(decoder *json.Decoder) error {
	var extra any
	if err := decoder.Decode(&extra); !errors.Is(err, io.EOF) {
		if err == nil {
			return errors.New("contains multiple JSON values")
		}
		return fmt.Errorf("parse trailing JSON: %w", err)
	}
	return nil
}

func validateOpenAIMetadata(repository *os.Root, skillName string) error {
	path := filepath.Join("spec-governance", "skills", skillName, "agents", "openai.yaml")
	data, err := repository.ReadFile(path)
	if err != nil {
		return fmt.Errorf("%s: %w", filepath.ToSlash(path), err)
	}
	var metadata openAIMetadata
	decoder := yaml.NewDecoder(bytes.NewReader(data))
	decoder.KnownFields(true)
	if err := decoder.Decode(&metadata); err != nil {
		return fmt.Errorf("%s: parse strict YAML: %w", filepath.ToSlash(path), err)
	}
	var extra any
	if err := decoder.Decode(&extra); !errors.Is(err, io.EOF) {
		if err == nil {
			return fmt.Errorf("%s: contains multiple YAML documents", filepath.ToSlash(path))
		}
		return fmt.Errorf("%s: parse trailing YAML: %w", filepath.ToSlash(path), err)
	}
	if strings.TrimSpace(metadata.Interface.DisplayName) == "" || strings.TrimSpace(metadata.Interface.ShortDescription) == "" || strings.TrimSpace(metadata.Interface.DefaultPrompt) == "" {
		return fmt.Errorf("%s: display_name, short_description, and default_prompt are required", filepath.ToSlash(path))
	}
	if !containsExactSkillInvocation(metadata.Interface.DefaultPrompt, skillName) {
		return fmt.Errorf("%s: default_prompt must delegate through $%s", filepath.ToSlash(path), skillName)
	}
	return nil
}

func containsExactSkillInvocation(prompt, skillName string) bool {
	pattern := `(^|[^A-Za-z0-9_$-])\$` + regexp.QuoteMeta(skillName) + `($|[^A-Za-z0-9_$-])`
	return regexp.MustCompile(pattern).MatchString(prompt)
}

func canonicalSkillNames(repository *os.Root) ([]string, error) {
	directory := filepath.Join("spec-governance", "skills")
	entries, err := fs.ReadDir(repository.FS(), directory)
	if err != nil {
		return nil, fmt.Errorf("read canonical skills: %w", err)
	}
	names := make([]string, 0)
	for _, entry := range entries {
		if !entry.IsDir() || strings.HasPrefix(entry.Name(), ".") {
			continue
		}
		if !skillNamePattern.MatchString(entry.Name()) {
			return nil, fmt.Errorf("canonical skill directory %q has an invalid name", entry.Name())
		}
		if info, statErr := repository.Stat(filepath.Join(directory, entry.Name(), "SKILL.md")); statErr != nil || !info.Mode().IsRegular() {
			if statErr != nil {
				return nil, fmt.Errorf("canonical skill %q: %w", entry.Name(), statErr)
			}
			return nil, fmt.Errorf("canonical skill %q has no regular SKILL.md", entry.Name())
		}
		names = append(names, entry.Name())
	}
	if len(names) == 0 {
		return nil, errors.New("no canonical SPEC governance skills found")
	}
	sort.Strings(names)
	return names, nil
}

func readMetadata(repository *os.Root, path string) (skillMetadata, error) {
	data, err := repository.ReadFile(path)
	if err != nil {
		return skillMetadata{}, err
	}
	return parseMetadata(data)
}

func parseMetadata(data []byte) (skillMetadata, error) {
	lines := strings.Split(strings.ReplaceAll(string(data), "\r\n", "\n"), "\n")
	if len(lines) == 0 || strings.TrimSuffix(lines[0], "\r") != "---" {
		return skillMetadata{}, errors.New("missing opening YAML frontmatter delimiter")
	}
	closing := -1
	for index, line := range lines[1:] {
		if line == "---" {
			closing = index + 1
			break
		}
	}
	if closing < 0 {
		return skillMetadata{}, errors.New("missing closing YAML frontmatter delimiter")
	}
	var raw struct {
		Name        string `yaml:"name"`
		Description string `yaml:"description"`
	}
	if err := yaml.Unmarshal([]byte(strings.Join(lines[1:closing], "\n")), &raw); err != nil {
		return skillMetadata{}, fmt.Errorf("parse YAML frontmatter: %w", err)
	}
	metadata := skillMetadata{name: strings.TrimSpace(raw.Name), description: strings.TrimSpace(raw.Description)}
	if metadata.name == "" {
		return skillMetadata{}, errors.New("frontmatter is missing name")
	}
	if metadata.description == "" {
		return skillMetadata{}, errors.New("frontmatter is missing description")
	}
	return metadata, nil
}

func projection(metadata skillMetadata, canonicalReference string) []byte {
	return fmt.Appendf(nil, `---
name: %s
description: %s
---

<!-- Code generated by sync-skill-projections; DO NOT EDIT. -->

# %s

This generated discovery entrypoint delegates to the canonical repository-owned
skill. It does not define a second workflow.

## Workflow

1. Resolve and read [%s](%s) completely before taking action.
2. Resolve and read the canonical skill's linked relative references when they
   are needed for the requested work.
3. Follow the canonical workflow, stop conditions, and evidence requirements
   without substituting this projection for them.

## Verify

Use the canonical skill's verification and completion criteria. Do not report
completion until its required evidence is satisfied.
`, metadata.name, yamlQuote(metadata.description), displayName(metadata.name), "the canonical skill", canonicalReference)
}

func yamlQuote(value string) string {
	return strconv.Quote(value)
}

func displayName(name string) string {
	words := strings.Split(name, "-")
	for i, word := range words {
		if word == "spec" {
			words[i] = "SPEC"
			continue
		}
		words[i] = strings.ToUpper(word[:1]) + word[1:]
	}
	return strings.Join(words, " ")
}

func planProjection(repository *os.Root, skillName, path string, want []byte) (projectionPlan, error) {
	plan := projectionPlan{path: path, want: want, stale: true}
	snapshot, err := readProjectionSnapshot(repository, path)
	if errors.Is(err, os.ErrNotExist) {
		return plan, nil
	}
	if err != nil {
		if errors.Is(err, errProjectionSymlink) {
			return projectionPlan{}, errors.New("refusing to overwrite symlinked projection")
		}
		return projectionPlan{}, err
	}
	plan.current = snapshot.data
	plan.info = snapshot.info
	plan.exists = true
	if bytes.Equal(snapshot.data, want) {
		plan.stale = false
		return plan, nil
	}
	if !isExactGeneratedProjection(skillName, path, snapshot.data) {
		return projectionPlan{}, errors.New("refusing to overwrite an existing file that is not exact generated output")
	}
	return plan, nil
}

func obsoleteGeneratedProjections(repository *os.Root, canonical map[string]bool) ([]projectionPlan, error) {
	directory := filepath.Join(".agents", "skills")
	entries, err := fs.ReadDir(repository.FS(), directory)
	if errors.Is(err, os.ErrNotExist) {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	obsolete := make([]projectionPlan, 0)
	for _, entry := range entries {
		if !entry.IsDir() || canonical[entry.Name()] {
			continue
		}
		path := filepath.Join(directory, entry.Name(), "SKILL.md")
		info, statErr := repository.Lstat(path)
		if errors.Is(statErr, os.ErrNotExist) {
			continue
		}
		if statErr != nil {
			return nil, statErr
		}
		if info.Mode()&os.ModeSymlink != 0 || !info.Mode().IsRegular() {
			continue
		}
		snapshot, readErr := readProjectionSnapshot(repository, path)
		if readErr != nil {
			return nil, readErr
		}
		if isExactGeneratedProjection(entry.Name(), path, snapshot.data) {
			obsolete = append(obsolete, projectionPlan{path: path, current: snapshot.data, info: snapshot.info, exists: true, stale: true})
		}
	}
	sort.Slice(obsolete, func(i, j int) bool { return obsolete[i].path < obsolete[j].path })
	return obsolete, nil
}

func isExactGeneratedProjection(skillName, targetPath string, current []byte) bool {
	metadata, err := parseMetadata(current)
	if err != nil || metadata.name != skillName {
		return false
	}
	canonicalPath := filepath.Join("spec-governance", "skills", skillName, "SKILL.md")
	reference, err := filepath.Rel(filepath.Dir(targetPath), canonicalPath)
	if err != nil {
		return false
	}
	return bytes.Equal(current, projection(metadata, filepath.ToSlash(reference)))
}

func writeProjectionNoClobber(repository *os.Root, plan projectionPlan, hook projectionMutationHook) error {
	if err := verifyUnchanged(repository, plan); err != nil {
		return err
	}
	if plan.exists {
		return refuseProjectionReplacement(repository, plan, hook)
	}
	return createProjectionNoClobber(repository, plan, hook)
}

func refuseProjectionReplacement(repository *os.Root, plan projectionPlan, hook projectionMutationHook) error {
	if err := runProjectionMutationHook(hook, projectionReplacement, plan.path); err != nil {
		return err
	}
	if err := verifyUnchanged(repository, plan); err != nil {
		return err
	}
	skillName := filepath.Base(filepath.Dir(plan.path))
	if !isExactGeneratedProjection(skillName, plan.path, plan.current) {
		return errors.New("refusing to replace a projection that is not exact generated output")
	}
	return errors.New("stale exact generated projection requires human inspection of its path and bytes, followed by explicit removal before regeneration")
}

func createProjectionNoClobber(repository *os.Root, plan projectionPlan, hook projectionMutationHook) error {
	directory := filepath.Dir(plan.path)
	if err := repository.MkdirAll(directory, 0o755); err != nil {
		return err
	}
	if err := runProjectionMutationHook(hook, projectionInstallCreate, plan.path); err != nil {
		return err
	}
	// Exclusive creation is the only publishing mutation. It cannot follow or
	// replace an entry that appears after planning, and the returned descriptor
	// remains bound if the path or a parent directory is subsequently swapped.
	created, err := repository.OpenFile(plan.path, os.O_WRONLY|os.O_CREATE|os.O_EXCL, 0o600)
	if errors.Is(err, fs.ErrExist) {
		return errors.New("projection target appeared before no-clobber creation")
	}
	if err != nil {
		return err
	}
	return populateCreatedProjection(repository, created, plan, hook)
}

func populateCreatedProjection(repository *os.Root, created *os.File, plan projectionPlan, hook projectionMutationHook) (returnErr error) {
	closed := false
	defer func() {
		if !closed {
			if closeErr := created.Close(); returnErr == nil && closeErr != nil {
				returnErr = closeErr
			}
		}
	}()
	written, err := created.Write(plan.want)
	if err == nil && written != len(plan.want) {
		err = io.ErrShortWrite
	}
	if err != nil {
		return fmt.Errorf("write newly created projection; target retained for explicit human inspection: %w", err)
	}
	if err = created.Chmod(0o644); err != nil {
		return fmt.Errorf("set newly created projection permissions; target retained for explicit human inspection: %w", err)
	}
	if err = created.Sync(); err != nil {
		return fmt.Errorf("sync newly created projection; target retained for explicit human inspection: %w", err)
	}
	createdInfo, err := created.Stat()
	if err != nil {
		return fmt.Errorf("inspect newly created projection; target retained for explicit human inspection: %w", err)
	}
	if err = runProjectionMutationHook(hook, projectionInstallVerify, plan.path); err != nil {
		return err
	}
	if err = created.Close(); err != nil {
		return fmt.Errorf("close newly created projection; target retained for explicit human inspection: %w", err)
	}
	closed = true
	snapshot, err := readProjectionSnapshot(repository, plan.path)
	if err != nil {
		return fmt.Errorf("newly created projection changed before final verification; no cleanup attempted: %w", err)
	}
	if !os.SameFile(createdInfo, snapshot.info) || !bytes.Equal(plan.want, snapshot.data) {
		return errors.New("newly created projection changed before final verification; no cleanup attempted")
	}
	return nil
}

func runProjectionMutationHook(hook projectionMutationHook, mutation projectionMutation, path string) error {
	if hook == nil {
		return nil
	}
	if err := hook(mutation, path); err != nil {
		return fmt.Errorf("projection %s test hook: %w", mutation, err)
	}
	return nil
}

type projectionSnapshot struct {
	data []byte
	info fs.FileInfo
}

var (
	errProjectionSymlink     = errors.New("projection target is a symlink")
	errProjectionNotRegular  = errors.New("projection target is not a regular file")
	errProjectionHardlinked  = errors.New("projection target must have exactly one hard link")
	errProjectionPermissions = errors.New("projection target permissions must be 0644")
	errProjectionTooLarge    = fmt.Errorf("projection target exceeds %d bytes", maxProjectionBytes)
	errProjectionChanged     = errors.New("projection target changed while it was read")
)

func readProjectionSnapshot(repository *os.Root, path string) (projectionSnapshot, error) {
	pathInfo, err := repository.Lstat(path)
	if err != nil {
		return projectionSnapshot{}, err
	}
	if err := validateProjectionInfo(pathInfo); err != nil {
		return projectionSnapshot{}, err
	}

	file, err := repository.Open(path)
	if err != nil {
		return projectionSnapshot{}, err
	}
	defer file.Close()
	openedInfo, err := file.Stat()
	if err != nil {
		return projectionSnapshot{}, err
	}
	if err := validateProjectionInfo(openedInfo); err != nil {
		return projectionSnapshot{}, errProjectionChanged
	}
	if !os.SameFile(pathInfo, openedInfo) {
		return projectionSnapshot{}, errProjectionChanged
	}
	data, err := io.ReadAll(io.LimitReader(file, maxProjectionBytes+1))
	if err != nil {
		return projectionSnapshot{}, err
	}
	if len(data) > maxProjectionBytes {
		return projectionSnapshot{}, errProjectionTooLarge
	}
	finalOpenedInfo, err := file.Stat()
	if err != nil {
		return projectionSnapshot{}, err
	}
	finalPathInfo, err := repository.Lstat(path)
	if err != nil {
		return projectionSnapshot{}, errProjectionChanged
	}
	if !isStableProjectionSnapshot(openedInfo, finalOpenedInfo, finalPathInfo, len(data)) {
		return projectionSnapshot{}, errProjectionChanged
	}
	return projectionSnapshot{data: data, info: finalOpenedInfo}, nil
}

func validateProjectionInfo(info fs.FileInfo) error {
	if info.Mode()&os.ModeSymlink != 0 {
		return errProjectionSymlink
	}
	if !info.Mode().IsRegular() {
		return errProjectionNotRegular
	}
	if info.Mode().Perm() != 0o644 {
		return errProjectionPermissions
	}
	if info.Size() > maxProjectionBytes {
		return errProjectionTooLarge
	}
	if !hasSingleHardLink(info) {
		return errProjectionHardlinked
	}
	return nil
}

func isStableProjectionSnapshot(opened, finalOpened, finalPath fs.FileInfo, dataLength int) bool {
	if validateProjectionInfo(finalOpened) != nil || validateProjectionInfo(finalPath) != nil {
		return false
	}
	if !os.SameFile(opened, finalOpened) || !os.SameFile(opened, finalPath) {
		return false
	}
	if opened.Size() != finalOpened.Size() {
		return false
	}
	if !opened.ModTime().Equal(finalOpened.ModTime()) {
		return false
	}
	return finalOpened.Size() == int64(dataLength)
}

func hasSingleHardLink(info fs.FileInfo) bool {
	stat, ok := info.Sys().(*syscall.Stat_t)
	return ok && stat.Nlink == 1
}

func verifyUnchanged(repository *os.Root, plan projectionPlan) error {
	if !plan.exists {
		_, err := repository.Lstat(plan.path)
		if errors.Is(err, os.ErrNotExist) {
			return nil
		}
		if err != nil {
			return err
		}
		return errors.New("projection target appeared after validation")
	}
	snapshot, err := readProjectionSnapshot(repository, plan.path)
	if err != nil {
		return fmt.Errorf("projection target changed after validation: %w", err)
	}
	if plan.info == nil || !os.SameFile(snapshot.info, plan.info) || !bytes.Equal(snapshot.data, plan.current) {
		return errors.New("projection target changed after validation")
	}
	return nil
}

func refuseObsoleteProjectionRemoval(repository *os.Root, plan projectionPlan, hook projectionMutationHook) error {
	if err := verifyUnchanged(repository, plan); err != nil {
		return err
	}
	if err := runProjectionMutationHook(hook, projectionDeletion, plan.path); err != nil {
		return err
	}
	if err := verifyUnchanged(repository, plan); err != nil {
		return err
	}
	skillName := filepath.Base(filepath.Dir(plan.path))
	if !isExactGeneratedProjection(skillName, plan.path, plan.current) {
		return errors.New("refusing to remove a projection that is not exact generated output")
	}
	return errors.New("obsolete exact generated projection requires human inspection of its path and bytes, followed by explicit removal; automatic compare-and-delete is unavailable")
}
