package main

import (
	"bytes"
	"errors"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/vbonnet/dear-agent/internal/gittest"
)

var testSkillNames = []string{"write-spec", "audit-specs"}

func TestSyncWritesAndChecksProjections(t *testing.T) {
	root := t.TempDir()
	writeCanonicalSkills(t, root)

	if err := sync(root, false); err != nil {
		t.Fatalf("sync() error = %v", err)
	}
	if err := sync(root, true); err != nil {
		t.Fatalf("sync(check) error = %v", err)
	}

	for _, name := range testSkillNames {
		path := filepath.Join(root, ".agents", "skills", name, "SKILL.md")
		data, err := os.ReadFile(path)
		if err != nil {
			t.Fatalf("read %s: %v", name, err)
		}
		text := string(data)
		for _, want := range []string{
			"<!-- Code generated by sync-skill-projections; DO NOT EDIT. -->",
			"name: " + name,
			"description: \"Use " + name + " for canonical SPEC governance.\"",
			"## Workflow",
			"## Verify",
			"../../../spec-governance/skills/" + name + "/SKILL.md",
		} {
			if !strings.Contains(text, want) {
				t.Errorf("%s does not contain %q:\n%s", name, want, text)
			}
		}
	}
}

func TestSyncCheckReportsStaleProjection(t *testing.T) {
	root := t.TempDir()
	writeCanonicalSkills(t, root)
	if err := sync(root, false); err != nil {
		t.Fatalf("sync() error = %v", err)
	}
	target := filepath.Join(root, ".agents", "skills", "write-spec", "SKILL.md")
	current, err := os.ReadFile(target)
	if err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(target, append(current, []byte("stale\n")...), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := sync(root, true); err == nil || !strings.Contains(err.Error(), "stale") {
		t.Fatalf("sync(check) error = %v, want stale projection error", err)
	}
}

func TestRunCheckMode(t *testing.T) {
	root := t.TempDir()
	writeCanonicalSkills(t, root)
	if err := sync(root, false); err != nil {
		t.Fatalf("sync() error = %v", err)
	}

	var stderr bytes.Buffer
	if code := run([]string{"--root", root, "--check"}, &stderr); code != 0 {
		t.Fatalf("run(--check) = %d, stderr = %s", code, stderr.String())
	}

	target := filepath.Join(root, ".agents", "skills", "audit-specs", "SKILL.md")
	current, err := os.ReadFile(target)
	if err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(target, append(current, []byte("stale\n")...), 0o644); err != nil {
		t.Fatal(err)
	}
	stderr.Reset()
	if code := run([]string{"--root", root, "--check"}, &stderr); code != 1 || !strings.Contains(stderr.String(), "stale") {
		t.Fatalf("run(stale --check) = %d, stderr = %q", code, stderr.String())
	}
}

func TestRunWriteRejectsExplicitRoot(t *testing.T) {
	var stderr bytes.Buffer
	if code := run([]string{"--root", t.TempDir()}, &stderr); code != 2 || !strings.Contains(stderr.String(), "only with -check") {
		t.Fatalf("run(write --root) = %d, stderr = %q", code, stderr.String())
	}
}

func TestRequireLinkedWorktreeRootRejectsOrdinaryCheckout(t *testing.T) {
	root := t.TempDir()
	if err := os.Mkdir(filepath.Join(root, ".git"), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := requireLinkedWorktreeRoot(root); err == nil || !strings.Contains(err.Error(), "regular .git file") {
		t.Fatalf("requireLinkedWorktreeRoot() error = %v, want ordinary-checkout rejection", err)
	}
}

func TestRequireLinkedWorktreeRootRejectsFabricatedMetadata(t *testing.T) {
	root := t.TempDir()
	gitDirectory := filepath.Join(t.TempDir(), "worktree-metadata")
	if err := os.Mkdir(gitDirectory, 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(root, ".git"), []byte("gitdir: "+gitDirectory+"\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := requireLinkedWorktreeRoot(root); err == nil {
		t.Fatal("requireLinkedWorktreeRoot() accepted fabricated Git metadata")
	}
}

func TestRequireLinkedWorktreeRootAcceptsRegisteredLinkedWorktree(t *testing.T) {
	repository := gittest.NewRepo(t)
	root := filepath.Join(t.TempDir(), "linked")
	gittest.Run(t, repository, "worktree", "add", "-b", "projection-test", root)
	t.Setenv("GIT_DIR", filepath.Join(t.TempDir(), "hostile.git"))
	t.Setenv("GIT_WORK_TREE", t.TempDir())
	if err := requireLinkedWorktreeRoot(root); err != nil {
		t.Fatalf("requireLinkedWorktreeRoot() error = %v", err)
	}
}

func TestRequireLinkedWorktreeRootRejectsCopiedWorktreePointer(t *testing.T) {
	repository := gittest.NewRepo(t)
	linked := filepath.Join(t.TempDir(), "linked")
	gittest.Run(t, repository, "worktree", "add", "-b", "projection-copy-test", linked)
	metadata, err := os.ReadFile(filepath.Join(linked, ".git"))
	if err != nil {
		t.Fatal(err)
	}
	fake := t.TempDir()
	if err := os.WriteFile(filepath.Join(fake, ".git"), metadata, 0o600); err != nil {
		t.Fatal(err)
	}
	if err := requireLinkedWorktreeRoot(fake); err == nil {
		t.Fatal("requireLinkedWorktreeRoot() accepted a copied pointer to another worktree")
	}
}

func TestSyncRefusesSymlinkTarget(t *testing.T) {
	root := t.TempDir()
	writeCanonicalSkills(t, root)
	target := filepath.Join(root, ".agents", "skills", "write-spec", "SKILL.md")
	if err := os.MkdirAll(filepath.Dir(target), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.Symlink(filepath.Join(root, "spec-governance", "skills", "write-spec", "SKILL.md"), target); err != nil {
		t.Skipf("symlinks unavailable: %v", err)
	}
	if err := sync(root, false); err == nil || !strings.Contains(err.Error(), "refusing to overwrite symlink") {
		t.Fatalf("sync() error = %v, want symlink refusal", err)
	}
}

func TestSyncRefusesEscapingSymlinkParent(t *testing.T) {
	root := t.TempDir()
	outside := t.TempDir()
	writeCanonicalSkills(t, root)
	if err := os.MkdirAll(filepath.Join(root, ".agents"), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.Symlink(outside, filepath.Join(root, ".agents", "skills")); err != nil {
		t.Skipf("symlinks unavailable: %v", err)
	}
	if err := sync(root, false); err == nil {
		t.Fatal("sync() succeeded through a parent symlink that escapes the repository root")
	}
	if _, err := os.Stat(filepath.Join(outside, "write-spec", "SKILL.md")); !errors.Is(err, os.ErrNotExist) {
		t.Fatalf("projection escaped repository root: %v", err)
	}
}

func TestSyncRefusesAuthoredRegularTarget(t *testing.T) {
	root := t.TempDir()
	writeCanonicalSkills(t, root)
	target := filepath.Join(root, ".agents", "skills", "write-spec", "SKILL.md")
	if err := os.MkdirAll(filepath.Dir(target), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(target, []byte("# authored\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := sync(root, false); err == nil || !strings.Contains(err.Error(), "without the generated marker") {
		t.Fatalf("sync() error = %v, want authored-file refusal", err)
	}
	data, err := os.ReadFile(target)
	if err != nil || string(data) != "# authored\n" {
		t.Fatalf("authored target changed: data=%q err=%v", data, err)
	}
}

func TestSyncValidatesAllMetadataBeforeWriting(t *testing.T) {
	root := t.TempDir()
	writeCanonicalSkills(t, root)
	if err := sync(root, false); err != nil {
		t.Fatal(err)
	}
	target := filepath.Join(root, ".agents", "skills", "audit-specs", "SKILL.md")
	before, err := os.ReadFile(target)
	if err != nil {
		t.Fatal(err)
	}
	writeSkill(t, root, "audit-specs", "---\nname: audit-specs\ndescription: changed\n---\n")
	writeSkill(t, root, "write-spec", "---\nname: write-spec\ndescription: broken\n")
	if err := sync(root, false); err == nil || !strings.Contains(err.Error(), "closing YAML") {
		t.Fatalf("sync() error = %v, want invalid second skill", err)
	}
	after, err := os.ReadFile(target)
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(before, after) {
		t.Fatal("first projection changed before all canonical metadata was validated")
	}
}

func TestSyncDiscoversNewAndObsoleteGeneratedSkills(t *testing.T) {
	root := t.TempDir()
	writeCanonicalSkills(t, root)
	writeSkill(t, root, "review-spec", "---\nname: review-spec\ndescription: Review a specification.\n---\n")
	if err := sync(root, false); err != nil {
		t.Fatal(err)
	}
	newProjection := filepath.Join(root, ".agents", "skills", "review-spec", "SKILL.md")
	if _, err := os.Stat(newProjection); err != nil {
		t.Fatalf("new canonical skill was not projected: %v", err)
	}
	if err := os.RemoveAll(filepath.Join(root, "spec-governance", "skills", "review-spec")); err != nil {
		t.Fatal(err)
	}
	if err := sync(root, true); err == nil || !strings.Contains(err.Error(), "obsolete") {
		t.Fatalf("sync(check) error = %v, want obsolete projection", err)
	}
	if err := sync(root, false); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(newProjection); !errors.Is(err, os.ErrNotExist) {
		t.Fatalf("obsolete generated projection still exists: %v", err)
	}
}

func TestSyncRetainsMarkerOnlyObsoleteProjection(t *testing.T) {
	root := t.TempDir()
	writeCanonicalSkills(t, root)
	path := filepath.Join(root, ".agents", "skills", "authored-skill", "SKILL.md")
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatal(err)
	}
	content := "---\nname: authored-skill\ndescription: Authored file.\n---\n\n" + generatedMarker + "\n\n# Authored\n"
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := sync(root, false); err != nil {
		t.Fatal(err)
	}
	got, err := os.ReadFile(path)
	if err != nil || string(got) != content {
		t.Fatalf("marker-only authored projection changed: data=%q err=%v", got, err)
	}
}

func TestReadMetadataRejectsMissingDescription(t *testing.T) {
	if _, err := parseMetadata([]byte("---\nname: write-spec\n---\n")); err == nil || !strings.Contains(err.Error(), "missing description") {
		t.Fatalf("readMetadata() error = %v, want missing description", err)
	}
}

func TestReadMetadataUsesStrictYAMLFrontmatter(t *testing.T) {
	tests := []struct {
		name    string
		content string
		wantErr string
	}{
		{name: "missing close", content: "---\nname: write-spec\ndescription: broken\n", wantErr: "closing YAML"},
		{name: "duplicate", content: "---\nname: write-spec\nname: other\ndescription: duplicate\n---\n", wantErr: "already defined"},
	}
	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			if _, err := parseMetadata([]byte(test.content)); err == nil || !strings.Contains(err.Error(), test.wantErr) {
				t.Fatalf("readMetadata() error=%v, want %q", err, test.wantErr)
			}
		})
	}
	metadata, err := parseMetadata([]byte("---\nname: write-spec\ndescription: >-\n  Write a neutral\n  specification.\n---\n"))
	if err != nil || metadata.description != "Write a neutral specification." {
		t.Fatalf("folded metadata=%#v err=%v", metadata, err)
	}
}

func TestSyncRejectsInvalidPackageMetadataBeforeWriting(t *testing.T) {
	tests := []struct {
		name    string
		mutate  func(*testing.T, string)
		wantErr string
	}{
		{
			name: "plugin skill export",
			mutate: func(t *testing.T, root string) {
				writeFile(t, root, "spec-governance/.claude-plugin/plugin.json", `{"name":"spec-governance","version":"0.1.0","description":"test","author":{"name":"test"},"skills":["./other/"]}`)
			},
			wantErr: "skills must be exactly",
		},
		{
			name: "plugin unknown field",
			mutate: func(t *testing.T, root string) {
				writeFile(t, root, "spec-governance/.claude-plugin/plugin.json", `{"name":"spec-governance","version":"0.1.0","description":"test","author":{"name":"test"},"skills":["./skills/"],"unexpected":true}`)
			},
			wantErr: "unknown field",
		},
		{
			name: "plugin invalid version",
			mutate: func(t *testing.T, root string) {
				writeFile(t, root, "spec-governance/.claude-plugin/plugin.json", `{"name":"spec-governance","version":"latest","description":"test","author":{"name":"test"},"skills":["./skills/"]}`)
			},
			wantErr: "identity, version, description, and author",
		},
		{
			name: "OpenAI prompt delegates to another skill",
			mutate: func(t *testing.T, root string) {
				writeFile(t, root, "spec-governance/skills/write-spec/agents/openai.yaml", "interface:\n  display_name: Write SPEC\n  short_description: Write a SPEC\n  default_prompt: Use $audit-specs instead.\n")
			},
			wantErr: "must delegate through $write-spec",
		},
		{
			name: "OpenAI prompt uses a longer near-prefix skill name",
			mutate: func(t *testing.T, root string) {
				writeFile(t, root, "spec-governance/skills/write-spec/agents/openai.yaml", "interface:\n  display_name: Write SPEC\n  short_description: Write a SPEC\n  default_prompt: Use $write-specification instead.\n")
			},
			wantErr: "must delegate through $write-spec",
		},
		{
			name: "OpenAI metadata unknown field",
			mutate: func(t *testing.T, root string) {
				writeFile(t, root, "spec-governance/skills/write-spec/agents/openai.yaml", "interface:\n  display_name: Write SPEC\n  short_description: Write a SPEC\n  default_prompt: Use $write-spec.\n  unexpected: true\n")
			},
			wantErr: "field unexpected not found",
		},
	}

	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			root := t.TempDir()
			writeCanonicalSkills(t, root)
			test.mutate(t, root)
			if err := sync(root, false); err == nil || !strings.Contains(err.Error(), test.wantErr) {
				t.Fatalf("sync() error = %v, want %q", err, test.wantErr)
			}
			if _, err := os.Stat(filepath.Join(root, ".agents", "skills", "write-spec", "SKILL.md")); !errors.Is(err, os.ErrNotExist) {
				t.Fatalf("projection was written before package metadata validation: %v", err)
			}
		})
	}
}

func writeCanonicalSkills(t *testing.T, root string) {
	t.Helper()
	writeFile(t, root, "spec-governance/.claude-plugin/plugin.json", `{"name":"spec-governance","version":"0.1.0","description":"Test SPEC governance plugin","author":{"name":"test"},"skills":["./skills/"]}`)
	for _, name := range testSkillNames {
		writeSkill(t, root, name, "---\nname: "+name+"\ndescription: \"Use "+name+" for canonical SPEC governance.\"\n---\n")
	}
}

func writeSkill(t *testing.T, root, name, content string) {
	t.Helper()
	writeFile(t, root, filepath.Join("spec-governance", "skills", name, "SKILL.md"), content)
	writeFile(t, root, filepath.Join("spec-governance", "skills", name, "agents", "openai.yaml"), "interface:\n  display_name: Test skill\n  short_description: Test canonical skill\n  default_prompt: Use $"+name+" for this request.\n")
}

func writeFile(t *testing.T, root, relative, content string) {
	t.Helper()
	path := filepath.Join(root, relative)
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		t.Fatal(err)
	}
}
