package main

import (
	"bytes"
	"encoding/json"
	"errors"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"testing"

	"github.com/vbonnet/dear-agent/spec-governance/internal/gittest"
	"github.com/vbonnet/dear-agent/spec-governance/skillset"
)

var testSkillNames = skillset.Names()

func TestSyncWritesAndChecksProjections(t *testing.T) {
	root := t.TempDir()
	writeCanonicalSkills(t, root)

	if err := sync(root, false); err != nil {
		t.Fatalf("sync() error = %v", err)
	}
	if err := sync(root, true); err != nil {
		t.Fatalf("sync(check) error = %v", err)
	}

	for _, name := range testSkillNames {
		path := filepath.Join(root, ".agents", "skills", name, "SKILL.md")
		data, err := os.ReadFile(path)
		if err != nil {
			t.Fatalf("read %s: %v", name, err)
		}
		text := string(data)
		for _, want := range []string{
			"<!-- Code generated by sync-skill-projections; DO NOT EDIT. -->",
			"name: " + name,
			"description: \"Use " + name + " for canonical SPEC governance.\"",
			"## Workflow",
			"## Verify",
			"../../../spec-governance/skills/" + name + "/SKILL.md",
		} {
			if !strings.Contains(text, want) {
				t.Errorf("%s does not contain %q:\n%s", name, want, text)
			}
		}
	}
}

func TestSyncCheckReportsStaleProjection(t *testing.T) {
	root := t.TempDir()
	writeCanonicalSkills(t, root)
	if err := sync(root, false); err != nil {
		t.Fatalf("sync() error = %v", err)
	}
	writeSkill(t, root, "write-spec", "---\nname: write-spec\ndescription: Updated canonical description.\n---\n")
	if err := sync(root, true); err == nil || !strings.Contains(err.Error(), "stale") {
		t.Fatalf("sync(check) error = %v, want stale projection error", err)
	}
}

func TestSyncRequiresExplicitRemovalForStaleProjection(t *testing.T) {
	root := t.TempDir()
	writeCanonicalSkills(t, root)
	if err := sync(root, false); err != nil {
		t.Fatalf("sync() error = %v", err)
	}
	target := filepath.Join(root, ".agents", "skills", "write-spec", "SKILL.md")
	before, err := os.ReadFile(target)
	if err != nil {
		t.Fatal(err)
	}
	writeSkill(t, root, "write-spec", "---\nname: write-spec\ndescription: Updated canonical description.\n---\n")
	if err := sync(root, false); err == nil || !strings.Contains(err.Error(), "human inspection") {
		t.Fatalf("sync() error = %v, want explicit-removal refusal", err)
	}
	unchanged, err := os.ReadFile(target)
	if err != nil || !bytes.Equal(unchanged, before) {
		t.Fatalf("stale generated target changed: data=%q err=%v", unchanged, err)
	}
	if err := os.Remove(target); err != nil {
		t.Fatal(err)
	}
	if err := sync(root, false); err != nil {
		t.Fatalf("sync() after explicit removal error = %v", err)
	}
	after, err := os.ReadFile(target)
	if err != nil || bytes.Equal(after, before) {
		t.Fatalf("projection was not regenerated after explicit removal: data=%q err=%v", after, err)
	}
}

func TestRunCheckMode(t *testing.T) {
	root := t.TempDir()
	writeCanonicalSkills(t, root)
	if err := sync(root, false); err != nil {
		t.Fatalf("sync() error = %v", err)
	}

	var stderr bytes.Buffer
	if code := run([]string{"--root", root, "--check"}, &stderr); code != 0 {
		t.Fatalf("run(--check) = %d, stderr = %s", code, stderr.String())
	}

	writeSkill(t, root, "audit-specs", "---\nname: audit-specs\ndescription: Updated canonical description.\n---\n")
	stderr.Reset()
	if code := run([]string{"--root", root, "--check"}, &stderr); code != 1 || !strings.Contains(stderr.String(), "stale") {
		t.Fatalf("run(stale --check) = %d, stderr = %q", code, stderr.String())
	}
}

func TestRunWriteRejectsExplicitRoot(t *testing.T) {
	var stderr bytes.Buffer
	if code := run([]string{"--root", t.TempDir()}, &stderr); code != 2 || !strings.Contains(stderr.String(), "only with -check") {
		t.Fatalf("run(write --root) = %d, stderr = %q", code, stderr.String())
	}
}

func TestRequireLinkedWorktreeRootRejectsOrdinaryCheckout(t *testing.T) {
	root := t.TempDir()
	if err := os.Mkdir(filepath.Join(root, ".git"), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := requireLinkedWorktreeRoot(root); err == nil || !strings.Contains(err.Error(), "regular .git file") {
		t.Fatalf("requireLinkedWorktreeRoot() error = %v, want ordinary-checkout rejection", err)
	}
}

func TestRequireLinkedWorktreeRootRejectsFabricatedMetadata(t *testing.T) {
	root := t.TempDir()
	gitDirectory := filepath.Join(t.TempDir(), "worktree-metadata")
	if err := os.Mkdir(gitDirectory, 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(root, ".git"), []byte("gitdir: "+gitDirectory+"\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := requireLinkedWorktreeRoot(root); err == nil {
		t.Fatal("requireLinkedWorktreeRoot() accepted fabricated Git metadata")
	}
}

func TestRequireLinkedWorktreeRootAcceptsRegisteredLinkedWorktree(t *testing.T) {
	repository := gittest.NewRepo(t)
	root := filepath.Join(t.TempDir(), "linked")
	gittest.Run(t, repository, "worktree", "add", "-b", "projection-test", root)
	t.Setenv("GIT_DIR", filepath.Join(t.TempDir(), "hostile.git"))
	t.Setenv("GIT_WORK_TREE", t.TempDir())
	if err := requireLinkedWorktreeRoot(root); err != nil {
		t.Fatalf("requireLinkedWorktreeRoot() error = %v", err)
	}
}

func TestRequireLinkedWorktreeRootRejectsCopiedWorktreePointer(t *testing.T) {
	repository := gittest.NewRepo(t)
	linked := filepath.Join(t.TempDir(), "linked")
	gittest.Run(t, repository, "worktree", "add", "-b", "projection-copy-test", linked)
	metadata, err := os.ReadFile(filepath.Join(linked, ".git"))
	if err != nil {
		t.Fatal(err)
	}
	fake := t.TempDir()
	if err := os.WriteFile(filepath.Join(fake, ".git"), metadata, 0o600); err != nil {
		t.Fatal(err)
	}
	if err := requireLinkedWorktreeRoot(fake); err == nil {
		t.Fatal("requireLinkedWorktreeRoot() accepted a copied pointer to another worktree")
	}
}

func TestRequireLinkedWorktreeRootRejectsOtherRegisteredWorktreePointer(t *testing.T) {
	repository := gittest.NewRepo(t)
	worktrees := t.TempDir()
	source := filepath.Join(worktrees, "source")
	target := filepath.Join(worktrees, "target")
	gittest.Run(t, repository, "worktree", "add", "-b", "projection-source-test", source)
	gittest.Run(t, repository, "worktree", "add", "-b", "projection-target-test", target)

	metadata, err := os.ReadFile(filepath.Join(source, ".git"))
	if err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(target, ".git"), metadata, 0o600); err != nil {
		t.Fatal(err)
	}
	if err := requireLinkedWorktreeRoot(target); err == nil || !strings.Contains(err.Error(), "does not point back") {
		t.Fatalf("requireLinkedWorktreeRoot() error = %v, want mismatched registered-worktree rejection", err)
	}
}

func TestRequireLinkedWorktreeRootRejectsOtherPointerAtRecreatedRegisteredPath(t *testing.T) {
	repository := gittest.NewRepo(t)
	worktrees := t.TempDir()
	source := filepath.Join(worktrees, "source")
	target := filepath.Join(worktrees, "target")
	gittest.Run(t, repository, "worktree", "add", "-b", "projection-recreate-source-test", source)
	gittest.Run(t, repository, "worktree", "add", "-b", "projection-recreate-target-test", target)

	metadata, err := os.ReadFile(filepath.Join(source, ".git"))
	if err != nil {
		t.Fatal(err)
	}
	if err := os.RemoveAll(target); err != nil {
		t.Fatal(err)
	}
	if err := os.MkdirAll(target, 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(target, ".git"), metadata, 0o600); err != nil {
		t.Fatal(err)
	}
	if err := requireLinkedWorktreeRoot(target); err == nil || !strings.Contains(err.Error(), "does not point back") {
		t.Fatalf("requireLinkedWorktreeRoot() error = %v, want recreated registered-path rejection", err)
	}
}

func TestSyncRefusesSymlinkTarget(t *testing.T) {
	root := t.TempDir()
	writeCanonicalSkills(t, root)
	target := filepath.Join(root, ".agents", "skills", "write-spec", "SKILL.md")
	if err := os.MkdirAll(filepath.Dir(target), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.Symlink(filepath.Join(root, "spec-governance", "skills", "write-spec", "SKILL.md"), target); err != nil {
		t.Skipf("symlinks unavailable: %v", err)
	}
	if err := sync(root, false); err == nil || !strings.Contains(err.Error(), "refusing to overwrite symlink") {
		t.Fatalf("sync() error = %v, want symlink refusal", err)
	}
}

func TestSyncRefusesEscapingSymlinkParent(t *testing.T) {
	root := t.TempDir()
	outside := t.TempDir()
	writeCanonicalSkills(t, root)
	if err := os.MkdirAll(filepath.Join(root, ".agents"), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.Symlink(outside, filepath.Join(root, ".agents", "skills")); err != nil {
		t.Skipf("symlinks unavailable: %v", err)
	}
	if err := sync(root, false); err == nil {
		t.Fatal("sync() succeeded through a parent symlink that escapes the repository root")
	}
	if _, err := os.Stat(filepath.Join(outside, "write-spec", "SKILL.md")); !errors.Is(err, os.ErrNotExist) {
		t.Fatalf("projection escaped repository root: %v", err)
	}
}

func TestSyncRefusesAuthoredRegularTarget(t *testing.T) {
	root := t.TempDir()
	writeCanonicalSkills(t, root)
	target := filepath.Join(root, ".agents", "skills", "write-spec", "SKILL.md")
	if err := os.MkdirAll(filepath.Dir(target), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(target, []byte("# authored\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := sync(root, false); err == nil || !strings.Contains(err.Error(), "not exact generated output") {
		t.Fatalf("sync() error = %v, want authored-file refusal", err)
	}
	data, err := os.ReadFile(target)
	if err != nil || string(data) != "# authored\n" {
		t.Fatalf("authored target changed: data=%q err=%v", data, err)
	}
}

func TestSyncRefusesMarkerBearingAuthoredCanonicalTarget(t *testing.T) {
	root := t.TempDir()
	writeCanonicalSkills(t, root)
	target := filepath.Join(root, ".agents", "skills", "write-spec", "SKILL.md")
	if err := os.MkdirAll(filepath.Dir(target), 0o755); err != nil {
		t.Fatal(err)
	}
	authored := []byte("---\nname: write-spec\ndescription: Authored local workflow.\n---\n\n" + generatedMarker + "\n\n# Authored local instructions\n")
	if err := os.WriteFile(target, authored, 0o644); err != nil {
		t.Fatal(err)
	}
	if err := sync(root, false); err == nil || !strings.Contains(err.Error(), "not exact generated output") {
		t.Fatalf("sync() error = %v, want marker-bearing authored-file refusal", err)
	}
	got, err := os.ReadFile(target)
	if err != nil || !bytes.Equal(got, authored) {
		t.Fatalf("marker-bearing authored target changed: data=%q err=%v", got, err)
	}
}

func TestSyncValidatesAllMetadataBeforeWriting(t *testing.T) {
	root := t.TempDir()
	writeCanonicalSkills(t, root)
	if err := sync(root, false); err != nil {
		t.Fatal(err)
	}
	target := filepath.Join(root, ".agents", "skills", "audit-specs", "SKILL.md")
	before, err := os.ReadFile(target)
	if err != nil {
		t.Fatal(err)
	}
	writeSkill(t, root, "audit-specs", "---\nname: audit-specs\ndescription: changed\n---\n")
	writeSkill(t, root, "write-spec", "---\nname: write-spec\ndescription: broken\n")
	if err := sync(root, false); err == nil || !strings.Contains(err.Error(), "closing YAML") {
		t.Fatalf("sync() error = %v, want invalid second skill", err)
	}
	after, err := os.ReadFile(target)
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(before, after) {
		t.Fatal("first projection changed before all canonical metadata was validated")
	}
}

func TestSyncRejectsFullyDeclaredAdditionalCanonicalSkill(t *testing.T) {
	root := t.TempDir()
	writeCanonicalSkills(t, root)
	writeSkill(t, root, "review-spec", "---\nname: review-spec\ndescription: Review a specification.\n---\n")
	fullyDeclared := append(testSkillNames, "review-spec")
	writeExpandedClaudeMarketplace(t, root, fullyDeclared)
	writeNativePluginManifest(t, root, fullyDeclared)
	if err := sync(root, false); err == nil || !strings.Contains(err.Error(), "want fixed set [audit-specs write-spec]") {
		t.Fatalf("sync() error = %v, want fixed-set rejection", err)
	}
	if _, err := os.Stat(filepath.Join(root, ".agents")); !errors.Is(err, os.ErrNotExist) {
		t.Fatalf("additional canonical skill was projected before rejection: %v", err)
	}
}

func TestSyncFindsObsoleteGeneratedProjection(t *testing.T) {
	root := t.TempDir()
	writeCanonicalSkills(t, root)
	if err := sync(root, false); err != nil {
		t.Fatal(err)
	}
	targetPath := writeObsoleteProjection(t, root, "review-spec")
	newProjection := filepath.Join(root, targetPath)
	if err := sync(root, true); err == nil || !strings.Contains(err.Error(), "obsolete") {
		t.Fatalf("sync(check) error = %v, want obsolete projection", err)
	}
	before, err := os.ReadFile(newProjection)
	if err != nil {
		t.Fatal(err)
	}
	if err := sync(root, false); err == nil || !strings.Contains(err.Error(), "explicit removal") {
		t.Fatalf("sync() error = %v, want explicit-removal refusal", err)
	}
	after, err := os.ReadFile(newProjection)
	if err != nil || !bytes.Equal(after, before) {
		t.Fatalf("obsolete generated projection changed: data=%q err=%v", after, err)
	}
	if err := os.Remove(newProjection); err != nil {
		t.Fatal(err)
	}
	if err := os.Remove(filepath.Dir(newProjection)); err != nil {
		t.Fatal(err)
	}
	if err := sync(root, false); err != nil {
		t.Fatalf("sync() after explicit removal error = %v", err)
	}
}

func TestSyncRetainsMarkerOnlyObsoleteProjection(t *testing.T) {
	root := t.TempDir()
	writeCanonicalSkills(t, root)
	path := filepath.Join(root, ".agents", "skills", "authored-skill", "SKILL.md")
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatal(err)
	}
	content := "---\nname: authored-skill\ndescription: Authored file.\n---\n\n" + generatedMarker + "\n\n# Authored\n"
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := sync(root, false); err != nil {
		t.Fatal(err)
	}
	got, err := os.ReadFile(path)
	if err != nil || string(got) != content {
		t.Fatalf("marker-only authored projection changed: data=%q err=%v", got, err)
	}
}

func TestSyncNoClobberWhenTargetAppearsBeforeCreate(t *testing.T) {
	root := t.TempDir()
	writeCanonicalSkills(t, root)
	targetPath := filepath.Join(".agents", "skills", "audit-specs", "SKILL.md")
	authored := []byte("# arrived after validation\n")
	invoked := false
	hook := func(mutation projectionMutation, path string) error {
		if mutation != projectionInstallCreate || path != targetPath {
			return nil
		}
		invoked = true
		return os.WriteFile(filepath.Join(root, path), authored, 0o644)
	}
	if err := syncWithMutationHook(root, false, hook); err == nil || !strings.Contains(err.Error(), "appeared before no-clobber creation") {
		t.Fatalf("sync() error = %v, want no-clobber refusal", err)
	}
	if !invoked {
		t.Fatal("install-create hook was not invoked")
	}
	got, err := os.ReadFile(filepath.Join(root, targetPath))
	if err != nil || !bytes.Equal(got, authored) {
		t.Fatalf("late-created authored target changed: data=%q err=%v", got, err)
	}
}

func TestSyncFailsClosedWhenNewTargetIsSwapped(t *testing.T) {
	for _, swapKind := range projectionSwapKinds {
		t.Run(swapKind, func(t *testing.T) {
			root := t.TempDir()
			writeCanonicalSkills(t, root)
			targetPath := filepath.Join(".agents", "skills", "audit-specs", "SKILL.md")
			target := filepath.Join(root, targetPath)
			backup := target + ".generated"
			source := filepath.Join(root, "authored-source")
			authored := []byte("authored swap content\n")
			if err := os.WriteFile(source, authored, 0o644); err != nil {
				t.Fatal(err)
			}
			invoked := false
			hook := func(mutation projectionMutation, path string) error {
				if mutation != projectionInstallVerify || path != targetPath {
					return nil
				}
				invoked = true
				return swapProjectionTarget(swapKind, target, backup, source)
			}
			if err := syncWithMutationHook(root, false, hook); err == nil || !strings.Contains(err.Error(), "changed before final verification") {
				t.Fatalf("sync() error = %v, want changed-target refusal", err)
			}
			if !invoked {
				t.Fatal("install-verify hook was not invoked")
			}
			assertProjectionSwap(t, swapKind, target, source, authored)
			generated, err := os.ReadFile(backup)
			if err != nil || !bytes.Contains(generated, []byte(generatedMarker)) {
				t.Fatalf("descriptor-bound generated file changed: data=%q err=%v", generated, err)
			}
		})
	}
}

func TestSyncFailsClosedWhenNewTargetParentIsSwapped(t *testing.T) {
	root := t.TempDir()
	writeCanonicalSkills(t, root)
	targetPath := filepath.Join(".agents", "skills", "audit-specs", "SKILL.md")
	targetDirectory := filepath.Dir(filepath.Join(root, targetPath))
	backupDirectory := targetDirectory + ".generated"
	authored := []byte("authored parent-swap content\n")
	invoked := false
	hook := func(mutation projectionMutation, path string) error {
		if mutation != projectionInstallVerify || path != targetPath {
			return nil
		}
		invoked = true
		if err := os.Rename(targetDirectory, backupDirectory); err != nil {
			return err
		}
		if err := os.Mkdir(targetDirectory, 0o755); err != nil {
			return err
		}
		return os.WriteFile(filepath.Join(root, targetPath), authored, 0o644)
	}
	if err := syncWithMutationHook(root, false, hook); err == nil || !strings.Contains(err.Error(), "changed before final verification") {
		t.Fatalf("sync() error = %v, want parent-swap refusal", err)
	}
	if !invoked {
		t.Fatal("install-verify hook was not invoked")
	}
	got, err := os.ReadFile(filepath.Join(root, targetPath))
	if err != nil || !bytes.Equal(got, authored) {
		t.Fatalf("parent-swapped authored target changed: data=%q err=%v", got, err)
	}
	generated, err := os.ReadFile(filepath.Join(backupDirectory, "SKILL.md"))
	if err != nil || !bytes.Contains(generated, []byte(generatedMarker)) {
		t.Fatalf("descriptor-bound generated target changed: data=%q err=%v", generated, err)
	}
}

func TestSyncFailsClosedWhenExistingTargetIsSwapped(t *testing.T) {
	for _, operation := range []string{"replacement", "deletion"} {
		for _, swapKind := range projectionSwapKinds {
			t.Run(operation+"/"+swapKind, func(t *testing.T) {
				root := t.TempDir()
				writeCanonicalSkills(t, root)
				var targetPath string
				var wantedMutation projectionMutation
				if operation == "replacement" {
					if err := sync(root, false); err != nil {
						t.Fatal(err)
					}
					targetPath = filepath.Join(".agents", "skills", "write-spec", "SKILL.md")
					wantedMutation = projectionReplacement
					writeSkill(t, root, "write-spec", "---\nname: write-spec\ndescription: Updated canonical description.\n---\n")
				} else {
					targetPath = writeObsoleteProjection(t, root, "review-spec")
					wantedMutation = projectionDeletion
				}

				target := filepath.Join(root, targetPath)
				backup := target + ".generated"
				original, err := os.ReadFile(target)
				if err != nil {
					t.Fatal(err)
				}
				source := filepath.Join(root, "authored-source")
				authored := []byte("authored swap content\n")
				if err := os.WriteFile(source, authored, 0o644); err != nil {
					t.Fatal(err)
				}
				invoked := false
				hook := func(mutation projectionMutation, path string) error {
					if mutation != wantedMutation || path != targetPath {
						return nil
					}
					invoked = true
					return swapProjectionTarget(swapKind, target, backup, source)
				}
				if err := syncWithMutationHook(root, false, hook); err == nil || !strings.Contains(err.Error(), "changed after validation") {
					t.Fatalf("sync() error = %v, want changed-target refusal", err)
				}
				if !invoked {
					t.Fatalf("%s hook was not invoked", operation)
				}
				assertProjectionSwap(t, swapKind, target, source, authored)
				generated, err := os.ReadFile(backup)
				if err != nil || !bytes.Equal(generated, original) {
					t.Fatalf("validated generated target changed: data=%q err=%v", generated, err)
				}
			})
		}
	}
}

func TestSyncFailsClosedWhenExistingTargetBytesChange(t *testing.T) {
	for _, operation := range []string{"replacement", "deletion"} {
		t.Run(operation, func(t *testing.T) {
			root := t.TempDir()
			writeCanonicalSkills(t, root)
			var targetPath string
			var wantedMutation projectionMutation
			if operation == "replacement" {
				if err := sync(root, false); err != nil {
					t.Fatal(err)
				}
				targetPath = filepath.Join(".agents", "skills", "write-spec", "SKILL.md")
				wantedMutation = projectionReplacement
				writeSkill(t, root, "write-spec", "---\nname: write-spec\ndescription: Updated canonical description.\n---\n")
			} else {
				targetPath = writeObsoleteProjection(t, root, "review-spec")
				wantedMutation = projectionDeletion
			}

			authored := []byte("in-place authored bytes\n")
			invoked := false
			hook := func(mutation projectionMutation, path string) error {
				if mutation != wantedMutation || path != targetPath {
					return nil
				}
				invoked = true
				return os.WriteFile(filepath.Join(root, path), authored, 0o644)
			}
			if err := syncWithMutationHook(root, false, hook); err == nil || !strings.Contains(err.Error(), "changed after validation") {
				t.Fatalf("sync() error = %v, want changed-bytes refusal", err)
			}
			if !invoked {
				t.Fatalf("%s hook was not invoked", operation)
			}
			got, err := os.ReadFile(filepath.Join(root, targetPath))
			if err != nil || !bytes.Equal(got, authored) {
				t.Fatalf("in-place authored bytes changed: data=%q err=%v", got, err)
			}
		})
	}
}

func TestSyncRejectsHardLinkedProjection(t *testing.T) {
	root := t.TempDir()
	writeCanonicalSkills(t, root)
	if err := sync(root, false); err != nil {
		t.Fatal(err)
	}
	target := filepath.Join(root, ".agents", "skills", "write-spec", "SKILL.md")
	alias := filepath.Join(root, "projection-alias")
	if err := os.Link(target, alias); err != nil {
		t.Fatal(err)
	}
	if err := sync(root, false); err == nil || !strings.Contains(err.Error(), "exactly one hard link") {
		t.Fatalf("sync() error = %v, want hard-link refusal", err)
	}
	targetInfo, targetErr := os.Stat(target)
	aliasInfo, aliasErr := os.Stat(alias)
	if targetErr != nil || aliasErr != nil || !os.SameFile(targetInfo, aliasInfo) {
		t.Fatalf("hard-linked target changed: targetErr=%v aliasErr=%v", targetErr, aliasErr)
	}
}

func TestSyncRejectsUnexpectedProjectionPermissions(t *testing.T) {
	root := t.TempDir()
	writeCanonicalSkills(t, root)
	if err := sync(root, false); err != nil {
		t.Fatal(err)
	}
	target := filepath.Join(root, ".agents", "skills", "write-spec", "SKILL.md")
	if err := os.Chmod(target, 0o600); err != nil {
		t.Fatal(err)
	}
	if err := sync(root, true); err == nil || !strings.Contains(err.Error(), "permissions must be 0644") {
		t.Fatalf("sync(check) error = %v, want permission refusal", err)
	}
}

func TestSyncRejectsOversizedProjectionTarget(t *testing.T) {
	root := t.TempDir()
	writeCanonicalSkills(t, root)
	target := filepath.Join(root, ".agents", "skills", "write-spec", "SKILL.md")
	if err := os.MkdirAll(filepath.Dir(target), 0o755); err != nil {
		t.Fatal(err)
	}
	oversized := bytes.Repeat([]byte("x"), maxProjectionBytes+1)
	if err := os.WriteFile(target, oversized, 0o644); err != nil {
		t.Fatal(err)
	}
	if err := sync(root, false); err == nil || !strings.Contains(err.Error(), "exceeds 262144 bytes") {
		t.Fatalf("sync() error = %v, want bounded-read refusal", err)
	}
	info, err := os.Stat(target)
	if err != nil {
		t.Fatalf("inspect oversized target: %v", err)
	}
	if info.Size() != int64(len(oversized)) {
		t.Fatalf("oversized target changed: size=%d", info.Size())
	}
}

func TestReadMetadataRejectsMissingDescription(t *testing.T) {
	if _, err := parseMetadata([]byte("---\nname: write-spec\n---\n")); err == nil || !strings.Contains(err.Error(), "missing description") {
		t.Fatalf("readMetadata() error = %v, want missing description", err)
	}
}

func TestReadMetadataUsesStrictYAMLFrontmatter(t *testing.T) {
	tests := []struct {
		name    string
		content string
		wantErr string
	}{
		{name: "missing close", content: "---\nname: write-spec\ndescription: broken\n", wantErr: "closing YAML"},
		{name: "duplicate", content: "---\nname: write-spec\nname: other\ndescription: duplicate\n---\n", wantErr: "already defined"},
	}
	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			if _, err := parseMetadata([]byte(test.content)); err == nil || !strings.Contains(err.Error(), test.wantErr) {
				t.Fatalf("readMetadata() error=%v, want %q", err, test.wantErr)
			}
		})
	}
	metadata, err := parseMetadata([]byte("---\nname: write-spec\ndescription: >-\n  Write a neutral\n  specification.\n---\n"))
	if err != nil || metadata.description != "Write a neutral specification." {
		t.Fatalf("folded metadata=%#v err=%v", metadata, err)
	}
}

func TestSyncRejectsInvalidPackageMetadataBeforeWriting(t *testing.T) {
	tests := []struct {
		name    string
		mutate  func(*testing.T, string)
		wantErr string
	}{
		{
			name: "marketplace bypasses native manifest",
			mutate: func(t *testing.T, root string) {
				writeFile(t, root, ".claude-plugin/marketplace.json", `{"name":"dear-agent","description":"test","owner":{"name":"test","email":"test@example.com"},"plugins":[{"name":"spec-governance","source":"./spec-governance","version":"0.1.0","description":"test","skills":["./other/"]}]}`)
			},
			wantErr: "delegate its complete native surface",
		},
		{
			name: "marketplace unknown field",
			mutate: func(t *testing.T, root string) {
				writeFile(t, root, ".claude-plugin/marketplace.json", `{"name":"dear-agent","description":"test","owner":{"name":"test","email":"test@example.com"},"plugins":[{"name":"spec-governance","source":"./spec-governance","version":"0.1.0","description":"test","unexpected":true}]}`)
			},
			wantErr: "unknown field",
		},
		{
			name: "marketplace invalid version",
			mutate: func(t *testing.T, root string) {
				writeFile(t, root, ".claude-plugin/marketplace.json", `{"name":"dear-agent","description":"test","owner":{"name":"test","email":"test@example.com"},"plugins":[{"name":"spec-governance","source":"./spec-governance","version":"latest","description":"test"}]}`)
			},
			wantErr: "identity, version, and description",
		},
		{
			name: "marketplace root source",
			mutate: func(t *testing.T, root string) {
				writeFile(t, root, ".claude-plugin/marketplace.json", `{"name":"dear-agent","description":"test","owner":{"name":"test","email":"test@example.com"},"plugins":[{"name":"spec-governance","source":".","version":"0.1.0","description":"test"}]}`)
			},
			wantErr: "isolated native plugin root",
		},
		{
			name: "marketplace strict mode",
			mutate: func(t *testing.T, root string) {
				writeFile(t, root, ".claude-plugin/marketplace.json", `{"name":"dear-agent","description":"test","owner":{"name":"test","email":"test@example.com"},"plugins":[{"name":"spec-governance","source":"./spec-governance","version":"0.1.0","description":"test","strict":true}]}`)
			},
			wantErr: "delegate its complete native surface",
		},
		{
			name: "native manifest exposes extra surface",
			mutate: func(t *testing.T, root string) {
				writeFile(t, root, "spec-governance/.claude-plugin/plugin.json", `{"name":"spec-governance","version":"0.1.0","description":"test","author":{"name":"test"},"skills":["./skills/audit-specs","./skills/write-spec"],"hooks":{}}`)
			},
			wantErr: "unknown field",
		},
		{
			name: "native plugin root exposes MCP",
			mutate: func(t *testing.T, root string) {
				writeFile(t, root, "spec-governance/.mcp.json", `{}`)
			},
			wantErr: "must not expose",
		},
		{
			name: "OpenAI prompt delegates to another skill",
			mutate: func(t *testing.T, root string) {
				writeFile(t, root, "spec-governance/skills/write-spec/agents/openai.yaml", "interface:\n  display_name: Write SPEC\n  short_description: Write a SPEC\n  default_prompt: Use $audit-specs instead.\n")
			},
			wantErr: "must delegate through $write-spec",
		},
		{
			name: "OpenAI prompt uses a longer near-prefix skill name",
			mutate: func(t *testing.T, root string) {
				writeFile(t, root, "spec-governance/skills/write-spec/agents/openai.yaml", "interface:\n  display_name: Write SPEC\n  short_description: Write a SPEC\n  default_prompt: Use $write-specification instead.\n")
			},
			wantErr: "must delegate through $write-spec",
		},
		{
			name: "OpenAI metadata unknown field",
			mutate: func(t *testing.T, root string) {
				writeFile(t, root, "spec-governance/skills/write-spec/agents/openai.yaml", "interface:\n  display_name: Write SPEC\n  short_description: Write a SPEC\n  default_prompt: Use $write-spec.\n  unexpected: true\n")
			},
			wantErr: "field unexpected not found",
		},
	}

	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			root := t.TempDir()
			writeCanonicalSkills(t, root)
			test.mutate(t, root)
			if err := sync(root, false); err == nil || !strings.Contains(err.Error(), test.wantErr) {
				t.Fatalf("sync() error = %v, want %q", err, test.wantErr)
			}
			if _, err := os.Stat(filepath.Join(root, ".agents", "skills", "write-spec", "SKILL.md")); !errors.Is(err, os.ErrNotExist) {
				t.Fatalf("projection was written before package metadata validation: %v", err)
			}
		})
	}
}

func writeCanonicalSkills(t *testing.T, root string) {
	t.Helper()
	for _, name := range testSkillNames {
		writeSkill(t, root, name, "---\nname: "+name+"\ndescription: \"Use "+name+" for canonical SPEC governance.\"\n---\n")
	}
	writeClaudeMarketplace(t, root)
	writeNativePluginManifest(t, root, testSkillNames)
}

func writeClaudeMarketplace(t *testing.T, root string) {
	t.Helper()
	data, err := json.Marshal(map[string]any{
		"name":        "dear-agent",
		"description": "test",
		"owner":       map[string]string{"name": "test", "email": "test@example.com"},
		"plugins": []any{map[string]any{
			"name": "spec-governance", "source": "./spec-governance", "version": "0.1.0",
			"description": "Test SPEC governance plugin",
		}},
	})
	if err != nil {
		t.Fatal(err)
	}
	writeFile(t, root, ".claude-plugin/marketplace.json", string(data))
}

func writeExpandedClaudeMarketplace(t *testing.T, root string, names []string) {
	t.Helper()
	names = append([]string(nil), names...)
	sort.Strings(names)
	skills := make([]string, len(names))
	for index, name := range names {
		skills[index] = "./skills/" + name
	}
	data, err := json.Marshal(map[string]any{
		"name":        "dear-agent",
		"description": "test",
		"owner":       map[string]string{"name": "test", "email": "test@example.com"},
		"plugins": []any{map[string]any{
			"name": "spec-governance", "source": "./spec-governance", "version": "0.1.0",
			"description": "Test expanded SPEC governance plugin", "strict": false, "skills": skills,
		}},
	})
	if err != nil {
		t.Fatal(err)
	}
	writeFile(t, root, ".claude-plugin/marketplace.json", string(data))
}

func writeNativePluginManifest(t *testing.T, root string, names []string) {
	t.Helper()
	names = append([]string(nil), names...)
	sort.Strings(names)
	skills := make([]string, len(names))
	for index, name := range names {
		skills[index] = "./skills/" + name
	}
	data, err := json.Marshal(map[string]any{
		"name": "spec-governance", "version": "0.1.0", "description": "Test SPEC governance plugin",
		"author": map[string]string{"name": "test"}, "skills": skills,
	})
	if err != nil {
		t.Fatal(err)
	}
	writeFile(t, root, "spec-governance/.claude-plugin/plugin.json", string(data))
}

func writeSkill(t *testing.T, root, name, content string) {
	t.Helper()
	writeFile(t, root, filepath.Join("spec-governance", "skills", name, "SKILL.md"), content)
	writeFile(t, root, filepath.Join("spec-governance", "skills", name, "agents", "openai.yaml"), "interface:\n  display_name: Test skill\n  short_description: Test canonical skill\n  default_prompt: Use $"+name+" for this request.\n")
}

func writeObsoleteProjection(t *testing.T, root, name string) string {
	t.Helper()
	targetPath := filepath.Join(".agents", "skills", name, "SKILL.md")
	canonicalPath := filepath.Join("spec-governance", "skills", name, "SKILL.md")
	reference, err := filepath.Rel(filepath.Dir(targetPath), canonicalPath)
	if err != nil {
		t.Fatal(err)
	}
	content := projection(skillMetadata{name: name, description: "Obsolete generated skill."}, filepath.ToSlash(reference))
	writeFile(t, root, targetPath, string(content))
	return targetPath
}

func writeFile(t *testing.T, root, relative, content string) {
	t.Helper()
	path := filepath.Join(root, relative)
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		t.Fatal(err)
	}
}

var projectionSwapKinds = []string{"regular", "symlink", "directory", "hardlink"}

func swapProjectionTarget(kind, target, backup, source string) error {
	if err := os.Rename(target, backup); err != nil {
		return err
	}
	switch kind {
	case "regular":
		return os.WriteFile(target, []byte("authored swap content\n"), 0o644)
	case "symlink":
		return os.Symlink(source, target)
	case "directory":
		return os.Mkdir(target, 0o755)
	case "hardlink":
		return os.Link(source, target)
	default:
		return errors.New("unknown projection swap kind")
	}
}

func assertProjectionSwap(t *testing.T, kind, target, source string, authored []byte) {
	t.Helper()
	info, err := os.Lstat(target)
	if err != nil {
		t.Fatalf("inspect swapped target: %v", err)
	}
	switch kind {
	case "regular":
		got, readErr := os.ReadFile(target)
		if readErr != nil || !bytes.Equal(got, authored) {
			t.Fatalf("regular swap changed: data=%q err=%v", got, readErr)
		}
	case "symlink":
		got, readErr := os.Readlink(target)
		if info.Mode()&os.ModeSymlink == 0 || readErr != nil || got != source {
			t.Fatalf("symlink swap changed: mode=%v target=%q err=%v", info.Mode(), got, readErr)
		}
	case "directory":
		if !info.IsDir() {
			t.Fatalf("directory swap changed: mode=%v", info.Mode())
		}
	case "hardlink":
		sourceInfo, statErr := os.Stat(source)
		if statErr != nil || !os.SameFile(info, sourceInfo) {
			t.Fatalf("hard-link swap changed: sourceErr=%v", statErr)
		}
		got, readErr := os.ReadFile(target)
		if readErr != nil || !bytes.Equal(got, authored) {
			t.Fatalf("hard-link swap bytes changed: data=%q err=%v", got, readErr)
		}
	default:
		t.Fatalf("unknown projection swap kind %q", kind)
	}
}
