/**
 * GitHub PR comment formatter for multi-persona-review reviews
 */

import type { ReviewResult, Severity } from '../types.js';
import {
  aggregateCacheMetrics,
  calculateCacheHitRate,
  calculateCostSavings,
} from '../cost-sink.js';

/**
 * Severity emoji mapping for GitHub
 */
const SEVERITY_EMOJI: Record<Severity, string> = {
  critical: '🔴',
  high: '🟠',
  medium: '🟡',
  low: '🔵',
  info: 'ℹ️',
};

/**
 * Formats review result as GitHub PR comment (markdown)
 */
export function formatReviewResultGitHub(result: ReviewResult): string {
  const lines: string[] = [];

  // Header
  lines.push('## 🔍 Multi-Persona Review Code Review');
  lines.push('');

  // Summary
  const { summary, cost } = result;
  lines.push('### Summary');
  lines.push('');
  lines.push(`- **Files reviewed**: ${summary.filesReviewed}`);
  lines.push(`- **Total findings**: ${summary.totalFindings}`);

  const severityCounts: string[] = [];
  if (summary.findingsBySeverity.critical > 0) {
    severityCounts.push(`🔴 ${summary.findingsBySeverity.critical} critical`);
  }
  if (summary.findingsBySeverity.high > 0) {
    severityCounts.push(`🟠 ${summary.findingsBySeverity.high} high`);
  }
  if (summary.findingsBySeverity.medium > 0) {
    severityCounts.push(`🟡 ${summary.findingsBySeverity.medium} medium`);
  }
  if (summary.findingsBySeverity.low > 0) {
    severityCounts.push(`🔵 ${summary.findingsBySeverity.low} low`);
  }
  if (summary.findingsBySeverity.info > 0) {
    severityCounts.push(`ℹ️ ${summary.findingsBySeverity.info} info`);
  }

  if (severityCounts.length > 0) {
    lines.push(`- **By severity**: ${severityCounts.join(', ')}`);
  }

  if (summary.deduplicated) {
    lines.push(`- **Duplicates removed**: ${summary.deduplicated}`);
  }

  lines.push(`- **Cost**: $${cost.totalCost.toFixed(4)} (${cost.totalTokens.toLocaleString()} tokens)`);

  // Add cache performance if available
  const cacheMetrics = aggregateCacheMetrics(cost);
  if (cacheMetrics.cacheReadTokens > 0 || cacheMetrics.cacheCreationTokens > 0) {
    const hitRate = calculateCacheHitRate(cacheMetrics);
    const costSavings = calculateCostSavings(cacheMetrics);
    lines.push(`- **Cache Performance**: ${hitRate.toFixed(1)}% hit rate, $${costSavings.savings.toFixed(4)} saved (${costSavings.savingsPercent.toFixed(1)}% reduction)`);
  }

  lines.push('');

  // No findings
  if (result.findings.length === 0) {
    lines.push('### ✅ No issues found!');
    lines.push('');
    return lines.join('\n');
  }

  // Findings by severity
  const severities: Severity[] = ['critical', 'high', 'medium', 'low', 'info'];

  for (const severity of severities) {
    const severityFindings = result.findings.filter(f => f.severity === severity);

    if (severityFindings.length === 0) continue;

    lines.push(`### ${SEVERITY_EMOJI[severity]} ${severity.toUpperCase()} (${severityFindings.length})`);
    lines.push('');

    for (const finding of severityFindings) {
      lines.push('<details>');
      lines.push(`<summary><b>${finding.file}${finding.line ? `:${finding.line}` : ''}</b> - ${finding.title}</summary>`);
      lines.push('');
      lines.push(finding.description);

      if (finding.categories && finding.categories.length > 0) {
        lines.push('');
        lines.push(`**Categories**: ${finding.categories.join(', ')}`);
      }

      if (finding.confidence) {
        lines.push('');
        lines.push(`**Confidence**: ${Math.round(finding.confidence * 100)}%`);
      }

      if (finding.decision) {
        lines.push('');
        const decisionEmoji = finding.decision === 'GO' ? '✅' : '🚫';
        lines.push(`**Decision**: ${decisionEmoji} ${finding.decision}`);
      }

      if (finding.alternatives && finding.alternatives.length > 0) {
        lines.push('');
        lines.push(`**Alternatives**:`);
        for (const alt of finding.alternatives) {
          lines.push(`- ${alt}`);
        }
      }

      if (finding.outOfScope) {
        lines.push('');
        lines.push(`⚠️ **Out of Scope** - This finding is outside the persona's expertise`);
      }

      lines.push('');
      lines.push(`**Personas**: ${finding.personas.join(', ')}`);
      lines.push('');
      lines.push('</details>');
      lines.push('');
    }
  }

  // Footer
  lines.push('---');
  lines.push('');
  lines.push('*Generated by [Multi-Persona Review](https://github.com/wayfinder/multi-persona-review)*');

  return lines.join('\n');
}
