package main

import (
	"testing"
)

// TestSend_QueueMode_NoESC_VerifyTmux is a REGRESSION TEST for Bug 2:
// ESC sent unconditionally in queue mode, interrupting operations
//
// Bug History (2026-03-14):
// - Issue: `agm session send` (without --interrupt) sent ESC, interrupting operations
// - Root Cause: SendPromptLiteral unconditionally sent ESC before all prompts
// - Fix: Made ESC conditional on shouldInterrupt parameter
//
// This test documents the expected behavior for queue mode (no ESC sent).
func TestSend_QueueMode_NoESC_VerifyTmux(t *testing.T) {
	t.Log("Queue Mode Verification (No ESC):")
	t.Log("")
	t.Log("TEST SCENARIO:")
	t.Log("1. Create AGM session")
	t.Log("2. Send message WITHOUT --interrupt flag")
	t.Log("3. Verify message queued (not sent directly)")
	t.Log("4. Verify NO ESC keypress in tmux capture")
	t.Log("")
	t.Log("EXPECTED BEHAVIOR:")
	t.Log("- Command output: '⏳ Message queued for delivery'")
	t.Log("- Tmux capture: No ESC escape sequences")
	t.Log("- Session state: Not interrupted")
	t.Log("")
	t.Log("VERIFICATION METHODS:")
	t.Log("1. Check command output for queue confirmation")
	t.Log("2. Capture tmux pane content with: tmux capture-pane -t {session} -p")
	t.Log("3. Search for ESC sequences (should not find any)")
	t.Log("4. Verify session state unchanged (still in thinking/ready state)")
	t.Log("")
	t.Log("MANUAL TEST PROCEDURE:")
	t.Log("```bash")
	t.Log("# Create test session")
	t.Log("agm session new test-queue-mode")
	t.Log("")
	t.Log("# Send message in queue mode (default)")
	t.Log("agm session send test-queue-mode --prompt='Test message'")
	t.Log("# Expected output: '⏳ Message queued for delivery when session becomes READY'")
	t.Log("")
	t.Log("# Verify no ESC in tmux")
	t.Log("tmux capture-pane -t test-queue-mode -p | grep -i escape")
	t.Log("# Expected: No results (no escape sequences)")
	t.Log("")
	t.Log("# Check session state")
	t.Log("agm session status test-queue-mode")
	t.Log("# Expected: Session still in original state (not interrupted)")
	t.Log("```")
	t.Log("")
	t.Log("CODE PATH VERIFICATION:")
	t.Log("- send.go:211 checks sessionSendInterrupt flag")
	t.Log("- If false (queue mode): calls queueMessage()")
	t.Log("- queueMessage() does NOT call sendDirectly()")
	t.Log("- Message queued in ~/.agm/queues/ for daemon delivery")
	t.Log("- No tmux interaction → No ESC sent")
}

// TestSend_InterruptMode_SendsESC documents emergency-interrupt mode behavior
func TestSend_InterruptMode_SendsESC(t *testing.T) {
	t.Log("Emergency Interrupt Mode Verification (ESC Sent):")
	t.Log("")
	t.Log("TEST SCENARIO:")
	t.Log("1. Create AGM session")
	t.Log("2. Send message WITH --emergency-interrupt flag")
	t.Log("3. Verify message sent directly (not queued)")
	t.Log("4. Verify ESC keypress in tmux capture")
	t.Log("")
	t.Log("EXPECTED BEHAVIOR:")
	t.Log("- Command output: '✓ Sent to {session}'")
	t.Log("- Tmux capture: ESC escape sequence present")
	t.Log("- Session state: Interrupted (thinking stopped)")
	t.Log("")
	t.Log("MANUAL TEST PROCEDURE:")
	t.Log("```bash")
	t.Log("# Create test session")
	t.Log("agm session new test-interrupt-mode")
	t.Log("")
	t.Log("# Start thinking state (send long prompt)")
	t.Log("agm session send test-interrupt-mode --prompt='Write a 1000 word essay'")
	t.Log("")
	t.Log("# Emergency interrupt with new message")
	t.Log("agm send msg test-interrupt-mode --emergency-interrupt --prompt='Stop, new task'")
	t.Log("# Expected output: '✓ Sent to test-interrupt-mode'")
	t.Log("")
	t.Log("# Verify ESC was sent")
	t.Log("# (ESC interrupts thinking state, observable in session behavior)")
	t.Log("")
	t.Log("# Deprecated --interrupt flag still works but prints warning")
	t.Log("agm send msg test-interrupt-mode --interrupt --prompt='Stop, new task'")
	t.Log("# Expected: Warning: --interrupt is deprecated, use --emergency-interrupt instead")
	t.Log("```")
	t.Log("")
	t.Log("CODE PATH VERIFICATION:")
	t.Log("- send_msg.go checks sessionSendEmergencyInterrupt || sessionSendInterrupt")
	t.Log("- If true: calls sendDirectly()")
	t.Log("- If --interrupt used: prints deprecation warning to stderr")
	t.Log("- sendDirectly() → sendViaTmux(..., shouldInterrupt=true)")
	t.Log("- sendViaTmux() → SendMultiLinePromptSafe(..., true)")
	t.Log("- SendMultiLinePromptSafe() → SendPromptLiteral(..., true)")
	t.Log("- SendPromptLiteral() checks shouldInterrupt=true → sends ESC")
}

// TestSend_StateDetectionFailure_ReturnsError documents error handling
func TestSend_StateDetectionFailure_ReturnsError(t *testing.T) {
	t.Log("State Detection Failure Handling (Bug Fix History):")
	t.Log("")
	t.Log("ORIGINAL BEHAVIOR (Buggy, pre 2026-03-14):")
	t.Log("- State detection fails")
	t.Log("- Falls back to sendDirectly() silently")
	t.Log("- Sends ESC and interrupts (unintended)")
	t.Log("❌ Problem: Silent fallback causes interruption")
	t.Log("")
	t.Log("INTERMEDIATE BEHAVIOR (2026-03-14 to 2026-03-28):")
	t.Log("- Session not in DB → returns error suggesting --force/--interrupt")
	t.Log("- This taught orchestrators to always use --interrupt")
	t.Log("❌ Problem: Error message caused --interrupt abuse")
	t.Log("")
	t.Log("CURRENT BEHAVIOR (Fixed 2026-03-28):")
	t.Log("- Session not in DB but exists in tmux → tmux-only state detection")
	t.Log("- DetectState(sessionName) works without DB (uses tmux only)")
	t.Log("- Routes normally via state-based decision matrix (queue/send)")
	t.Log("- Only errors if tmux state detection itself fails")
	t.Log("✓ Result: No --interrupt needed for sandbox/unregistered sessions")
	t.Log("")
	t.Log("ERROR CASES:")
	t.Log("1. Session not in DB, exists in tmux")
	t.Log("   - Falls through to DetectState(sessionName) via tmux")
	t.Log("   - Routes normally based on detected state")
	t.Log("")
	t.Log("2. State detection failed (tmux error)")
	t.Log("   - Error: 'failed to detect session state for <session>: <error>'")
	t.Log("")
	t.Log("MANUAL VERIFICATION:")
	t.Log("```bash")
	t.Log("# Create tmux session without DB registration")
	t.Log("tmux new-session -d -s test-sandbox")
	t.Log("")
	t.Log("# Send message without --interrupt (should work now)")
	t.Log("agm send msg test-sandbox --prompt='Test message'")
	t.Log("# Expected: '⏳ Queued' or '✓ Sent' — NOT an error")
	t.Log("```")
}

// TestSend_QueueFallbackPaths documents all queue vs interrupt paths
func TestSend_QueueFallbackPaths(t *testing.T) {
	t.Log("Queue vs Interrupt Decision Matrix:")
	t.Log("")
	t.Log("DECISION FLOW:")
	t.Log("")
	t.Log("1. Check --emergency-interrupt flag (or deprecated --interrupt)")
	t.Log("   If TRUE → sendDirectly() with shouldInterrupt=true")
	t.Log("   If FALSE → Continue to state detection")
	t.Log("")
	t.Log("1b. Check --force flag")
	t.Log("   If TRUE → sendDirectly() (bypass DB and safety)")
	t.Log("   If FALSE → Continue")
	t.Log("")
	t.Log("2. Resolve session manifest (DB lookup)")
	t.Log("   If NOT FOUND → Fall through to tmux-only DetectState()")
	t.Log("   If FOUND → Use cached state or detect if stale")
	t.Log("")
	t.Log("3. State-based routing (same for DB and tmux-only paths)")
	t.Log("   - DONE → sendDirectly(shouldInterrupt=false) — no ESC, preserves plan mode")
	t.Log("   - WORKING/USER_PROMPT → queueMessage() (no ESC)")
	t.Log("   - COMPACTING → Error (retry message)")
	t.Log("   - OFFLINE → Error")
	t.Log("   - UNKNOWN → sendDirectly(shouldInterrupt=false) with warning")
	t.Log("")
	t.Log("KEY FIX (2026-03-28):")
	t.Log("Old: DB lookup failure → error suggesting --interrupt/--force")
	t.Log("New: DB lookup failure → tmux-only state detection → normal routing")
	t.Log("")
	t.Log("RESULT:")
	t.Log("- Sandbox/unregistered sessions work without --interrupt")
	t.Log("- No silent interruptions")
	t.Log("- --emergency-interrupt reserved for true emergencies")
}

// TestSend_DoneState_NoESC_PreservesPlanMode is a REGRESSION TEST for plan mode exit bug.
//
// Bug History (2026-04-01):
//   - Issue: Sessions in plan mode had plan mode unexpectedly exited when receiving messages
//   - Root Cause: sendDirectly() hardcoded shouldInterrupt=true, sending ESC to sessions
//     at the prompt. ESC exits plan mode in Claude Code.
//   - Fix: sendDirectly() now accepts shouldInterrupt parameter. DONE-state sends use
//     shouldInterrupt=false. Only --force sends use shouldInterrupt=true.
//
// This test documents that DONE-state sends must NOT send ESC.
func TestSend_DoneState_NoESC_PreservesPlanMode(t *testing.T) {
	t.Log("Plan Mode Preservation - DONE State (No ESC):")
	t.Log("")
	t.Log("BUG SCENARIO:")
	t.Log("1. Session is in plan mode, at the prompt (state=DONE)")
	t.Log("2. agm send msg delivers a message")
	t.Log("3. sendDirectly() was called with shouldInterrupt=true (HARDCODED)")
	t.Log("4. ESC keystroke sent via tmux before message text")
	t.Log("5. ESC exits plan mode in Claude Code")
	t.Log("6. Session unexpectedly leaves plan mode")
	t.Log("")
	t.Log("FIX:")
	t.Log("- sendDirectly() now accepts shouldInterrupt parameter")
	t.Log("- DONE state: sendDirectly(..., shouldInterrupt=false) — no ESC")
	t.Log("- --force:     sendDirectly(..., shouldInterrupt=true)  — ESC sent")
	t.Log("- Unknown:     sendDirectly(..., shouldInterrupt=false) — safe default")
	t.Log("")
	t.Log("CODE PATH VERIFICATION:")
	t.Log("- send_msg.go DONE case → sendDirectly(..., false)")
	t.Log("- sendDirectly(..., false) → sendViaTmux(..., false)")
	t.Log("- sendViaTmux → SendMultiLinePromptSafe(..., false)")
	t.Log("- SendMultiLinePromptSafe → SendPromptLiteral(..., false)")
	t.Log("- SendPromptLiteral checks shouldInterrupt=false → skips ESC")
	t.Log("- Message text sent directly, plan mode preserved")
	t.Log("")
	t.Log("MANUAL TEST PROCEDURE:")
	t.Log("```bash")
	t.Log("# Create session in plan mode")
	t.Log("agm session new test-plan-mode")
	t.Log("agm send mode plan test-plan-mode")
	t.Log("")
	t.Log("# Wait for session to reach prompt (DONE state)")
	t.Log("agm session status test-plan-mode  # Should show DONE")
	t.Log("")
	t.Log("# Send message (should NOT exit plan mode)")
	t.Log("agm send msg test-plan-mode --prompt 'Analyze this code'")
	t.Log("")
	t.Log("# Verify plan mode preserved")
	t.Log("agm session status test-plan-mode  # Should still show plan mode")
	t.Log("tmux capture-pane -t test-plan-mode -p | grep -i plan")
	t.Log("# Expected: Plan mode indicator still visible")
	t.Log("```")
	t.Log("")
	t.Log("CONTRAST WITH --force:")
	t.Log("```bash")
	t.Log("# --force DOES send ESC (intentional)")
	t.Log("agm send msg test-plan-mode --force --prompt 'Emergency'")
	t.Log("# This may exit plan mode — user explicitly chose --force")
	t.Log("```")
}
