package main

import (
	"fmt"
	"strings"

	"github.com/spf13/cobra"
	"github.com/vbonnet/dear-agent/agm/internal/ops"
	"github.com/vbonnet/dear-agent/agm/internal/ui"
)

var sessionSummaryCmd = &cobra.Command{
	Use:   "summary <name>",
	Short: "Generate a post-session summary report",
	Long: `Generate a structured retrospective summary for a session.

Collects commits, file changes, duration, trust events, and cost data
into a single report. Useful for post-session review and orchestrator
reporting.

Output formats:
  • json (default) — Machine-readable JSON
  • markdown (-o markdown) — Human-readable markdown

Examples:
  agm session summary my-session                # JSON output
  agm session summary my-session -o markdown    # Markdown output
  agm session summary my-session -o json --fields commits,files  # Field mask`,
	Args: cobra.ExactArgs(1),
	RunE: runSessionSummary,
}

func init() {
	sessionCmd.AddCommand(sessionSummaryCmd)
}

func runSessionSummary(cmd *cobra.Command, args []string) error {
	sessionName := args[0]

	opCtx, cleanup, err := newOpContextWithStorage()
	if err != nil {
		return fmt.Errorf("failed to connect to storage: %w", err)
	}
	defer cleanup()

	result, opErr := ops.GenerateSessionSummary(opCtx, &ops.GenerateSessionSummaryRequest{
		SessionName: sessionName,
	})
	if opErr != nil {
		return handleError(opErr)
	}

	if outputFormat == "markdown" {
		printSummaryMarkdown(result)
		return nil
	}

	return printResult(result, func() {
		printSummaryText(result)
	})
}

func printSummaryText(r *ops.GenerateSessionSummaryResult) {
	fmt.Printf("Session: %s\n", ui.Bold(r.SessionName))
	fmt.Printf("Branch:  %s\n", r.Branch)
	fmt.Printf("Commits: %d\n\n", r.CommitCount)

	if len(r.Commits) > 0 {
		fmt.Println("Commits:")
		for _, c := range r.Commits {
			fmt.Printf("  %s %s (%s)\n", c.Hash, c.Subject, c.Author)
		}
		fmt.Println()
	}

	fmt.Printf("Files: %d changed, +%d/-%d lines\n",
		r.Files.TotalFiles, r.Files.LinesAdded, r.Files.LinesRemoved)

	if r.Duration != nil {
		fmt.Printf("Duration: %s (%s to %s)\n",
			r.Duration.Elapsed, r.Duration.StartTime, r.Duration.EndTime)
	}

	if r.Trust != nil {
		fmt.Printf("Trust: score=%d events=%d\n", r.Trust.Score, r.Trust.TotalEvents)
	}

	if r.Cost != nil {
		fmt.Printf("Cost: $%.2f", r.Cost.EstimatedCost)
		if r.Cost.TokensIn > 0 || r.Cost.TokensOut > 0 {
			fmt.Printf(" (in=%d out=%d)", r.Cost.TokensIn, r.Cost.TokensOut)
		}
		fmt.Println()
	}
}

func printSummaryMarkdown(r *ops.GenerateSessionSummaryResult) {
	fmt.Printf("# Session Summary: %s\n\n", r.SessionName)
	fmt.Printf("**Branch:** `%s`\n\n", r.Branch)

	// Commits
	fmt.Printf("## Commits (%d)\n\n", r.CommitCount)
	if len(r.Commits) > 0 {
		fmt.Println("| Hash | Subject | Author | Time |")
		fmt.Println("|------|---------|--------|------|")
		for _, c := range r.Commits {
			fmt.Printf("| `%s` | %s | %s | %s |\n",
				c.Hash, c.Subject, c.Author, c.Timestamp)
		}
	} else {
		fmt.Println("No commits on this branch.")
	}
	fmt.Println()

	// Files
	fmt.Println("## Files Changed")
	fmt.Println()
	fmt.Printf("- **Files:** %d\n", r.Files.TotalFiles)
	fmt.Printf("- **Lines added:** %d\n", r.Files.LinesAdded)
	fmt.Printf("- **Lines removed:** %d\n", r.Files.LinesRemoved)
	fmt.Println()

	// Duration
	if r.Duration != nil {
		fmt.Println("## Duration")
		fmt.Println()
		fmt.Printf("- **Elapsed:** %s\n", r.Duration.Elapsed)
		fmt.Printf("- **Start:** %s\n", r.Duration.StartTime)
		fmt.Printf("- **End:** %s\n", r.Duration.EndTime)
		fmt.Println()
	}

	// Trust
	if r.Trust != nil {
		fmt.Println("## Trust")
		fmt.Println()
		fmt.Printf("- **Score:** %d/100\n", r.Trust.Score)
		fmt.Printf("- **Events:** %d\n", r.Trust.TotalEvents)
		if len(r.Trust.Events) > 0 {
			fmt.Println()
			for _, e := range r.Trust.Events {
				fmt.Printf("  - `%s` %s", e.EventType, e.Detail)
				if !e.Timestamp.IsZero() {
					fmt.Printf(" (%s)", e.Timestamp.Format("15:04:05"))
				}
				fmt.Println()
			}
		}
		fmt.Println()
	}

	// Cost
	if r.Cost != nil {
		fmt.Println("## Cost")
		fmt.Println()
		fmt.Printf("- **Estimated:** $%.2f\n", r.Cost.EstimatedCost)
		if r.Cost.TokensIn > 0 || r.Cost.TokensOut > 0 {
			fmt.Printf("- **Tokens in:** %s\n", formatTokenCount(int(r.Cost.TokensIn)))
			fmt.Printf("- **Tokens out:** %s\n", formatTokenCount(int(r.Cost.TokensOut)))
		}
		fmt.Println()
	}

	// Footer
	fmt.Println(strings.Repeat("---", 1))
	fmt.Printf("*Generated by `agm session summary %s`*\n", r.SessionName)
}
