//go:build linux

package overlayfs

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// TestWriteSecretsUnit tests the writeSecrets function directly without mounting.
// This test can run on any platform without requiring OverlayFS support.
func TestWriteSecretsUnit(t *testing.T) {
	provider := NewProvider()
	upperDir := t.TempDir()

	// Set up test environment variable
	t.Setenv("TEST_VAR", "test_value")

	secrets := map[string]string{
		"API_KEY":    "secret-123",
		"DATABASE":   "postgres://localhost",
		"EXPAND_VAR": "${TEST_VAR}/expanded",
	}

	err := provider.writeSecrets(upperDir, secrets)
	require.NoError(t, err)

	// Verify .env file exists
	envPath := filepath.Join(upperDir, ".env")
	content, err := os.ReadFile(envPath)
	require.NoError(t, err)

	contentStr := string(content)

	// Verify header
	assert.Contains(t, contentStr, "# Auto-generated by AGM sandbox")
	assert.Contains(t, contentStr, "# DO NOT COMMIT THIS FILE")

	// Verify secrets
	assert.Contains(t, contentStr, "API_KEY=secret-123")
	assert.Contains(t, contentStr, "DATABASE=postgres://localhost")

	// Verify expansion
	assert.Contains(t, contentStr, "test_value/expanded")
	assert.NotContains(t, contentStr, "${TEST_VAR}")

	// Verify permissions
	stat, err := os.Stat(envPath)
	require.NoError(t, err)
	assert.Equal(t, os.FileMode(0600), stat.Mode().Perm())
}

// TestWriteSecretsEmpty verifies behavior with empty secrets map.
func TestWriteSecretsEmpty(t *testing.T) {
	provider := NewProvider()
	upperDir := t.TempDir()

	// Empty map should still work (creates file with just header)
	secrets := map[string]string{}

	err := provider.writeSecrets(upperDir, secrets)
	require.NoError(t, err)

	envPath := filepath.Join(upperDir, ".env")
	content, err := os.ReadFile(envPath)
	require.NoError(t, err)

	contentStr := string(content)

	// Should have header but no secrets
	assert.Contains(t, contentStr, "# Auto-generated by AGM sandbox")
	assert.NotContains(t, contentStr, "=") // No key=value pairs
}

// TestWriteSecretsSpecialCharacters verifies special character handling.
func TestWriteSecretsSpecialCharacters(t *testing.T) {
	provider := NewProvider()
	upperDir := t.TempDir()

	secrets := map[string]string{
		"URL":      "https://user:p@ss@example.com:8080",
		"SPACES":   "value with spaces",
		"QUOTES":   `value with "quotes"`,
		"NEWLINES": "line1\nline2",
		"EQUALS":   "key=value=more",
	}

	err := provider.writeSecrets(upperDir, secrets)
	require.NoError(t, err)

	envPath := filepath.Join(upperDir, ".env")
	content, err := os.ReadFile(envPath)
	require.NoError(t, err)

	contentStr := string(content)

	// Verify all special characters are preserved
	assert.Contains(t, contentStr, "URL=https://user:p@ss@example.com:8080")
	assert.Contains(t, contentStr, "SPACES=value with spaces")
	assert.Contains(t, contentStr, `QUOTES=value with "quotes"`)
	assert.Contains(t, contentStr, "NEWLINES=line1\nline2")
	assert.Contains(t, contentStr, "EQUALS=key=value=more")
}

// TestWriteSecretsEnvironmentExpansion verifies variable expansion behavior.
func TestWriteSecretsEnvironmentExpansion(t *testing.T) {
	provider := NewProvider()
	upperDir := t.TempDir()

	// Set up multiple environment variables
	t.Setenv("VAR1", "value1")
	t.Setenv("VAR2", "value2")
	t.Setenv("PATH_PREFIX", "/usr/local")

	secrets := map[string]string{
		"SIMPLE":  "${VAR1}",
		"PATH":    "${PATH_PREFIX}/bin",
		"MULTI":   "${VAR1}_and_${VAR2}",
		"LITERAL": "no_expansion",
		"MISSING": "${NONEXISTENT}",
	}

	err := provider.writeSecrets(upperDir, secrets)
	require.NoError(t, err)

	envPath := filepath.Join(upperDir, ".env")
	content, err := os.ReadFile(envPath)
	require.NoError(t, err)

	contentStr := string(content)

	// Verify expansions
	assert.Contains(t, contentStr, "SIMPLE=value1")
	assert.Contains(t, contentStr, "PATH=/usr/local/bin")
	assert.Contains(t, contentStr, "MULTI=value1_and_value2")
	assert.Contains(t, contentStr, "LITERAL=no_expansion")

	// Missing variables expand to empty string
	lines := strings.Split(contentStr, "\n")
	for _, line := range lines {
		if strings.HasPrefix(line, "MISSING=") {
			// Should not contain ${...} syntax
			assert.NotContains(t, line, "${NONEXISTENT}")
		}
	}
}

// TestWriteSecretsPermissions verifies strict file permissions.
func TestWriteSecretsPermissions(t *testing.T) {
	provider := NewProvider()
	upperDir := t.TempDir()

	secrets := map[string]string{
		"SECRET": "value",
	}

	err := provider.writeSecrets(upperDir, secrets)
	require.NoError(t, err)

	envPath := filepath.Join(upperDir, ".env")
	stat, err := os.Stat(envPath)
	require.NoError(t, err)

	// Must be exactly 0600 (owner read/write only)
	perms := stat.Mode().Perm()
	assert.Equal(t, os.FileMode(0600), perms)

	// No group or other permissions
	assert.Equal(t, os.FileMode(0), perms&0077)
}
