//go:build linux

package overlayfs_test

import (
	"context"
	"errors"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"github.com/vbonnet/dear-agent/internal/sandbox"
	"github.com/vbonnet/dear-agent/internal/sandbox/overlayfs"
)

// TestSecretsInjection verifies basic secrets injection functionality.
func TestSecretsInjection(t *testing.T) {
	if !isLinux() {
		t.Skip("OverlayFS tests only run on Linux")
	}

	if !hasKernel511() {
		t.Skip("OverlayFS rootless requires kernel 5.11+")
	}

	provider := overlayfs.NewProvider()
	ctx := context.Background()

	// Create test directories
	lowerDir := t.TempDir()
	workspaceDir := t.TempDir()

	// Set up environment variable for expansion test
	t.Setenv("TEST_HOME", "/test/home/path")

	req := sandbox.SandboxRequest{
		SessionID:    "secrets-test",
		LowerDirs:    []string{lowerDir},
		WorkspaceDir: workspaceDir,
		Secrets: map[string]string{
			"API_KEY":    "secret-value-123",
			"DATABASE":   "postgres://user:pass@localhost:5432/db",
			"EXPAND_VAR": "${TEST_HOME}/path",
		},
	}

	sb, err := provider.Create(ctx, req)
	if err != nil {
		var sbErr *sandbox.Error
		if errors.As(err, &sbErr) && sbErr.Code == sandbox.ErrCodeMountFailed {
			t.Skipf("Mount failed (may need permissions): %v", err)
		}
		require.NoError(t, err)
	}
	require.NotNil(t, sb)
	defer func() {
		_ = provider.Destroy(ctx, sb.ID)
	}()

	// Verify .env exists in upperdir
	envPath := filepath.Join(sb.UpperPath, ".env")
	content, err := os.ReadFile(envPath)
	require.NoError(t, err, ".env file should exist in upperdir")

	contentStr := string(content)

	// Verify header comments
	assert.Contains(t, contentStr, "# Auto-generated by AGM sandbox")
	assert.Contains(t, contentStr, "# DO NOT COMMIT THIS FILE")

	// Verify secrets are present
	assert.Contains(t, contentStr, "API_KEY=secret-value-123")
	assert.Contains(t, contentStr, "DATABASE=postgres://user:pass@localhost:5432/db")

	// Verify environment variable expansion happened
	assert.Contains(t, contentStr, "/test/home/path/path")
	assert.NotContains(t, contentStr, "${TEST_HOME}")

	// Verify file permissions (0600)
	stat, err := os.Stat(envPath)
	require.NoError(t, err)
	assert.Equal(t, os.FileMode(0600), stat.Mode().Perm(), "Secrets file should have 0600 permissions")

	// Verify .env NOT in lowerdir
	_, err = os.Stat(filepath.Join(lowerDir, ".env"))
	assert.True(t, os.IsNotExist(err), ".env should not exist in lowerdir")

	// Verify .env is visible in merged view
	mergedEnvPath := filepath.Join(sb.MergedPath, ".env")
	mergedContent, err := os.ReadFile(mergedEnvPath)
	require.NoError(t, err, ".env should be visible in merged view")
	assert.Equal(t, contentStr, string(mergedContent), "Merged .env should match upper .env")
}

// TestSecretsIsolation verifies secrets don't leak between sandboxes.
func TestSecretsIsolation(t *testing.T) {
	if !isLinux() {
		t.Skip("OverlayFS tests only run on Linux")
	}

	if !hasKernel511() {
		t.Skip("OverlayFS rootless requires kernel 5.11+")
	}

	provider := overlayfs.NewProvider()
	ctx := context.Background()

	// Create shared lowerdir
	lowerDir := t.TempDir()

	// Create first sandbox with secrets
	workspace1 := t.TempDir()
	req1 := sandbox.SandboxRequest{
		SessionID:    "sandbox-1",
		LowerDirs:    []string{lowerDir},
		WorkspaceDir: workspace1,
		Secrets: map[string]string{
			"SECRET_1": "value-from-sandbox-1",
			"SHARED":   "sandbox1-value",
		},
	}

	sb1, err := provider.Create(ctx, req1)
	if err != nil {
		var sbErr *sandbox.Error
		if errors.As(err, &sbErr) && sbErr.Code == sandbox.ErrCodeMountFailed {
			t.Skipf("Mount failed: %v", err)
		}
		require.NoError(t, err)
	}
	require.NotNil(t, sb1)
	defer func() {
		_ = provider.Destroy(ctx, sb1.ID)
	}()

	// Create second sandbox with different secrets
	workspace2 := t.TempDir()
	req2 := sandbox.SandboxRequest{
		SessionID:    "sandbox-2",
		LowerDirs:    []string{lowerDir},
		WorkspaceDir: workspace2,
		Secrets: map[string]string{
			"SECRET_2": "value-from-sandbox-2",
			"SHARED":   "sandbox2-value",
		},
	}

	sb2, err := provider.Create(ctx, req2)
	if err != nil {
		var sbErr *sandbox.Error
		if errors.As(err, &sbErr) && sbErr.Code == sandbox.ErrCodeMountFailed {
			t.Skipf("Mount failed: %v", err)
		}
		require.NoError(t, err)
	}
	require.NotNil(t, sb2)
	defer func() {
		_ = provider.Destroy(ctx, sb2.ID)
	}()

	// Verify sandbox 1 secrets
	env1Path := filepath.Join(sb1.UpperPath, ".env")
	content1, err := os.ReadFile(env1Path)
	require.NoError(t, err)
	content1Str := string(content1)

	assert.Contains(t, content1Str, "SECRET_1=value-from-sandbox-1")
	assert.Contains(t, content1Str, "SHARED=sandbox1-value")
	assert.NotContains(t, content1Str, "SECRET_2")
	assert.NotContains(t, content1Str, "sandbox2-value")

	// Verify sandbox 2 secrets
	env2Path := filepath.Join(sb2.UpperPath, ".env")
	content2, err := os.ReadFile(env2Path)
	require.NoError(t, err)
	content2Str := string(content2)

	assert.Contains(t, content2Str, "SECRET_2=value-from-sandbox-2")
	assert.Contains(t, content2Str, "SHARED=sandbox2-value")
	assert.NotContains(t, content2Str, "SECRET_1")
	assert.NotContains(t, content2Str, "sandbox1-value")

	// Verify lowerdir has no .env file
	_, err = os.Stat(filepath.Join(lowerDir, ".env"))
	assert.True(t, os.IsNotExist(err), "No .env should exist in shared lowerdir")
}

// TestNoSecretsWhenEmpty verifies no .env file is created when secrets are empty.
func TestNoSecretsWhenEmpty(t *testing.T) {
	if !isLinux() {
		t.Skip("OverlayFS tests only run on Linux")
	}

	if !hasKernel511() {
		t.Skip("OverlayFS rootless requires kernel 5.11+")
	}

	provider := overlayfs.NewProvider()
	ctx := context.Background()

	// Create sandbox without secrets
	lowerDir := t.TempDir()
	workspaceDir := t.TempDir()

	req := sandbox.SandboxRequest{
		SessionID:    "no-secrets-test",
		LowerDirs:    []string{lowerDir},
		WorkspaceDir: workspaceDir,
		Secrets:      nil, // No secrets
	}

	sb, err := provider.Create(ctx, req)
	if err != nil {
		var sbErr *sandbox.Error
		if errors.As(err, &sbErr) && sbErr.Code == sandbox.ErrCodeMountFailed {
			t.Skipf("Mount failed: %v", err)
		}
		require.NoError(t, err)
	}
	require.NotNil(t, sb)
	defer func() {
		_ = provider.Destroy(ctx, sb.ID)
	}()

	// Verify no .env file was created
	envPath := filepath.Join(sb.UpperPath, ".env")
	_, err = os.Stat(envPath)
	assert.True(t, os.IsNotExist(err), "No .env file should be created when secrets are empty")

	// Also check with empty map
	workspaceDir2 := t.TempDir()
	req2 := sandbox.SandboxRequest{
		SessionID:    "no-secrets-test-2",
		LowerDirs:    []string{lowerDir},
		WorkspaceDir: workspaceDir2,
		Secrets:      map[string]string{}, // Empty map
	}

	sb2, err := provider.Create(ctx, req2)
	if err != nil {
		var sbErr *sandbox.Error
		if errors.As(err, &sbErr) && sbErr.Code == sandbox.ErrCodeMountFailed {
			t.Skipf("Mount failed: %v", err)
		}
		require.NoError(t, err)
	}
	require.NotNil(t, sb2)
	defer func() {
		_ = provider.Destroy(ctx, sb2.ID)
	}()

	envPath2 := filepath.Join(sb2.UpperPath, ".env")
	_, err = os.Stat(envPath2)
	assert.True(t, os.IsNotExist(err), "No .env file should be created when secrets map is empty")
}

// TestSecretsEnvironmentExpansion tests various environment variable expansion scenarios.
func TestSecretsEnvironmentExpansion(t *testing.T) {
	if !isLinux() {
		t.Skip("OverlayFS tests only run on Linux")
	}

	if !hasKernel511() {
		t.Skip("OverlayFS rootless requires kernel 5.11+")
	}

	provider := overlayfs.NewProvider()
	ctx := context.Background()

	// Set up test environment variables
	t.Setenv("TEST_VAR", "test_value")
	t.Setenv("PATH_PREFIX", "/usr/local")
	t.Setenv("NESTED_VAR", "nested_${TEST_VAR}")

	lowerDir := t.TempDir()
	workspaceDir := t.TempDir()

	req := sandbox.SandboxRequest{
		SessionID:    "expansion-test",
		LowerDirs:    []string{lowerDir},
		WorkspaceDir: workspaceDir,
		Secrets: map[string]string{
			// Simple expansion
			"SIMPLE": "${TEST_VAR}",
			// Expansion in middle of string
			"PATH": "${PATH_PREFIX}/bin",
			// Multiple expansions
			"MULTI": "${TEST_VAR}_and_${PATH_PREFIX}",
			// No expansion needed
			"LITERAL": "no_variables_here",
			// Nested expansion (will expand NESTED_VAR but not nested TEST_VAR)
			"NESTED": "${NESTED_VAR}",
			// Non-existent variable (should remain as-is or expand to empty)
			"MISSING": "${NONEXISTENT_VAR}",
		},
	}

	sb, err := provider.Create(ctx, req)
	if err != nil {
		var sbErr *sandbox.Error
		if errors.As(err, &sbErr) && sbErr.Code == sandbox.ErrCodeMountFailed {
			t.Skipf("Mount failed: %v", err)
		}
		require.NoError(t, err)
	}
	require.NotNil(t, sb)
	defer func() {
		_ = provider.Destroy(ctx, sb.ID)
	}()

	envPath := filepath.Join(sb.UpperPath, ".env")
	content, err := os.ReadFile(envPath)
	require.NoError(t, err)
	contentStr := string(content)

	// Verify expansions
	assert.Contains(t, contentStr, "SIMPLE=test_value")
	assert.Contains(t, contentStr, "PATH=/usr/local/bin")
	assert.Contains(t, contentStr, "MULTI=test_value_and_/usr/local")
	assert.Contains(t, contentStr, "LITERAL=no_variables_here")
	assert.Contains(t, contentStr, "NESTED=nested_${TEST_VAR}") // Only first level expanded

	// Non-existent variables expand to empty string
	lines := strings.Split(contentStr, "\n")
	for _, line := range lines {
		if strings.HasPrefix(line, "MISSING=") {
			// Should not contain the ${...} syntax
			assert.NotContains(t, line, "${NONEXISTENT_VAR}")
		}
	}
}

// TestSecretsPermissions verifies file permissions are strictly enforced.
func TestSecretsPermissions(t *testing.T) {
	if !isLinux() {
		t.Skip("OverlayFS tests only run on Linux")
	}

	if !hasKernel511() {
		t.Skip("OverlayFS rootless requires kernel 5.11+")
	}

	provider := overlayfs.NewProvider()
	ctx := context.Background()

	lowerDir := t.TempDir()
	workspaceDir := t.TempDir()

	req := sandbox.SandboxRequest{
		SessionID:    "perms-test",
		LowerDirs:    []string{lowerDir},
		WorkspaceDir: workspaceDir,
		Secrets: map[string]string{
			"SENSITIVE": "very-secret-value",
		},
	}

	sb, err := provider.Create(ctx, req)
	if err != nil {
		var sbErr *sandbox.Error
		if errors.As(err, &sbErr) && sbErr.Code == sandbox.ErrCodeMountFailed {
			t.Skipf("Mount failed: %v", err)
		}
		require.NoError(t, err)
	}
	require.NotNil(t, sb)
	defer func() {
		_ = provider.Destroy(ctx, sb.ID)
	}()

	envPath := filepath.Join(sb.UpperPath, ".env")
	stat, err := os.Stat(envPath)
	require.NoError(t, err)

	// Verify permissions are exactly 0600 (owner read/write only)
	perms := stat.Mode().Perm()
	assert.Equal(t, os.FileMode(0600), perms, "Secrets file must have 0600 permissions")

	// Verify no group or other permissions
	assert.Equal(t, os.FileMode(0), perms&0077, "No group or other permissions should be set")
}

// TestSecretsSpecialCharacters verifies handling of special characters in secrets.
func TestSecretsSpecialCharacters(t *testing.T) {
	if !isLinux() {
		t.Skip("OverlayFS tests only run on Linux")
	}

	if !hasKernel511() {
		t.Skip("OverlayFS rootless requires kernel 5.11+")
	}

	provider := overlayfs.NewProvider()
	ctx := context.Background()

	lowerDir := t.TempDir()
	workspaceDir := t.TempDir()

	req := sandbox.SandboxRequest{
		SessionID:    "special-chars-test",
		LowerDirs:    []string{lowerDir},
		WorkspaceDir: workspaceDir,
		Secrets: map[string]string{
			// Special characters that should be preserved
			"URL":      "https://user:p@ss!word@example.com:8080/path?query=value&other=123",
			"SPACES":   "value with spaces",
			"QUOTES":   `value with "quotes" and 'apostrophes'`,
			"NEWLINES": "line1\nline2\nline3",
			"TABS":     "tab\tseparated\tvalues",
			"EQUALS":   "key=value=more=equals",
			"HASH":     "value # with hash",
		},
	}

	sb, err := provider.Create(ctx, req)
	if err != nil {
		var sbErr *sandbox.Error
		if errors.As(err, &sbErr) && sbErr.Code == sandbox.ErrCodeMountFailed {
			t.Skipf("Mount failed: %v", err)
		}
		require.NoError(t, err)
	}
	require.NotNil(t, sb)
	defer func() {
		_ = provider.Destroy(ctx, sb.ID)
	}()

	envPath := filepath.Join(sb.UpperPath, ".env")
	content, err := os.ReadFile(envPath)
	require.NoError(t, err)
	contentStr := string(content)

	// Verify special characters are preserved
	assert.Contains(t, contentStr, "URL=https://user:p@ss!word@example.com:8080/path?query=value&other=123")
	assert.Contains(t, contentStr, "SPACES=value with spaces")
	assert.Contains(t, contentStr, `QUOTES=value with "quotes" and 'apostrophes'`)
	assert.Contains(t, contentStr, "NEWLINES=line1\nline2\nline3")
	assert.Contains(t, contentStr, "TABS=tab\tseparated\tvalues")
	assert.Contains(t, contentStr, "EQUALS=key=value=more=equals")
	assert.Contains(t, contentStr, "HASH=value # with hash")
}

// TestSecretsNotInLowerdirAfterDestroy verifies cleanup doesn't leak secrets.
func TestSecretsNotInLowerdirAfterDestroy(t *testing.T) {
	if !isLinux() {
		t.Skip("OverlayFS tests only run on Linux")
	}

	if !hasKernel511() {
		t.Skip("OverlayFS rootless requires kernel 5.11+")
	}

	provider := overlayfs.NewProvider()
	ctx := context.Background()

	lowerDir := t.TempDir()
	workspaceDir := t.TempDir()

	req := sandbox.SandboxRequest{
		SessionID:    "cleanup-test",
		LowerDirs:    []string{lowerDir},
		WorkspaceDir: workspaceDir,
		Secrets: map[string]string{
			"TOP_SECRET": "super-secret-value",
		},
	}

	sb, err := provider.Create(ctx, req)
	if err != nil {
		var sbErr *sandbox.Error
		if errors.As(err, &sbErr) && sbErr.Code == sandbox.ErrCodeMountFailed {
			t.Skipf("Mount failed: %v", err)
		}
		require.NoError(t, err)
	}
	require.NotNil(t, sb)

	// Verify .env exists in upperdir before destroy
	envPath := filepath.Join(sb.UpperPath, ".env")
	_, err = os.Stat(envPath)
	require.NoError(t, err, ".env should exist before destroy")

	// Destroy sandbox
	err = provider.Destroy(ctx, sb.ID)
	require.NoError(t, err)

	// Verify lowerdir has no .env file
	lowerEnvPath := filepath.Join(lowerDir, ".env")
	_, err = os.Stat(lowerEnvPath)
	assert.True(t, os.IsNotExist(err), ".env should never exist in lowerdir")

	// Verify workspace directory is cleaned up (or at least .env is gone)
	_, err = os.Stat(envPath)
	// After destroy, the file should be gone (entire workspace cleaned up)
	if err == nil {
		// If workspace still exists, verify .env is gone
		t.Logf("Workspace still exists after destroy, checking .env is removed")
		assert.True(t, os.IsNotExist(err), ".env should be removed during cleanup")
	}
}

// Helper functions are defined in provider_test.go and shared across all test files
