// Package intent implements a non-blocking coordination signal for
// agents working in parallel: each agent declares which files and
// packages it intends to touch, other agents can read the board to
// see what's in flight, and the orchestrator can flag overlaps.
//
// The key word is "non-blocking". An intent is information, not a
// lock. Two agents can declare overlapping intents and both proceed —
// the board exists so they (and the human reviewing them) know it's
// happening. We chose this over global locks because locks are
// training wheels: they prevent agents from learning to coordinate by
// removing the conflict entirely. Conflict detection beats conflict
// avoidance when the goal is for agents to develop better intuition
// about ownership.
//
// Storage is filesystem-backed. Each intent is one JSON file under
// the board directory keyed by intent ID. We pick files (not SQLite,
// not a daemon) because the board is multi-writer by definition and
// the OS already handles atomic file writes; adding a process or a
// schema would buy us nothing for a few-dozen-row dataset.
//
// Intents auto-expire on a TTL. Callers should run Expire() before a
// List query if they care about freshness, or use ListActive which
// filters expired rows in-memory without touching the disk.
package intent

import (
	"crypto/rand"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"
)

// DefaultTTL is the lifetime of a freshly declared intent if the
// caller doesn't pass an explicit one. Long enough that a human-paced
// task won't expire mid-flight; short enough that a forgotten intent
// from a crashed worker won't haunt the board for a week.
const DefaultTTL = 30 * time.Minute

// Intent records one agent's declared scope of work.
type Intent struct {
	// ID is opaque, generated by Declare. Callers do not set it.
	ID string `json:"id"`
	// SessionID is the AGM session (or any agent identifier) that owns
	// this intent. Required.
	SessionID string `json:"session_id"`
	// Files is the list of file paths the agent intends to modify.
	// Paths are stored as given — callers should normalize to repo-root
	// relative form before declaring so overlap detection has a chance.
	Files []string `json:"files,omitempty"`
	// Packages is a parallel list at a coarser grain (Go packages,
	// directories, modules). Either or both of Files/Packages may be
	// empty but at least one must be non-empty.
	Packages []string `json:"packages,omitempty"`
	// Description is free-form context shown alongside the intent. It
	// is what a human reviewer reads to understand "what is this agent
	// trying to do?".
	Description string `json:"description,omitempty"`
	// DeclaredAt is set by Declare.
	DeclaredAt time.Time `json:"declared_at"`
	// ExpiresAt is set by Declare from the TTL.
	ExpiresAt time.Time `json:"expires_at"`
}

// Active reports whether the intent has not yet expired at now.
func (i Intent) Active(now time.Time) bool {
	return now.Before(i.ExpiresAt)
}

// Overlaps reports whether i and other share any declared file or
// package. The comparison is set-membership on the path strings — we
// do NOT walk the filesystem or expand globs, since the goal is a
// fast, conservative signal, not a perfect oracle. If either side is
// vague (e.g. declares the whole repo via "."), it should expect
// many overlaps and that is the correct answer.
func (i Intent) Overlaps(other Intent) bool {
	if i.SessionID == other.SessionID {
		// Two intents from the same session never count as a conflict —
		// the agent is welcome to refine its own scope mid-task.
		return false
	}
	if hasCommon(i.Files, other.Files) {
		return true
	}
	if hasCommon(i.Packages, other.Packages) {
		return true
	}
	return false
}

func hasCommon(a, b []string) bool {
	if len(a) == 0 || len(b) == 0 {
		return false
	}
	set := make(map[string]struct{}, len(a))
	for _, x := range a {
		set[x] = struct{}{}
	}
	for _, y := range b {
		if _, ok := set[y]; ok {
			return true
		}
	}
	return false
}

// DeclareOpts tunes a Declare call.
type DeclareOpts struct {
	// SessionID owns the intent. Required.
	SessionID string
	// Files and Packages describe the scope. At least one must be
	// non-empty.
	Files    []string
	Packages []string
	// Description is free-form context.
	Description string
	// TTL overrides DefaultTTL when non-zero.
	TTL time.Duration
}

// ListFilter narrows a List call. Zero value matches everything that
// has not yet expired.
type ListFilter struct {
	// SessionID restricts results to one session. Empty matches all.
	SessionID string
	// IncludeExpired returns expired-but-still-on-disk rows too.
	// Useful for `agm intent list --all` debugging.
	IncludeExpired bool
}

// Board is the storage abstraction so callers can mock it in tests.
// The exported FileBoard is the only production implementation.
type Board interface {
	Declare(opts DeclareOpts) (Intent, error)
	Get(id string) (Intent, error)
	List(filter ListFilter) ([]Intent, error)
	Remove(id string) error
	Expire() (int, error)
	Overlaps(intent Intent) ([]Intent, error)
}

// ErrNotFound is returned by Get/Remove when no intent has the given
// ID. Callers should errors.Is against it.
var ErrNotFound = errors.New("intent: not found")

// FileBoard is a filesystem-backed Board. Each intent is one JSON
// file at <Dir>/<id>.json. Concurrent writers are safe because each
// row is a separate file and atomic via rename-into-place.
type FileBoard struct {
	Dir string
	// Now is the time source. Tests inject a stub; production leaves
	// it nil and the board uses time.Now.
	Now func() time.Time
}

// NewFileBoard returns a board rooted at dir and ensures the
// directory exists.
func NewFileBoard(dir string) (*FileBoard, error) {
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return nil, fmt.Errorf("intent: mkdir %s: %w", dir, err)
	}
	return &FileBoard{Dir: dir}, nil
}

func (b *FileBoard) now() time.Time {
	if b.Now != nil {
		return b.Now()
	}
	return time.Now()
}

func (b *FileBoard) path(id string) string {
	return filepath.Join(b.Dir, id+".json")
}

// Declare creates a new intent on the board and returns it. The ID
// and timestamps are generated; the caller must not pre-populate
// them.
func (b *FileBoard) Declare(opts DeclareOpts) (Intent, error) {
	if strings.TrimSpace(opts.SessionID) == "" {
		return Intent{}, errors.New("intent: session_id is required")
	}
	if len(opts.Files) == 0 && len(opts.Packages) == 0 {
		return Intent{}, errors.New("intent: must declare at least one file or package")
	}
	ttl := opts.TTL
	if ttl <= 0 {
		ttl = DefaultTTL
	}
	id, err := newID()
	if err != nil {
		return Intent{}, fmt.Errorf("intent: generate id: %w", err)
	}
	now := b.now()
	intent := Intent{
		ID:          id,
		SessionID:   opts.SessionID,
		Files:       dedup(opts.Files),
		Packages:    dedup(opts.Packages),
		Description: opts.Description,
		DeclaredAt:  now,
		ExpiresAt:   now.Add(ttl),
	}
	if err := b.write(intent); err != nil {
		return Intent{}, err
	}
	return intent, nil
}

// Get returns the intent with id, or ErrNotFound.
func (b *FileBoard) Get(id string) (Intent, error) {
	data, err := os.ReadFile(b.path(id))
	if err != nil {
		if errors.Is(err, os.ErrNotExist) {
			return Intent{}, ErrNotFound
		}
		return Intent{}, fmt.Errorf("intent: read %s: %w", id, err)
	}
	var intent Intent
	if err := json.Unmarshal(data, &intent); err != nil {
		return Intent{}, fmt.Errorf("intent: parse %s: %w", id, err)
	}
	return intent, nil
}

// List returns intents matching filter, sorted oldest-first.
func (b *FileBoard) List(filter ListFilter) ([]Intent, error) {
	entries, err := os.ReadDir(b.Dir)
	if err != nil {
		if errors.Is(err, os.ErrNotExist) {
			return nil, nil
		}
		return nil, fmt.Errorf("intent: read dir: %w", err)
	}
	now := b.now()
	out := make([]Intent, 0, len(entries))
	for _, e := range entries {
		if e.IsDir() || !strings.HasSuffix(e.Name(), ".json") {
			continue
		}
		id := strings.TrimSuffix(e.Name(), ".json")
		intent, err := b.Get(id)
		if err != nil {
			if errors.Is(err, ErrNotFound) {
				// File vanished between ReadDir and Get; skip.
				continue
			}
			return nil, err
		}
		if !filter.IncludeExpired && !intent.Active(now) {
			continue
		}
		if filter.SessionID != "" && intent.SessionID != filter.SessionID {
			continue
		}
		out = append(out, intent)
	}
	sort.Slice(out, func(i, j int) bool {
		return out[i].DeclaredAt.Before(out[j].DeclaredAt)
	})
	return out, nil
}

// Remove deletes the intent with id.
func (b *FileBoard) Remove(id string) error {
	if err := os.Remove(b.path(id)); err != nil {
		if errors.Is(err, os.ErrNotExist) {
			return ErrNotFound
		}
		return fmt.Errorf("intent: remove %s: %w", id, err)
	}
	return nil
}

// Expire deletes all intents whose ExpiresAt is in the past. Returns
// the count removed.
func (b *FileBoard) Expire() (int, error) {
	all, err := b.List(ListFilter{IncludeExpired: true})
	if err != nil {
		return 0, err
	}
	now := b.now()
	removed := 0
	for _, intent := range all {
		if intent.Active(now) {
			continue
		}
		if err := b.Remove(intent.ID); err != nil && !errors.Is(err, ErrNotFound) {
			return removed, err
		}
		removed++
	}
	return removed, nil
}

// Overlaps returns the active intents on the board that share files
// or packages with the given intent (excluding the intent itself).
func (b *FileBoard) Overlaps(intent Intent) ([]Intent, error) {
	all, err := b.List(ListFilter{})
	if err != nil {
		return nil, err
	}
	out := make([]Intent, 0)
	for _, other := range all {
		if other.ID == intent.ID {
			continue
		}
		if intent.Overlaps(other) {
			out = append(out, other)
		}
	}
	return out, nil
}

func (b *FileBoard) write(intent Intent) error {
	data, err := json.MarshalIndent(intent, "", "  ")
	if err != nil {
		return fmt.Errorf("intent: marshal: %w", err)
	}
	final := b.path(intent.ID)
	tmp := final + ".tmp"
	if err := os.WriteFile(tmp, data, 0o600); err != nil {
		return fmt.Errorf("intent: write tmp: %w", err)
	}
	if err := os.Rename(tmp, final); err != nil {
		return fmt.Errorf("intent: rename: %w", err)
	}
	return nil
}

// newID returns a 16-hex-char random ID. Short enough to be easy to
// type when removing an intent by hand; long enough that two parallel
// agents won't collide.
func newID() (string, error) {
	var b [8]byte
	if _, err := rand.Read(b[:]); err != nil {
		return "", err
	}
	return hex.EncodeToString(b[:]), nil
}

// dedup returns a sorted, de-duplicated copy of in. Empty/blank
// entries are dropped.
func dedup(in []string) []string {
	if len(in) == 0 {
		return nil
	}
	seen := make(map[string]struct{}, len(in))
	out := make([]string, 0, len(in))
	for _, s := range in {
		s = strings.TrimSpace(s)
		if s == "" {
			continue
		}
		if _, ok := seen[s]; ok {
			continue
		}
		seen[s] = struct{}{}
		out = append(out, s)
	}
	sort.Strings(out)
	return out
}
