// Command skill-projections checks the two generated regular-file skill
// delegates that point at the canonical SPEC governance workflows.
//
// Usage:
//
//	skill-projections -repo <root>
//	skill-projections -repo <root> -write
package main

import (
	"bytes"
	"context"
	"errors"
	"flag"
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
	"time"

	"gopkg.in/yaml.v3"
)

const (
	generatedMarker          = "<!-- generated by tools/skill-projections; do not edit -->"
	maxCanonicalSkillBytes   = 1 << 20
	maxDelegateBytes         = 64 << 10
	maxGitPointerBytes       = 4 << 10
	linkedWorktreeDeadline   = 5 * time.Second
	trustedGitCandidate      = "/usr/bin/git"
	markerScanMaxFiles       = 100_000
	markerScanMaxDirectories = 25_000
	markerScanMaxDepth       = 64
	markerScanMaxBytes       = 32 << 20
	markerScanElapsedBudget  = 10 * time.Second
)

type projection struct {
	canonical string
	delegate  string
}

var projections = []projection{
	{canonical: "spec-governance/skills/write-spec/SKILL.md", delegate: ".agents/skills/write-spec/SKILL.md"},
	{canonical: "spec-governance/skills/audit-specs/SKILL.md", delegate: ".agents/skills/audit-specs/SKILL.md"},
}

type metadata struct {
	Name        string `yaml:"name"`
	Description string `yaml:"description"`
}

type delegateCreator func(root *repositoryRoot, relative string, content []byte) (created bool, err error)

type linkedWorktreeDiscoverer func(currentDirectory, gitExecutable string, gitEnvironment []string) (worktreeRoot, gitDirectory, commonDirectory string, err error)

type authenticatedWorktree struct {
	repository    *repositoryRoot
	rootPath      string
	gitExecutable string
}

type markerScanLimits struct {
	maxFiles       int
	maxDirectories int
	maxDepth       int
	maxBytes       int64
	elapsedBudget  time.Duration
	now            func(checkpoint string) time.Time
}

func defaultMarkerScanLimits() markerScanLimits {
	return markerScanLimits{
		maxFiles:       markerScanMaxFiles,
		maxDirectories: markerScanMaxDirectories,
		maxDepth:       markerScanMaxDepth,
		maxBytes:       markerScanMaxBytes,
		elapsedBudget:  markerScanElapsedBudget,
		now:            func(_ string) time.Time { return time.Now() },
	}
}

func main() { os.Exit(run(os.Args[1:], os.Stdout, os.Stderr)) }

func run(args []string, stdout, stderr io.Writer) int {
	flags := flag.NewFlagSet("skill-projections", flag.ContinueOnError)
	flags.SetOutput(stderr)
	repositoryArgument := flags.String("repo", "", "repository containing the canonical skills")
	write := flags.Bool("write", false, "create the two absent delegates after validating the canonical sources")
	flags.Usage = func() {
		fmt.Fprintln(stderr, "Usage: skill-projections -repo <root> [-write]")
		flags.PrintDefaults()
	}
	if err := flags.Parse(args); err != nil || *repositoryArgument == "" || flags.NArg() != 0 {
		flags.Usage()
		return 2
	}
	rootPath, err := filepath.Abs(*repositoryArgument)
	if err != nil {
		fmt.Fprintf(stderr, "skill-projections: resolve repository: %v\n", err)
		return 2
	}

	var authentication authenticatedWorktree
	var repository *repositoryRoot
	if *write {
		authentication, err = authenticateWriteRoot(rootPath)
		if err == nil {
			repository = authentication.repository
		}
	} else {
		repository, err = openRepositoryRoot(rootPath)
	}
	if err != nil {
		fmt.Fprintf(stderr, "skill-projections: %v\n", err)
		return 1
	}

	identity := repository.identity()
	var operationErr error
	if *write {
		operationErr = writeDelegates(repository)
		if operationErr == nil {
			if validationErr := checkDelegates(repository); validationErr != nil {
				operationErr = fmt.Errorf(
					"post-write validation failed: %w; write mode never rolls back or deletes created delegates, so inspect and remove these paths manually before retrying: %s",
					validationErr,
					delegatePathList(),
				)
			}
		}
	} else {
		operationErr = checkDelegates(repository)
	}
	closeErr := repository.close()
	if operationErr != nil {
		fmt.Fprintf(stderr, "skill-projections: %v\n", operationErr)
		if closeErr != nil {
			fmt.Fprintf(stderr, "skill-projections: close retained repository root: %v\n", closeErr)
		}
		return 1
	}
	if closeErr != nil {
		fmt.Fprintf(stderr, "skill-projections: close retained repository root: %v\n", closeErr)
		return 1
	}

	if *write {
		fmt.Fprintf(
			stdout,
			"ok: 2 canonical skill discovery delegates were created and match their sources; write root authenticated with %s, reciprocal linked-worktree metadata, and retained identity %s\n",
			authentication.gitExecutable,
			identity,
		)
		return 0
	}
	fmt.Fprintln(stdout, "ok: 2 canonical skill discovery delegates match their sources")
	return 0
}

func delegatePathList() string {
	paths := make([]string, 0, len(projections))
	for _, item := range projections {
		paths = append(paths, item.delegate)
	}
	return strings.Join(paths, ", ")
}

func authenticateWriteRoot(requestedRoot string) (authenticatedWorktree, error) {
	currentDirectory, err := os.Getwd()
	if err != nil {
		return authenticatedWorktree{}, fmt.Errorf("resolve current directory for write mode: %w", err)
	}
	return authenticateWriteRootFrom(currentDirectory, requestedRoot)
}

func authenticateWriteRootFrom(currentDirectory, requestedRoot string) (authenticatedWorktree, error) {
	return authenticateWriteRootFromWithDiscovery(currentDirectory, requestedRoot, discoverLinkedWorktree)
}

func authenticateWriteRootFromWithDiscovery(
	currentDirectory, requestedRoot string,
	discover linkedWorktreeDiscoverer,
) (authenticatedWorktree, error) {
	repository, err := openRepositoryRoot(requestedRoot)
	if err != nil {
		return authenticatedWorktree{}, fmt.Errorf("retain caller-requested repository root before Git discovery: %w", err)
	}
	authentication, authenticationErr := authenticateRetainedWriteRootFrom(
		repository,
		currentDirectory,
		requestedRoot,
		discover,
	)
	if authenticationErr != nil {
		closeErr := repository.close()
		return authenticatedWorktree{}, errors.Join(authenticationErr, closeErr)
	}
	return authentication, nil
}

func authenticateRetainedWriteRootFrom(
	repository *repositoryRoot,
	currentDirectory, requestedRoot string,
	discover linkedWorktreeDiscoverer,
) (authenticatedWorktree, error) {
	requested, err := canonicalExistingPath(requestedRoot)
	if err != nil {
		return authenticatedWorktree{}, fmt.Errorf("resolve retained caller-requested repository root before Git discovery: %w", err)
	}
	if err := repository.verifyPathIdentity(requested, "caller-requested worktree before Git discovery"); err != nil {
		return authenticatedWorktree{}, err
	}
	gitExecutable, err := resolveTrustedGitExecutable()
	if err != nil {
		return authenticatedWorktree{}, err
	}
	gitEnvironment, err := gitAuthenticationEnvironment(os.Environ(), gitExecutable)
	if err != nil {
		return authenticatedWorktree{}, err
	}
	worktreeRoot, gitDirectory, commonDirectory, err := discover(currentDirectory, gitExecutable, gitEnvironment)
	if err != nil {
		return authenticatedWorktree{}, err
	}
	if requested != worktreeRoot {
		return authenticatedWorktree{}, fmt.Errorf("write mode refuses caller-selected repository root %s; run it for the current linked worktree %s", requested, worktreeRoot)
	}
	if err := repository.verifyPathIdentity(worktreeRoot, "Git-reported worktree"); err != nil {
		return authenticatedWorktree{}, err
	}
	if gitDirectory == commonDirectory {
		return authenticatedWorktree{}, fmt.Errorf("write mode requires the current checkout to be a linked worktree; %s is the primary checkout", worktreeRoot)
	}
	if err := requireDirectory(gitDirectory, "linked-worktree Git directory"); err != nil {
		return authenticatedWorktree{}, err
	}
	if err := requireDirectory(commonDirectory, "common Git directory"); err != nil {
		return authenticatedWorktree{}, err
	}
	if err := verifyLinkedWorktreePointers(repository, worktreeRoot, gitDirectory); err != nil {
		return authenticatedWorktree{}, err
	}
	return authenticatedWorktree{
		repository:    repository,
		rootPath:      worktreeRoot,
		gitExecutable: gitExecutable,
	}, nil
}

func discoverLinkedWorktree(currentDirectory, gitExecutable string, gitEnvironment []string) (string, string, string, error) {
	ctx, cancel := context.WithTimeout(context.Background(), linkedWorktreeDeadline)
	defer cancel()
	command := exec.CommandContext(
		ctx,
		gitExecutable,
		"-C",
		currentDirectory,
		"rev-parse",
		"--path-format=absolute",
		"--show-toplevel",
		"--git-dir",
		"--git-common-dir",
	)
	command.Env = gitEnvironment
	var output bytes.Buffer
	command.Stdout = &output
	command.Stderr = &output
	if err := command.Run(); err != nil {
		if ctx.Err() != nil {
			return "", "", "", fmt.Errorf("authenticate current linked worktree with trusted Git executable %s within %s: %w", gitExecutable, linkedWorktreeDeadline, ctx.Err())
		}
		return "", "", "", fmt.Errorf("authenticate current linked worktree with trusted Git executable %s: %w: %s", gitExecutable, err, strings.TrimSpace(output.String()))
	}
	lines := strings.Split(strings.ReplaceAll(strings.TrimSpace(output.String()), "\r", ""), "\n")
	if len(lines) != 3 {
		return "", "", "", fmt.Errorf("authenticate current linked worktree with trusted Git executable %s: unexpected output %q", gitExecutable, output.String())
	}
	worktreeRoot, err := canonicalExistingPath(lines[0])
	if err != nil {
		return "", "", "", fmt.Errorf("authenticate current linked worktree root: %w", err)
	}
	gitDirectory, err := canonicalExistingPath(lines[1])
	if err != nil {
		return "", "", "", fmt.Errorf("authenticate linked-worktree Git directory: %w", err)
	}
	commonDirectory, err := canonicalExistingPath(lines[2])
	if err != nil {
		return "", "", "", fmt.Errorf("authenticate common Git directory: %w", err)
	}
	return worktreeRoot, gitDirectory, commonDirectory, nil
}

func resolveTrustedGitExecutable() (string, error) {
	executable, err := canonicalExistingPath(trustedGitCandidate)
	if err != nil {
		return "", fmt.Errorf("resolve trusted Git executable %s: %w", trustedGitCandidate, err)
	}
	if !filepath.IsAbs(executable) {
		return "", fmt.Errorf("trusted Git executable did not resolve to an absolute path: %s", executable)
	}
	info, err := os.Lstat(executable)
	if err != nil {
		return "", fmt.Errorf("stat trusted Git executable %s: %w", executable, err)
	}
	if !info.Mode().IsRegular() || info.Mode().Perm()&0o111 == 0 {
		return "", fmt.Errorf("trusted Git executable %s must be a regular executable file", executable)
	}
	return executable, nil
}

func gitAuthenticationEnvironment(environ []string, gitExecutable string) ([]string, error) {
	allowed := make(map[string]string)
	for _, entry := range environ {
		key, value, ok := strings.Cut(entry, "=")
		if !ok {
			continue
		}
		if isGitRepositoryOverride(key) {
			return nil, fmt.Errorf("write mode refuses inherited Git environment override %s", key)
		}
		if key == "LANG" || key == "LANGUAGE" || strings.HasPrefix(key, "LC_") || key == "TMPDIR" || key == "TMP" || key == "TEMP" || key == "SystemRoot" || key == "SYSTEMROOT" {
			allowed[key] = value
		}
	}
	keys := make([]string, 0, len(allowed))
	for key := range allowed {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	result := make([]string, 0, len(keys)+5)
	for _, key := range keys {
		result = append(result, key+"="+allowed[key])
	}
	return append(
		result,
		"PATH="+filepath.Dir(gitExecutable)+string(os.PathListSeparator)+"/bin",
		"GIT_CONFIG_NOSYSTEM=1",
		"GIT_CONFIG_GLOBAL="+os.DevNull,
		"GIT_TERMINAL_PROMPT=0",
		"GIT_OPTIONAL_LOCKS=0",
	), nil
}

func isGitRepositoryOverride(key string) bool {
	switch key {
	case "GIT_DIR",
		"GIT_WORK_TREE",
		"GIT_COMMON_DIR",
		"GIT_INDEX_FILE",
		"GIT_OBJECT_DIRECTORY",
		"GIT_ALTERNATE_OBJECT_DIRECTORIES",
		"GIT_NAMESPACE",
		"GIT_CEILING_DIRECTORIES",
		"GIT_DISCOVERY_ACROSS_FILESYSTEM",
		"GIT_CONFIG",
		"GIT_CONFIG_GLOBAL",
		"GIT_CONFIG_SYSTEM",
		"GIT_CONFIG_NOSYSTEM",
		"GIT_CONFIG_COUNT",
		"GIT_PREFIX",
		"GIT_INTERNAL_SUPER_PREFIX",
		"GIT_QUARANTINE_PATH",
		"GIT_SHALLOW_FILE",
		"GIT_GRAFT_FILE",
		"GIT_REPLACE_REF_BASE",
		"GIT_NO_REPLACE_OBJECTS":
		return true
	default:
		return strings.HasPrefix(key, "GIT_CONFIG_KEY_") || strings.HasPrefix(key, "GIT_CONFIG_VALUE_")
	}
}

func requireDirectory(path, label string) error {
	info, err := os.Stat(path)
	if err != nil {
		return fmt.Errorf("authenticate %s: %w", label, err)
	}
	if !info.IsDir() {
		return fmt.Errorf("authenticate %s: %s is not a directory", label, path)
	}
	return nil
}

func verifyLinkedWorktreePointers(repository *repositoryRoot, worktreePath, gitDirectory string) error {
	pointer, err := repository.readRegular(".git", ".git", maxGitPointerBytes)
	if err != nil {
		return fmt.Errorf("authenticate linked-worktree pointer on retained root %s: %w", repository.identity(), err)
	}
	pointerLine, err := oneLine(pointer, ".git pointer")
	if err != nil {
		return err
	}
	pointerValue, ok := strings.CutPrefix(pointerLine, "gitdir: ")
	if !ok || strings.TrimSpace(pointerValue) == "" {
		return fmt.Errorf("authenticate linked-worktree pointer: expected one gitdir line")
	}
	if !filepath.IsAbs(pointerValue) {
		return fmt.Errorf("authenticate linked-worktree pointer: gitdir target must be absolute")
	}
	resolvedPointer, err := canonicalExistingPath(pointerValue)
	if err != nil {
		return fmt.Errorf("authenticate linked-worktree pointer target: %w", err)
	}
	if resolvedPointer != gitDirectory {
		return fmt.Errorf("authenticate linked-worktree pointer: .git resolves to %s, Git reported %s", resolvedPointer, gitDirectory)
	}

	gitRoot, err := openRepositoryRoot(gitDirectory)
	if err != nil {
		return fmt.Errorf("retain linked-worktree Git directory: %w", err)
	}
	backPointer, readErr := gitRoot.readRegular("gitdir", "linked-worktree gitdir backlink", maxGitPointerBytes)
	closeErr := gitRoot.close()
	if readErr != nil || closeErr != nil {
		return fmt.Errorf("authenticate linked-worktree backlink: %w", errors.Join(readErr, closeErr))
	}
	backPointerLine, err := oneLine(backPointer, "linked-worktree gitdir backlink")
	if err != nil {
		return err
	}
	if !filepath.IsAbs(backPointerLine) {
		return fmt.Errorf("authenticate linked-worktree backlink: target must be absolute")
	}
	wantBackPointer := filepath.Clean(filepath.Join(worktreePath, ".git"))
	if filepath.Clean(backPointerLine) != wantBackPointer {
		return fmt.Errorf("authenticate linked-worktree backlink: Git directory points to %s, retained worktree path is %s with identity %s", filepath.Clean(backPointerLine), wantBackPointer, repository.identity())
	}
	return nil
}

func oneLine(data []byte, label string) (string, error) {
	line := strings.TrimSuffix(string(data), "\n")
	line = strings.TrimSuffix(line, "\r")
	if line == "" || strings.ContainsAny(line, "\r\n\x00") {
		return "", fmt.Errorf("authenticate %s: expected one non-empty line", label)
	}
	return line, nil
}

func canonicalExistingPath(path string) (string, error) {
	absolute, err := filepath.Abs(path)
	if err != nil {
		return "", err
	}
	resolved, err := filepath.EvalSymlinks(absolute)
	if err != nil {
		return "", err
	}
	return filepath.Clean(resolved), nil
}

func checkDelegates(root *repositoryRoot) error {
	expected, err := expectedDelegates(root)
	if err != nil {
		return err
	}
	for _, item := range projections {
		actual, err := root.readRegular(item.delegate, item.delegate, maxDelegateBytes)
		if err != nil {
			return err
		}
		if string(actual) != expected[item.delegate] {
			return fmt.Errorf("%s: generated delegate is stale; remove it manually, then run tools/skill-projections with -write from the linked-worktree root", item.delegate)
		}
	}
	return rejectUnexpectedMarkers(root, defaultMarkerScanLimits())
}

func writeDelegates(root *repositoryRoot) error {
	return writeDelegatesWithCreator(root, func(root *repositoryRoot, relative string, content []byte) (bool, error) {
		return root.createExclusive(relative, content)
	})
}

func writeDelegatesWithCreator(root *repositoryRoot, create delegateCreator) error {
	expected, err := expectedDelegates(root)
	if err != nil {
		return err
	}
	if err := preflightDelegateTargets(root); err != nil {
		return err
	}
	created := make([]string, 0, len(projections))
	for _, item := range projections {
		content := []byte(expected[item.delegate])
		wasCreated, createErr := create(root, item.delegate, content)
		if wasCreated {
			created = append(created, item.delegate)
		}
		if createErr != nil {
			if len(created) == 0 {
				return fmt.Errorf("create %s without overwriting or deleting any entry: %w", item.delegate, createErr)
			}
			return fmt.Errorf(
				"create %s: %w; write mode never rolls back or deletes possible partial files, so inspect and remove these paths manually before retrying: %s",
				item.delegate,
				createErr,
				strings.Join(created, ", "),
			)
		}
		if !wasCreated {
			return fmt.Errorf("create %s: creator reported success without exclusive creation", item.delegate)
		}
	}
	return nil
}

func preflightDelegateTargets(root *repositoryRoot) error {
	for _, item := range projections {
		absent, err := root.targetAbsent(item.delegate)
		if err != nil {
			return fmt.Errorf("%s: inspect fixed target beneath retained root %s: %w", item.delegate, root.identity(), err)
		}
		if !absent {
			return fmt.Errorf("%s: refusing to overwrite or delete an existing entry; remove it manually only after inspection", item.delegate)
		}
	}
	return nil
}

func expectedDelegates(root *repositoryRoot) (map[string]string, error) {
	expected := make(map[string]string, len(projections))
	for _, item := range projections {
		data, err := root.readRegular(item.canonical, item.canonical, maxCanonicalSkillBytes)
		if err != nil {
			return nil, err
		}
		var meta metadata
		if err := yaml.Unmarshal(frontmatter(data), &meta); err != nil {
			return nil, fmt.Errorf("parse %s metadata: %w", item.canonical, err)
		}
		if meta.Name == "" || meta.Description == "" {
			return nil, fmt.Errorf("%s: canonical metadata requires name and description", item.canonical)
		}
		reference, err := filepath.Rel(filepath.Dir(item.delegate), item.canonical)
		if err != nil {
			return nil, fmt.Errorf("derive reference for %s: %w", item.delegate, err)
		}
		rendered := renderDelegate(meta, filepath.ToSlash(reference))
		if len(rendered) > maxDelegateBytes {
			return nil, fmt.Errorf("%s: rendered delegate exceeds %d-byte limit", item.delegate, maxDelegateBytes)
		}
		expected[item.delegate] = rendered
	}
	return expected, nil
}

func frontmatter(data []byte) []byte {
	text := strings.ReplaceAll(string(data), "\r\n", "\n")
	if !strings.HasPrefix(text, "---\n") {
		return nil
	}
	end := strings.Index(text[4:], "\n---\n")
	if end < 0 {
		return nil
	}
	return []byte(text[4 : 4+end])
}

func renderDelegate(meta metadata, reference string) string {
	return fmt.Sprintf("---\nname: %s\ndescription: %s\n---\n\n# Skill discovery delegate: %s\n\n%s\n\nThis generated discovery delegate points to [the canonical workflow](%s).\n\n## Workflow\n\n1. Read and follow the canonical workflow.\n2. Keep changes in that source; this delegate is regenerated.\n\n## Verify\n\nConfirm `make lint-skills` accepts this unmodified delegate.\n", meta.Name, strconv.Quote(meta.Description), meta.Name, generatedMarker, reference)
}

func rejectUnexpectedMarkers(root *repositoryRoot, limits markerScanLimits) error {
	marked, err := root.scanGeneratedMarkers(limits)
	if err != nil {
		return fmt.Errorf("scan retained repository root %s for unexpected delegates: %w", root.identity(), err)
	}
	expected := make(map[string]bool, len(projections))
	for _, item := range projections {
		expected[item.delegate] = true
	}
	unexpected := make([]string, 0)
	for _, path := range marked {
		if !expected[path] {
			unexpected = append(unexpected, path)
		}
	}
	if len(unexpected) == 0 {
		return nil
	}
	sort.Strings(unexpected)
	return fmt.Errorf("unexpected generated delegate marker in %s", strings.Join(unexpected, ", "))
}
