// Command skill-projections checks the two generated regular-file skill
// delegates that point at the canonical SPEC governance workflows.
//
// Usage:
//
//	skill-projections -repo <root>
//	skill-projections -repo <root> -write
package main

import (
	"errors"
	"flag"
	"fmt"
	"io"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"

	"gopkg.in/yaml.v3"
)

const generatedMarker = "<!-- generated by tools/skill-projections; do not edit -->"

type projection struct {
	canonical string
	delegate  string
}

var projections = []projection{
	{canonical: "spec-governance/skills/write-spec/SKILL.md", delegate: ".agents/skills/write-spec/SKILL.md"},
	{canonical: "spec-governance/skills/audit-specs/SKILL.md", delegate: ".agents/skills/audit-specs/SKILL.md"},
}

type metadata struct {
	Name        string `yaml:"name"`
	Description string `yaml:"description"`
}

func main() { os.Exit(run(os.Args[1:], os.Stdout, os.Stderr)) }

func run(args []string, stdout, stderr io.Writer) int {
	flags := flag.NewFlagSet("skill-projections", flag.ContinueOnError)
	flags.SetOutput(stderr)
	repository := flags.String("repo", "", "repository containing the canonical skills")
	write := flags.Bool("write", false, "write the two explicit delegates after validating the canonical sources")
	flags.Usage = func() {
		fmt.Fprintln(stderr, "Usage: skill-projections -repo <root> [-write]")
		flags.PrintDefaults()
	}
	if err := flags.Parse(args); err != nil || *repository == "" || flags.NArg() != 0 {
		flags.Usage()
		return 2
	}
	root, err := filepath.Abs(*repository)
	if err != nil {
		fmt.Fprintf(stderr, "skill-projections: resolve repository: %v\n", err)
		return 2
	}
	if *write {
		if err := writeDelegates(root); err != nil {
			fmt.Fprintf(stderr, "skill-projections: %v\n", err)
			return 1
		}
	}
	if err := checkDelegates(root); err != nil {
		fmt.Fprintf(stderr, "skill-projections: %v\n", err)
		return 1
	}
	fmt.Fprintln(stdout, "ok: 2 canonical skill discovery delegates match their sources")
	return 0
}

func checkDelegates(root string) error {
	expected, err := expectedDelegates(root)
	if err != nil {
		return err
	}
	for _, item := range projections {
		path := filepath.Join(root, filepath.FromSlash(item.delegate))
		info, err := os.Lstat(path)
		if err != nil {
			return fmt.Errorf("%s: %w", item.delegate, err)
		}
		if !info.Mode().IsRegular() {
			return fmt.Errorf("%s: delegate must be a regular file", item.delegate)
		}
		actual, err := os.ReadFile(path)
		if err != nil {
			return fmt.Errorf("read %s: %w", item.delegate, err)
		}
		if string(actual) != expected[item.delegate] {
			return fmt.Errorf("%s: generated delegate is stale; run tools/skill-projections with -write", item.delegate)
		}
	}
	return rejectUnexpectedMarkers(root)
}

func writeDelegates(root string) error {
	expected, err := expectedDelegates(root)
	if err != nil {
		return err
	}
	for _, item := range projections {
		path := filepath.Join(root, filepath.FromSlash(item.delegate))
		if err := ensureSafeParent(root, path); err != nil {
			return fmt.Errorf("%s: %w", item.delegate, err)
		}
		if info, err := os.Lstat(path); err == nil && !info.Mode().IsRegular() {
			return fmt.Errorf("%s: refusing to replace a non-regular file", item.delegate)
		} else if err != nil && !errors.Is(err, fs.ErrNotExist) {
			return fmt.Errorf("%s: stat: %w", item.delegate, err)
		}
		if err := os.WriteFile(path, []byte(expected[item.delegate]), 0o600); err != nil {
			return fmt.Errorf("write %s: %w", item.delegate, err)
		}
	}
	return nil
}

func expectedDelegates(root string) (map[string]string, error) {
	expected := make(map[string]string, len(projections))
	for _, item := range projections {
		canonical := filepath.Join(root, filepath.FromSlash(item.canonical))
		info, err := os.Lstat(canonical)
		if err != nil {
			return nil, fmt.Errorf("%s: %w", item.canonical, err)
		}
		if !info.Mode().IsRegular() {
			return nil, fmt.Errorf("%s: canonical skill must be a regular file", item.canonical)
		}
		data, err := os.ReadFile(canonical)
		if err != nil {
			return nil, fmt.Errorf("read %s: %w", item.canonical, err)
		}
		var meta metadata
		if err := yaml.Unmarshal(frontmatter(data), &meta); err != nil {
			return nil, fmt.Errorf("parse %s metadata: %w", item.canonical, err)
		}
		if meta.Name == "" || meta.Description == "" {
			return nil, fmt.Errorf("%s: canonical metadata requires name and description", item.canonical)
		}
		reference, err := filepath.Rel(filepath.Dir(item.delegate), item.canonical)
		if err != nil {
			return nil, fmt.Errorf("derive reference for %s: %w", item.delegate, err)
		}
		expected[item.delegate] = renderDelegate(meta, filepath.ToSlash(reference))
	}
	return expected, nil
}

func frontmatter(data []byte) []byte {
	text := strings.ReplaceAll(string(data), "\r\n", "\n")
	if !strings.HasPrefix(text, "---\n") {
		return nil
	}
	end := strings.Index(text[4:], "\n---\n")
	if end < 0 {
		return nil
	}
	return []byte(text[4 : 4+end])
}

func renderDelegate(meta metadata, reference string) string {
	return fmt.Sprintf("---\nname: %s\ndescription: %s\n---\n\n# Skill discovery delegate: %s\n\n%s\n\nThis generated discovery delegate points to [the canonical workflow](%s).\n\n## Workflow\n\n1. Read and follow the canonical workflow.\n2. Keep changes in that source; this delegate is regenerated.\n\n## Verify\n\nConfirm `make lint-skills` accepts this unmodified delegate.\n", meta.Name, strconv.Quote(meta.Description), meta.Name, generatedMarker, reference)
}

func ensureSafeParent(root, path string) error {
	root = filepath.Clean(root)
	relative, err := filepath.Rel(root, path)
	if err != nil || relative == ".." || strings.HasPrefix(relative, ".."+string(filepath.Separator)) {
		return fmt.Errorf("delegate path escapes repository")
	}
	directory := root
	for segment := range strings.SplitSeq(filepath.Dir(relative), string(filepath.Separator)) {
		if segment == "." || segment == "" {
			continue
		}
		directory = filepath.Join(directory, segment)
		info, err := os.Lstat(directory)
		switch {
		case errors.Is(err, fs.ErrNotExist):
			if err := os.Mkdir(directory, 0o755); err != nil {
				return err
			}
		case err != nil:
			return err
		case info.Mode()&os.ModeSymlink != 0:
			return fmt.Errorf("refusing to traverse symlinked parent %s", filepath.ToSlash(relative))
		case !info.IsDir():
			return fmt.Errorf("parent is not a directory")
		}
	}
	return nil
}

func rejectUnexpectedMarkers(root string) error {
	rootFS, err := os.OpenRoot(root)
	if err != nil {
		return fmt.Errorf("open repository root: %w", err)
	}
	defer func() { _ = rootFS.Close() }()

	expected := make(map[string]bool, len(projections))
	for _, item := range projections {
		expected[item.delegate] = true
	}
	var unexpected []string
	err = filepath.WalkDir(root, func(path string, entry fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if entry.IsDir() && entry.Name() == ".git" {
			return filepath.SkipDir
		}
		if entry.IsDir() || entry.Type()&os.ModeSymlink != 0 || entry.Name() != "SKILL.md" {
			return nil
		}
		relative, err := filepath.Rel(root, path)
		if err != nil {
			return err
		}
		relative = filepath.ToSlash(relative)
		data, err := rootFS.ReadFile(filepath.FromSlash(relative))
		if err != nil {
			return err
		}
		if !strings.Contains(string(data), generatedMarker) {
			return nil
		}
		if !expected[relative] {
			unexpected = append(unexpected, relative)
		}
		return nil
	})
	if err != nil {
		return fmt.Errorf("scan for unexpected delegates: %w", err)
	}
	if len(unexpected) == 0 {
		return nil
	}
	sort.Strings(unexpected)
	return fmt.Errorf("unexpected generated delegate marker in %s", strings.Join(unexpected, ", "))
}
