package harnesseffort

import (
	"fmt"
	"strings"
)

const (
	codexSentinelBegin = "# --- BEGIN engram-managed profiles ---"
	codexSentinelEnd   = "# --- END engram-managed profiles ---"
)

// codexTierOrder defines the order tiers appear in the generated TOML block.
var codexTierOrder = []string{"lookup", "operational", "analysis", "deep"}

// GenerateCodex produces the full content for ~/.codex/config.toml.
// If existingContent is non-empty, the managed sentinel block is replaced.
// If no sentinel block exists, the managed block is appended.
// If existingContent is empty, only the managed block is returned.
func GenerateCodex(cfg HarnessEffortConfig, existingContent string) (string, error) {
	block := buildCodexBlock(cfg)

	if existingContent == "" {
		return block, nil
	}

	beginIdx := strings.Index(existingContent, codexSentinelBegin)
	endIdx := strings.Index(existingContent, codexSentinelEnd)

	if beginIdx >= 0 && endIdx >= 0 && endIdx > beginIdx {
		// Replace managed block in-place
		before := existingContent[:beginIdx]
		after := existingContent[endIdx+len(codexSentinelEnd):]
		// Trim trailing newlines from before, leading newlines from after
		before = strings.TrimRight(before, "\n")
		after = strings.TrimLeft(after, "\n")
		var result string
		if before == "" {
			result = block
		} else {
			result = before + "\n" + block
		}
		if after != "" {
			result += "\n" + after
		}
		if !strings.HasSuffix(result, "\n") {
			result += "\n"
		}
		return result, nil
	}

	// No sentinels found: append at end
	result := strings.TrimRight(existingContent, "\n") + "\n\n" + block
	return result, nil
}

// buildCodexBlock generates the sentinel-wrapped TOML profile block.
func buildCodexBlock(cfg HarnessEffortConfig) string {
	var sb strings.Builder
	sb.WriteString(codexSentinelBegin + "\n")
	sb.WriteString("# Generated by: engram config apply-harness-effort\n")
	sb.WriteString("# Do not edit this section manually.\n")

	for _, tierName := range codexTierOrder {
		if cfg.Tiers == nil {
			continue
		}
		tier, exists := cfg.Tiers[tierName]
		if !exists {
			continue
		}
		prov, exists := tier.Providers["openai"]
		if !exists {
			continue
		}
		fmt.Fprintf(&sb, "\n[profiles.%s]\n", tierName)
		fmt.Fprintf(&sb, "model = %q\n", prov.Model)
		if prov.ReasoningEffort != "" {
			fmt.Fprintf(&sb, "reasoning_effort = %q\n", prov.ReasoningEffort)
		}
	}

	sb.WriteString(codexSentinelEnd + "\n")
	return sb.String()
}
