package harnesseffort

import (
	"fmt"
	"strings"
)

// geminiTierModelMap maps effort tiers to Gemini model names.
// flash is used for low/medium effort tiers; pro for high effort tiers.
var geminiTierModelMap = map[string]string{
	"lookup":      "gemini-2.5-flash",
	"operational": "gemini-2.5-flash",
	"analysis":    "gemini-2.5-pro",
	"deep":        "gemini-2.5-pro",
}

// geminiTierOrder defines the order tiers appear in alias output.
var geminiTierOrder = []string{"lookup", "operational", "analysis", "deep"}

// GenerateGemini returns shell alias suggestions for Gemini tier selection.
// Does not write any files. Output is intended to be printed to stdout.
func GenerateGemini(cfg HarnessEffortConfig) string {
	var sb strings.Builder
	sb.WriteString("# Gemini effort tier aliases (generated by: engram config apply-harness-effort)\n")
	sb.WriteString("# Add these to ~/.bashrc or ~/.zshrc, then run: source ~/.bashrc\n")

	for _, tierName := range geminiTierOrder {
		model := geminiTierModelFromCfg(cfg, tierName)
		fmt.Fprintf(&sb, "alias gemini-%s='gemini -m %s'\n", tierName, model)
	}

	return sb.String()
}

// geminiTierModelFromCfg returns the Gemini model for the given tier.
// Falls back to geminiTierModelMap defaults if the tier is not in cfg.
func geminiTierModelFromCfg(cfg HarnessEffortConfig, tierName string) string {
	if cfg.Tiers != nil {
		if tier, ok := cfg.Tiers[tierName]; ok {
			if prov, ok := tier.Providers["google"]; ok && prov.Model != "" {
				return prov.Model
			}
		}
	}
	if model, ok := geminiTierModelMap[tierName]; ok {
		return model
	}
	return "gemini-2.5-flash"
}
