#!/bin/bash
# AGM Post-Install Hook
# Initializes AGM configuration after component installation

set -euo pipefail

WORKSPACE_ROOT=$1
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

echo "AGM Post-Install Configuration"
echo "Workspace: ${WORKSPACE_ROOT}"
echo

# Step 1: Create default session directory
SESSION_DIR="${HOME}/.agm/sessions"
if [ ! -d "${SESSION_DIR}" ]; then
    mkdir -p "${SESSION_DIR}"
    echo "✓ Created session directory: ${SESSION_DIR}"
else
    echo "✓ Session directory already exists: ${SESSION_DIR}"
fi

# Step 2: Create cache directory
CACHE_DIR="${HOME}/.agm-cache"
if [ ! -d "${CACHE_DIR}" ]; then
    mkdir -p "${CACHE_DIR}"
    echo "✓ Created cache directory: ${CACHE_DIR}"
else
    echo "✓ Cache directory already exists: ${CACHE_DIR}"
fi

# Step 3: Generate initial configuration file (if not exists)
CONFIG_FILE="${HOME}/.agm/config.yaml"
if [ ! -f "${CONFIG_FILE}" ]; then
    cat > "${CONFIG_FILE}" << 'EOF'
# AGM Configuration
# Auto-generated by component installer

version: 1

# Session management
sessions:
  timeout_hours: 24
  max_active: 50
  auto_archive_after_days: 30

# Default model
default_model: claude-sonnet-4-5

# Agent mode
default_agent_mode: implementer

# Workspace integration
workspace:
  auto_detect: true
  default: oss
EOF
    echo "✓ Created configuration file: ${CONFIG_FILE}"
else
    echo "✓ Configuration file already exists: ${CONFIG_FILE}"
fi

# Step 4: Mark as initialized
touch "${WORKSPACE_ROOT}/.agm-initialized"
echo "✓ Marked workspace as AGM-initialized"

# Step 5: Install configure-claude-settings and register hooks
if command -v configure-claude-settings >/dev/null 2>&1; then
    echo "✓ configure-claude-settings already installed"
else
    REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
    if [ -f "${REPO_ROOT}/cmd/configure-claude-settings/main.go" ]; then
        echo "  Building configure-claude-settings..."
        (cd "${REPO_ROOT}" && go build -o "${HOME}/go/bin/configure-claude-settings" ./cmd/configure-claude-settings/) 2>/dev/null && \
            echo "✓ Installed configure-claude-settings" || \
            echo "⚠ Could not build configure-claude-settings (optional)"
    fi
fi

# Step 5b: Register AGM hooks in settings.json via configure-claude-settings
if command -v configure-claude-settings >/dev/null 2>&1; then
    agm admin install-hooks 2>/dev/null && \
        echo "✓ AGM hooks registered in settings.json" || \
        echo "⚠ Hook registration skipped (run 'agm admin install-hooks' manually)"
fi

# Step 6: Register with Corpus Callosum (if installed)
if "${SCRIPT_DIR}/register-corpus-callosum.sh"; then
    echo "✓ AGM schemas registered with Corpus Callosum"
else
    echo "✓ Corpus Callosum registration skipped (CLI not available or registration failed)"
fi

# Step 7: Display setup instructions
echo
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "✅ AGM Installation Complete!"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo
echo "Quick Start:"
echo "  1. Create session:    agm new \"My First Session\""
echo "  2. List sessions:     agm list"
echo "  3. Attach to session: agm attach <session-name>"
echo "  4. Kill session:      agm kill <session-name>"
echo
echo "Configuration: ${CONFIG_FILE}"
echo "Sessions:      ${SESSION_DIR}"
echo
echo "For help: agm --help"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
