//go:build ignore

// Code generated by codegen. DO NOT EDIT.
// Format version: 1

package surface

import (
	"context"

	"github.com/modelcontextprotocol/go-sdk/mcp"
)

// ListSessionsMCPInput is the MCP input schema for list_sessions.
type ListSessionsMCPInput struct {
	Status  string `json:"status,omitempty" jsonschema:"description=Filter by session status,enum=active, archived, all"`
	Harness string `json:"harness,omitempty" jsonschema:"description=Filter by agent type,enum=claude-code, gemini-cli, codex, opencode, all"`
	Limit   int    `json:"limit,omitempty" jsonschema:"description=Maximum sessions to return (1-1000)"`
	Offset  int    `json:"offset,omitempty" jsonschema:"description=Pagination offset"`
}

// AddListSessionsTool registers the agm_list_sessions MCP tool.
func AddListSessionsTool(server *mcp.Server, newOpCtx func() (*OpContext, func(), error)) {
	mcp.AddTool(server, &mcp.Tool{
		Name:        "agm_list_sessions",
		Description: "List AGM sessions. Use when you need to see all active sessions or find sessions by status/type.",
	}, func(_ context.Context, _ *mcp.CallToolRequest, input ListSessionsMCPInput) (*mcp.CallToolResult, any, error) {
		opCtx, cleanup, err := newOpCtx()
		if err != nil {
			return mcpError(err), nil, nil
		}
		defer cleanup()

		req := &ListSessionsRequest{

			Status:  input.Status,
			Harness: input.Harness,
			Limit:   input.Limit,
			Offset:  input.Offset,
		}

		result, opErr := ListSessions(opCtx, req)
		if opErr != nil {
			return mcpError(opErr), nil, nil
		}

		return mcpSuccess(result), result, nil
	})
}

// GetSessionMCPInput is the MCP input schema for get_session.
type GetSessionMCPInput struct {
	Identifier string `json:"identifier" jsonschema:"description=Session ID, name, or UUID prefix,required"`
}

// AddGetSessionTool registers the agm_get_session MCP tool.
func AddGetSessionTool(server *mcp.Server, newOpCtx func() (*OpContext, func(), error)) {
	mcp.AddTool(server, &mcp.Tool{
		Name:        "agm_get_session",
		Description: "Get detailed metadata for an AGM session. Use when you need full session details by ID or name.",
	}, func(_ context.Context, _ *mcp.CallToolRequest, input GetSessionMCPInput) (*mcp.CallToolResult, any, error) {
		opCtx, cleanup, err := newOpCtx()
		if err != nil {
			return mcpError(err), nil, nil
		}
		defer cleanup()

		req := &GetSessionRequest{

			Identifier: input.Identifier,
		}

		result, opErr := GetSession(opCtx, req)
		if opErr != nil {
			return mcpError(opErr), nil, nil
		}

		return mcpSuccess(result), result, nil
	})
}

// SearchSessionsMCPInput is the MCP input schema for search_sessions.
type SearchSessionsMCPInput struct {
	Query  string `json:"query" jsonschema:"description=Search query for session names (case-insensitive),required"`
	Status string `json:"status,omitempty" jsonschema:"description=Filter by session status,enum=active, archived, all"`
	Limit  int    `json:"limit,omitempty" jsonschema:"description=Maximum results to return (1-50)"`
}

// AddSearchSessionsTool registers the agm_search_sessions MCP tool.
func AddSearchSessionsTool(server *mcp.Server, newOpCtx func() (*OpContext, func(), error)) {
	mcp.AddTool(server, &mcp.Tool{
		Name:        "agm_search_sessions",
		Description: "Search AGM sessions by name. Use when you need to find a specific session by partial name match.",
	}, func(_ context.Context, _ *mcp.CallToolRequest, input SearchSessionsMCPInput) (*mcp.CallToolResult, any, error) {
		opCtx, cleanup, err := newOpCtx()
		if err != nil {
			return mcpError(err), nil, nil
		}
		defer cleanup()

		req := &SearchSessionsRequest{

			Query:  input.Query,
			Status: input.Status,
			Limit:  input.Limit,
		}

		result, opErr := SearchSessions(opCtx, req)
		if opErr != nil {
			return mcpError(opErr), nil, nil
		}

		return mcpSuccess(result), result, nil
	})
}

// GetStatusMCPInput is the MCP input schema for get_status.
type GetStatusMCPInput struct {
	IncludeArchived bool `json:"include_archived,omitempty" jsonschema:"description=Include archived sessions in the status report"`
}

// AddGetStatusTool registers the agm_get_status MCP tool.
func AddGetStatusTool(server *mcp.Server, newOpCtx func() (*OpContext, func(), error)) {
	mcp.AddTool(server, &mcp.Tool{
		Name:        "agm_get_status",
		Description: "Get live status of all AGM sessions with summary counts. Use for dashboard views.",
	}, func(_ context.Context, _ *mcp.CallToolRequest, input GetStatusMCPInput) (*mcp.CallToolResult, any, error) {
		opCtx, cleanup, err := newOpCtx()
		if err != nil {
			return mcpError(err), nil, nil
		}
		defer cleanup()

		req := &GetStatusRequest{

			IncludeArchived: input.IncludeArchived,
		}

		result, opErr := GetStatus(opCtx, req)
		if opErr != nil {
			return mcpError(opErr), nil, nil
		}

		return mcpSuccess(result), result, nil
	})
}

// ArchiveSessionMCPInput is the MCP input schema for archive_session.
type ArchiveSessionMCPInput struct {
	Identifier string `json:"identifier" jsonschema:"description=Session ID, name, or UUID prefix,required"`
}

// AddArchiveSessionTool registers the agm_archive_session MCP tool.
func AddArchiveSessionTool(server *mcp.Server, newOpCtx func() (*OpContext, func(), error)) {
	mcp.AddTool(server, &mcp.Tool{
		Name:        "agm_archive_session",
		Description: "Archive an AGM session by marking it as archived. Use when a session is no longer needed and should be hidden from the active list.",
	}, func(_ context.Context, _ *mcp.CallToolRequest, input ArchiveSessionMCPInput) (*mcp.CallToolResult, any, error) {
		opCtx, cleanup, err := newOpCtx()
		if err != nil {
			return mcpError(err), nil, nil
		}
		defer cleanup()

		req := &ArchiveSessionRequest{

			Identifier: input.Identifier,
		}

		result, opErr := ArchiveSession(opCtx, req)
		if opErr != nil {
			return mcpError(opErr), nil, nil
		}

		return mcpSuccess(result), result, nil
	})
}

// KillSessionMCPInput is the MCP input schema for kill_session.
type KillSessionMCPInput struct {
	Identifier string `json:"identifier" jsonschema:"description=Session ID, name, or UUID prefix,required"`
}

// AddKillSessionTool registers the agm_kill_session MCP tool.
func AddKillSessionTool(server *mcp.Server, newOpCtx func() (*OpContext, func(), error)) {
	mcp.AddTool(server, &mcp.Tool{
		Name:        "agm_kill_session",
		Description: "Kill the tmux session for an AGM session. Use when a session is stuck or unresponsive and needs to be force-stopped.",
	}, func(_ context.Context, _ *mcp.CallToolRequest, input KillSessionMCPInput) (*mcp.CallToolResult, any, error) {
		opCtx, cleanup, err := newOpCtx()
		if err != nil {
			return mcpError(err), nil, nil
		}
		defer cleanup()

		req := &KillSessionRequest{

			Identifier: input.Identifier,
		}

		result, opErr := KillSession(opCtx, req)
		if opErr != nil {
			return mcpError(opErr), nil, nil
		}

		return mcpSuccess(result), result, nil
	})
}

// ListOpsMCPInput is the MCP input schema for list_ops.
type ListOpsMCPInput struct {
}

// AddListOpsTool registers the agm_list_ops MCP tool.
func AddListOpsTool(server *mcp.Server, newOpCtx func() (*OpContext, func(), error)) {
	mcp.AddTool(server, &mcp.Tool{
		Name:        "agm_list_ops",
		Description: "List all available AGM operations. Use for schema discovery and to see what tools are available.",
	}, func(_ context.Context, _ *mcp.CallToolRequest, input ListOpsMCPInput) (*mcp.CallToolResult, any, error) {
		opCtx, cleanup, err := newOpCtx()
		if err != nil {
			return mcpError(err), nil, nil
		}
		defer cleanup()

		req := &ListOpsRequest{}

		result, opErr := ListOps(opCtx, req)
		if opErr != nil {
			return mcpError(opErr), nil, nil
		}

		return mcpSuccess(result), result, nil
	})
}
