//go:build ignore

// Code generated by codegen. DO NOT EDIT.
// Format version: 1

package surface

import (
	"context"

	"github.com/modelcontextprotocol/go-sdk/mcp"
)

// ListSessionsMCPInput is the MCP input schema for list_sessions.
type ListSessionsMCPInput struct {
	Status  string `json:"status,omitempty" jsonschema:"description=Filter by session status,enum=active, archived, all"`
	Harness string `json:"harness,omitempty" jsonschema:"description=Filter by harness; gemini-cli is deprecated,enum=claude-code, codex-cli, agy, opencode-cli, pi-cli, gemini-cli, all"`
	Limit   int    `json:"limit,omitempty" jsonschema:"description=Maximum sessions to return (1-1000)"`
	Offset  int    `json:"offset,omitempty" jsonschema:"description=Pagination offset"`
}

// AddListSessionsTool registers the agm_list_sessions MCP tool.
func AddListSessionsTool(server *mcp.Server, newOpCtx func() (*OpContext, func(), error)) {
	mcp.AddTool(server, &mcp.Tool{
		Name:        "agm_list_sessions",
		Description: "List AGM sessions. Use when you need to see all active sessions or find sessions by status/type.",
	}, func(_ context.Context, _ *mcp.CallToolRequest, input ListSessionsMCPInput) (*mcp.CallToolResult, any, error) {
		opCtx, cleanup, err := newOpCtx()
		if err != nil {
			return mcpError(err), nil, nil
		}
		defer cleanup()

		req := &ListSessionsRequest{

			Status:  input.Status,
			Harness: input.Harness,
			Limit:   input.Limit,
			Offset:  input.Offset,
		}

		result, opErr := ListSessions(opCtx, req)
		if opErr != nil {
			return mcpError(opErr), nil, nil
		}

		return mcpSuccess(result), result, nil
	})
}

// GetSessionMCPInput is the MCP input schema for get_session.
type GetSessionMCPInput struct {
	Identifier string `json:"identifier" jsonschema:"description=Session ID, name, or UUID prefix,required"`
}

// AddGetSessionTool registers the agm_get_session MCP tool.
func AddGetSessionTool(server *mcp.Server, newOpCtx func() (*OpContext, func(), error)) {
	mcp.AddTool(server, &mcp.Tool{
		Name:        "agm_get_session",
		Description: "Get detailed metadata for an AGM session. Use when you need full session details by ID or name.",
	}, func(_ context.Context, _ *mcp.CallToolRequest, input GetSessionMCPInput) (*mcp.CallToolResult, any, error) {
		opCtx, cleanup, err := newOpCtx()
		if err != nil {
			return mcpError(err), nil, nil
		}
		defer cleanup()

		req := &GetSessionRequest{

			Identifier: input.Identifier,
		}

		result, opErr := GetSession(opCtx, req)
		if opErr != nil {
			return mcpError(opErr), nil, nil
		}

		return mcpSuccess(result), result, nil
	})
}

// GetSessionOutputMCPInput is the MCP input schema for get_session_output.
type GetSessionOutputMCPInput struct {
	Identifier string `json:"identifier" jsonschema:"description=Session ID, name, or UUID prefix,required"`
	Lines      int    `json:"lines,omitempty" jsonschema:"description=Trailing pane lines to capture (default 100, max 2000)"`
}

// AddGetSessionOutputTool registers the agm_get_session_output MCP tool.
func AddGetSessionOutputTool(server *mcp.Server, newOpCtx func() (*OpContext, func(), error)) {
	mcp.AddTool(server, &mcp.Tool{
		Name:        "agm_get_session_output",
		Description: "Read the tail of an AGM session's terminal output — live pane while running, durable final capture after completion. Use to collect a worker's result without attaching to its pane.",
	}, func(_ context.Context, _ *mcp.CallToolRequest, input GetSessionOutputMCPInput) (*mcp.CallToolResult, any, error) {
		opCtx, cleanup, err := newOpCtx()
		if err != nil {
			return mcpError(err), nil, nil
		}
		defer cleanup()

		req := &GetSessionOutputRequest{

			Identifier: input.Identifier,
			Lines:      input.Lines,
		}

		result, opErr := GetSessionOutput(opCtx, req)
		if opErr != nil {
			return mcpError(opErr), nil, nil
		}

		return mcpSuccess(result), result, nil
	})
}

// SearchSessionsMCPInput is the MCP input schema for search_sessions.
type SearchSessionsMCPInput struct {
	Query  string `json:"query" jsonschema:"description=Search query for session names (case-insensitive),required"`
	Status string `json:"status,omitempty" jsonschema:"description=Filter by session status,enum=active, archived, all"`
	Limit  int    `json:"limit,omitempty" jsonschema:"description=Maximum results to return (1-50)"`
}

// AddSearchSessionsTool registers the agm_search_sessions MCP tool.
func AddSearchSessionsTool(server *mcp.Server, newOpCtx func() (*OpContext, func(), error)) {
	mcp.AddTool(server, &mcp.Tool{
		Name:        "agm_search_sessions",
		Description: "Search AGM sessions by name. Use when you need to find a specific session by partial name match.",
	}, func(_ context.Context, _ *mcp.CallToolRequest, input SearchSessionsMCPInput) (*mcp.CallToolResult, any, error) {
		opCtx, cleanup, err := newOpCtx()
		if err != nil {
			return mcpError(err), nil, nil
		}
		defer cleanup()

		req := &SearchSessionsRequest{

			Query:  input.Query,
			Status: input.Status,
			Limit:  input.Limit,
		}

		result, opErr := SearchSessions(opCtx, req)
		if opErr != nil {
			return mcpError(opErr), nil, nil
		}

		return mcpSuccess(result), result, nil
	})
}

// GetStatusMCPInput is the MCP input schema for get_status.
type GetStatusMCPInput struct {
	IncludeArchived bool `json:"include_archived,omitempty" jsonschema:"description=Include archived sessions in the status report"`
}

// AddGetStatusTool registers the agm_get_status MCP tool.
func AddGetStatusTool(server *mcp.Server, newOpCtx func() (*OpContext, func(), error)) {
	mcp.AddTool(server, &mcp.Tool{
		Name:        "agm_get_status",
		Description: "Get live status of all AGM sessions with summary counts. Use for dashboard views.",
	}, func(_ context.Context, _ *mcp.CallToolRequest, input GetStatusMCPInput) (*mcp.CallToolResult, any, error) {
		opCtx, cleanup, err := newOpCtx()
		if err != nil {
			return mcpError(err), nil, nil
		}
		defer cleanup()

		req := &GetStatusRequest{

			IncludeArchived: input.IncludeArchived,
		}

		result, opErr := GetStatus(opCtx, req)
		if opErr != nil {
			return mcpError(opErr), nil, nil
		}

		return mcpSuccess(result), result, nil
	})
}

// GetCompletionRelayTargetMCPInput is the MCP input schema for get_completion_relay_target.
type GetCompletionRelayTargetMCPInput struct {
}

// AddGetCompletionRelayTargetTool registers the agm_get_completion_relay_target MCP tool.
func AddGetCompletionRelayTargetTool(server *mcp.Server, newOpCtx func() (*OpContext, func(), error)) {
	mcp.AddTool(server, &mcp.Tool{
		Name:        "agm_get_completion_relay_target",
		Description: "Read the live AGM completion relay target. Use before relying on completion notifications from AGM-created sessions.",
	}, func(_ context.Context, _ *mcp.CallToolRequest, input GetCompletionRelayTargetMCPInput) (*mcp.CallToolResult, any, error) {
		opCtx, cleanup, err := newOpCtx()
		if err != nil {
			return mcpError(err), nil, nil
		}
		defer cleanup()

		req := &GetCompletionRelayTargetInput{}

		result, opErr := GetCompletionRelayTarget(opCtx, req)
		if opErr != nil {
			return mcpError(opErr), nil, nil
		}

		return mcpSuccess(result), result, nil
	})
}

// GetQuotaStatusMCPInput is the MCP input schema for get_quota_status.
type GetQuotaStatusMCPInput struct {
	Provider string `json:"provider,omitempty" jsonschema:"description=Provider quota to read. Defaults to codex."`
}

// AddGetQuotaStatusTool registers the agm_get_quota_status MCP tool.
func AddGetQuotaStatusTool(server *mcp.Server, newOpCtx func() (*OpContext, func(), error)) {
	mcp.AddTool(server, &mcp.Tool{
		Name:        "agm_get_quota_status",
		Description: "Read the latest provider quota status captured by CodexBar. Use to pace Dispatch work when a provider is throttled or near-empty.",
	}, func(_ context.Context, _ *mcp.CallToolRequest, input GetQuotaStatusMCPInput) (*mcp.CallToolResult, any, error) {
		opCtx, cleanup, err := newOpCtx()
		if err != nil {
			return mcpError(err), nil, nil
		}
		defer cleanup()

		req := &QuotaStatusInput{

			Provider: input.Provider,
		}

		result, opErr := GetQuotaStatus(opCtx, req)
		if opErr != nil {
			return mcpError(opErr), nil, nil
		}

		return mcpSuccess(result), result, nil
	})
}

// ArchiveSessionMCPInput is the MCP input schema for archive_session.
type ArchiveSessionMCPInput struct {
	Identifier string `json:"identifier" jsonschema:"description=Session ID, name, or UUID prefix,required"`
}

// AddArchiveSessionTool registers the agm_archive_session MCP tool.
func AddArchiveSessionTool(server *mcp.Server, newOpCtx func() (*OpContext, func(), error)) {
	mcp.AddTool(server, &mcp.Tool{
		Name:        "agm_archive_session",
		Description: "Archive an AGM session by marking it as archived. Use when a session is no longer needed and should be hidden from the active list.",
	}, func(_ context.Context, _ *mcp.CallToolRequest, input ArchiveSessionMCPInput) (*mcp.CallToolResult, any, error) {
		opCtx, cleanup, err := newOpCtx()
		if err != nil {
			return mcpError(err), nil, nil
		}
		defer cleanup()

		req := &ArchiveSessionRequest{

			Identifier: input.Identifier,
		}

		result, opErr := ArchiveSession(opCtx, req)
		if opErr != nil {
			return mcpError(opErr), nil, nil
		}

		return mcpSuccess(result), result, nil
	})
}

// KillSessionMCPInput is the MCP input schema for kill_session.
type KillSessionMCPInput struct {
	Identifier     string `json:"identifier" jsonschema:"description=Session ID, name, or UUID prefix,required"`
	Force          bool   `json:"force,omitempty" jsonschema:"description=Bypass the recent-activity safety check"`
	ConfirmedStuck bool   `json:"confirmed_stuck,omitempty" jsonschema:"description=Confirm that a live harness is stuck and may be killed"`
}

// AddKillSessionTool registers the agm_kill_session MCP tool.
func AddKillSessionTool(server *mcp.Server, newOpCtx func() (*OpContext, func(), error)) {
	mcp.AddTool(server, &mcp.Tool{
		Name:        "agm_kill_session",
		Description: "Kill the tmux session for an AGM session. Use when a session is stuck or unresponsive and needs to be force-stopped.",
	}, func(_ context.Context, _ *mcp.CallToolRequest, input KillSessionMCPInput) (*mcp.CallToolResult, any, error) {
		opCtx, cleanup, err := newOpCtx()
		if err != nil {
			return mcpError(err), nil, nil
		}
		defer cleanup()

		req := &KillSessionRequest{

			Identifier:     input.Identifier,
			Force:          input.Force,
			ConfirmedStuck: input.ConfirmedStuck,
		}

		result, opErr := KillSession(opCtx, req)
		if opErr != nil {
			return mcpError(opErr), nil, nil
		}

		return mcpSuccess(result), result, nil
	})
}

// SetCompletionRelayTargetMCPInput is the MCP input schema for set_completion_relay_target.
type SetCompletionRelayTargetMCPInput struct {
	SessionID string `json:"session_id" jsonschema:"description=Live Dispatch/AGM session ID or name that should receive completion relays (required),required"`
}

// AddSetCompletionRelayTargetTool registers the agm_set_completion_relay_target MCP tool.
func AddSetCompletionRelayTargetTool(server *mcp.Server, newOpCtx func() (*OpContext, func(), error)) {
	mcp.AddTool(server, &mcp.Tool{
		Name:        "agm_set_completion_relay_target",
		Description: "Set the live Dispatch/AGM session that receives completion relays from the watcher. Takes effect without restarting the watcher.",
	}, func(_ context.Context, _ *mcp.CallToolRequest, input SetCompletionRelayTargetMCPInput) (*mcp.CallToolResult, any, error) {
		opCtx, cleanup, err := newOpCtx()
		if err != nil {
			return mcpError(err), nil, nil
		}
		defer cleanup()

		req := &SetCompletionRelayTargetInput{

			SessionID: input.SessionID,
		}

		result, opErr := SetCompletionRelayTarget(opCtx, req)
		if opErr != nil {
			return mcpError(opErr), nil, nil
		}

		return mcpSuccess(result), result, nil
	})
}

// ListOpsMCPInput is the MCP input schema for list_ops.
type ListOpsMCPInput struct {
}

// AddListOpsTool registers the agm_list_ops MCP tool.
func AddListOpsTool(server *mcp.Server, newOpCtx func() (*OpContext, func(), error)) {
	mcp.AddTool(server, &mcp.Tool{
		Name:        "agm_list_ops",
		Description: "List all available AGM operations. Use for schema discovery and to see what tools are available.",
	}, func(_ context.Context, _ *mcp.CallToolRequest, input ListOpsMCPInput) (*mcp.CallToolResult, any, error) {
		opCtx, cleanup, err := newOpCtx()
		if err != nil {
			return mcpError(err), nil, nil
		}
		defer cleanup()

		req := &ListOpsRequest{}

		result, opErr := ListOps(opCtx, req)
		if opErr != nil {
			return mcpError(opErr), nil, nil
		}

		return mcpSuccess(result), result, nil
	})
}
