//go:build ignore

// Code generated by codegen. DO NOT EDIT.
// Format version: 1

package surface

import (
	"fmt"

	"github.com/spf13/cobra"
)

// OpCtxFunc creates an OpContext from a Cobra command.
type OpCtxFunc func(cmd *cobra.Command) (*OpContext, func(), error)

// NewListSessionsCmd creates the Cobra command for list_sessions.
func NewListSessionsCmd(newOpCtx OpCtxFunc) *cobra.Command {
	cmd := &cobra.Command{
		Use:     "list [flags]",
		Short:   "List AGM sessions with filters",
		Aliases: []string{"ls"},
		RunE: func(cmd *cobra.Command, args []string) error {

			opCtx, cleanup, err := newOpCtx(cmd)
			if err != nil {
				return fmt.Errorf("failed to create context: %w", err)
			}
			defer cleanup()

			req := &ListSessionsRequest{}

			req.Status, _ = cmd.Flags().GetString("status")
			req.Harness, _ = cmd.Flags().GetString("harness")
			req.Limit, _ = cmd.Flags().GetInt("limit")
			req.Offset, _ = cmd.Flags().GetInt("offset")

			// Validate enum for status
			switch req.Status {
			case "active", "archived", "all":
				// valid
			default:
				return fmt.Errorf("invalid value for --status: %q (allowed: active, archived, all)", req.Status)
			}
			// Validate enum for harness
			switch req.Harness {
			case "claude-code", "gemini-cli", "codex", "opencode", "all":
				// valid
			default:
				return fmt.Errorf("invalid value for --harness: %q (allowed: claude-code, gemini-cli, codex, opencode, all)", req.Harness)
			}

			result, opErr := ListSessions(opCtx, req)
			if opErr != nil {
				return opErr
			}

			_ = result
			fmt.Println("OK")
			return nil
		},
	}

	cmd.Flags().StringP("status", "s", "active", "Filter by session status (allowed: active, archived, all)")
	cmd.Flags().StringP("harness", "H", "", "Filter by agent type (allowed: claude-code, gemini-cli, codex, opencode, all)")
	cmd.Flags().IntP("limit", "n", 100, "Maximum sessions to return (1-1000)")
	cmd.Flags().Int("offset", 0, "Pagination offset")

	return cmd
}

// NewGetSessionCmd creates the Cobra command for get_session.
func NewGetSessionCmd(newOpCtx OpCtxFunc) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "get <identifier>",
		Short: "Get detailed session metadata by ID or name",
		RunE: func(cmd *cobra.Command, args []string) error {

			opCtx, cleanup, err := newOpCtx(cmd)
			if err != nil {
				return fmt.Errorf("failed to create context: %w", err)
			}
			defer cleanup()

			req := &GetSessionRequest{}

			if len(args) > 0 {
				req.Identifier = args[0]
			}

			result, opErr := GetSession(opCtx, req)
			if opErr != nil {
				return opErr
			}

			_ = result
			fmt.Println("OK")
			return nil
		},
	}

	return cmd
}

// NewSearchSessionsCmd creates the Cobra command for search_sessions.
func NewSearchSessionsCmd(newOpCtx OpCtxFunc) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "search <query>",
		Short: "Search sessions by name with relevance scoring",
		RunE: func(cmd *cobra.Command, args []string) error {

			opCtx, cleanup, err := newOpCtx(cmd)
			if err != nil {
				return fmt.Errorf("failed to create context: %w", err)
			}
			defer cleanup()

			req := &SearchSessionsRequest{}

			if len(args) > 0 {
				req.Query = args[0]
			}
			req.Status, _ = cmd.Flags().GetString("status")
			req.Limit, _ = cmd.Flags().GetInt("limit")

			// Validate enum for status
			switch req.Status {
			case "active", "archived", "all":
				// valid
			default:
				return fmt.Errorf("invalid value for --status: %q (allowed: active, archived, all)", req.Status)
			}

			result, opErr := SearchSessions(opCtx, req)
			if opErr != nil {
				return opErr
			}

			_ = result
			fmt.Println("OK")
			return nil
		},
	}

	cmd.Flags().StringP("status", "s", "active", "Filter by session status (allowed: active, archived, all)")
	cmd.Flags().IntP("limit", "n", 10, "Maximum results to return (1-50)")

	return cmd
}

// NewGetStatusCmd creates the Cobra command for get_status.
func NewGetStatusCmd(newOpCtx OpCtxFunc) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "status [flags]",
		Short: "Get live status of all sessions with summary counts",
		RunE: func(cmd *cobra.Command, args []string) error {

			opCtx, cleanup, err := newOpCtx(cmd)
			if err != nil {
				return fmt.Errorf("failed to create context: %w", err)
			}
			defer cleanup()

			req := &GetStatusRequest{}

			req.IncludeArchived, _ = cmd.Flags().GetBool("include-archived")

			result, opErr := GetStatus(opCtx, req)
			if opErr != nil {
				return opErr
			}

			_ = result
			fmt.Println("OK")
			return nil
		},
	}

	cmd.Flags().BoolP("include-archived", "a", false, "Include archived sessions in the status report")

	return cmd
}

// NewArchiveSessionCmd creates the Cobra command for archive_session.
func NewArchiveSessionCmd(newOpCtx OpCtxFunc) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "archive <identifier>",
		Short: "Archive a session",
		RunE: func(cmd *cobra.Command, args []string) error {

			opCtx, cleanup, err := newOpCtx(cmd)
			if err != nil {
				return fmt.Errorf("failed to create context: %w", err)
			}
			defer cleanup()

			req := &ArchiveSessionRequest{}

			if len(args) > 0 {
				req.Identifier = args[0]
			}

			result, opErr := ArchiveSession(opCtx, req)
			if opErr != nil {
				return opErr
			}

			_ = result
			fmt.Println("OK")
			return nil
		},
	}

	return cmd
}

// NewKillSessionCmd creates the Cobra command for kill_session.
func NewKillSessionCmd(newOpCtx OpCtxFunc) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "kill <identifier>",
		Short: "Terminate a running session",
		RunE: func(cmd *cobra.Command, args []string) error {

			opCtx, cleanup, err := newOpCtx(cmd)
			if err != nil {
				return fmt.Errorf("failed to create context: %w", err)
			}
			defer cleanup()

			req := &KillSessionRequest{}

			if len(args) > 0 {
				req.Identifier = args[0]
			}

			result, opErr := KillSession(opCtx, req)
			if opErr != nil {
				return opErr
			}

			_ = result
			fmt.Println("OK")
			return nil
		},
	}

	return cmd
}
